import type { PreguntaSeguimiento } from "./preguntasSeguimiento";

export const preguntasCardioResp: PreguntaSeguimiento[] = [
  {
    id: "palpitaciones-patron",
    activadores: ["Palpitaciones"],
    texto: "¿Cómo notas las palpitaciones?",
    opciones: [
      "Latidos rápidos",
      "Latidos irregulares",
      "Latidos rápidos e irregulares",
      "Aparecen con estrés",
      "Aparecen tras cafeína o energéticas",
      "No sabría describirlo",
    ],
  },
  {
    id: "palpitaciones-alarmas",
    activadores: ["Palpitaciones"],
    texto: "¿Aparece alguna de estas señales con las palpitaciones?",
    opciones: [
      "Dolor de pecho",
      "Falta de aire",
      "Desmayo",
      "Sensación de desmayo",
      "Sudor frío",
      "Ninguno",
    ],
    esAlarma: true,
  },
  {
    id: "tos-patron",
    activadores: ["Tos seca", "Tos con mucosidad"],
    texto: "¿Qué acompaña a la tos?",
    opciones: [
      "Congestión nasal",
      "Mucosidad",
      "Dolor de garganta",
      "Ronquera",
      "Silbidos al respirar",
      "Fiebre",
      "Ninguno",
    ],
  },
  {
    id: "tos-alarmas",
    activadores: ["Tos seca", "Tos con mucosidad"],
    texto: "¿Aparece alguna señal respiratoria de alarma?",
    opciones: [
      "Falta de aire",
      "Falta de aire intensa",
      "Dolor al respirar",
      "Dolor de pecho",
      "No puedo hablar frases completas",
      "Labios azulados",
      "Confusión",
      "Ninguno",
    ],
    esAlarma: true,
  },
  {
    id: "asma-patron",
    activadores: ["Silbidos al respirar", "Falta de aire"],
    texto: "¿Cómo se comportan los síntomas respiratorios?",
    opciones: [
      "Aparecen por episodios y luego mejoran",
      "Aparecen con ejercicio",
      "Aparecen con alergias",
      "Aparecen con aire frío",
      "Aparecen tras una infección respiratoria",
      "Opresión en el pecho",
    ],
  },
  {
    id: "asma-alarmas",
    activadores: ["Silbidos al respirar", "Falta de aire"],
    texto: "¿La dificultad respiratoria es importante?",
    opciones: [
      "Falta de aire intensa",
      "No puedo hablar frases completas",
      "Labios azulados",
      "Confusión",
      "Ninguno",
    ],
    esAlarma: true,
  },
  {
    id: "dolor-pecho-mecanico",
    activadores: ["Dolor de pecho"],
    texto: "¿El dolor de pecho cambia con movimiento o al tocar una zona concreta?",
    opciones: [
      "Dolor de pecho al moverme",
      "Dolor de pecho al tocar",
      "Empeora al respirar profundo",
      "No cambia con movimiento ni al tocar",
    ],
  },
  {
    id: "mareo-ortostatico",
    activadores: ["Mareo", "Sensación de desmayo", "Aparece al levantarme"],
    texto: "¿El mareo aparece al incorporarte?",
    opciones: [
      "Aparece al levantarme",
      "Mejora al sentarme o tumbarme",
      "Bebo poca agua",
      "He cambiado medicación recientemente",
      "No encuentro relación con la postura",
    ],
  },
];