export interface PreguntaSeguimiento {
  id: string;
  activadores: string[];
  texto: string;
  opciones: string[];
  esAlarma?: boolean;
}

export const preguntasSeguimiento: PreguntaSeguimiento[] = [
  {
    id: "dolor-pecho-tipo",
    activadores: ["Dolor de pecho", "Presión en el pecho"],
    texto: "¿Cómo es el dolor o la molestia en el pecho?",
    opciones: [
      "Presión u opresión",
      "Dolor punzante",
      "Quemazón",
      "Dolor al respirar",
      "No sabría describirlo",
    ],
  },
  {
    id: "dolor-pecho-alarma",
    activadores: ["Dolor de pecho", "Presión en el pecho"],
    texto: "¿Tienes alguno de estos síntomas?",
    opciones: [
      "Falta de aire",
      "Sudor frío",
      "Mareo intenso",
      "Náuseas",
      "Dolor hacia brazo, espalda o mandíbula",
      "Ninguno",
    ],
    esAlarma: true,
  },
  {
    id: "dolor-abdominal-zona",
    activadores: ["Dolor abdominal", "Dolor abdomen superior"],
    texto: "¿En qué zona notas el dolor abdominal?",
    opciones: [
      "Parte superior derecha",
      "Parte superior izquierda",
      "Centro",
      "Parte inferior derecha",
      "Parte inferior izquierda",
      "Todo el abdomen",
    ],
  },
  {
    id: "dolor-abdominal-intensidad",
    activadores: ["Dolor abdominal", "Dolor abdomen superior"],
    texto: "¿Qué intensidad tiene el dolor?",
    opciones: ["Leve", "Moderado", "Intenso", "Muy intenso"],
  },
  {
    id: "estrenimiento-duracion",
    activadores: [
      "Heces duras",
      "Esfuerzo al defecar",
      "Menos de tres deposiciones por semana",
      "Estreñimiento",
    ],
    texto: "¿Cuánto tiempo llevas con estreñimiento?",
    opciones: [
      "Uno o dos días",
      "Entre tres días y una semana",
      "Varias semanas",
      "Más de un mes",
    ],
  },
  {
    id: "estrenimiento-alarmas",
    activadores: ["Heces duras", "Esfuerzo al defecar", "Estreñimiento"],
    texto: "¿Aparece alguno de estos signos?",
    opciones: [
      "Sangre en las heces",
      "Vómitos",
      "Fiebre",
      "Dolor abdominal intenso",
      "No puedo expulsar gases",
      "Ninguno",
    ],
    esAlarma: true,
  },
  {
    id: "diarrea-duracion",
    activadores: [
      "Diarrea continua",
      "Heces líquidas",
      "Deposiciones muy frecuentes",
    ],
    texto: "¿Cuánto tiempo llevas con diarrea?",
    opciones: [
      "Menos de 24 horas",
      "Entre uno y tres días",
      "Más de tres días",
      "Varias semanas o episodios repetidos",
    ],
  },
  {
    id: "diarrea-alarmas",
    activadores: [
      "Diarrea continua",
      "Heces líquidas",
      "Deposiciones muy frecuentes",
    ],
    texto: "¿Aparece alguno de estos signos con la diarrea?",
    opciones: [
      "Sangre roja en las heces",
      "Heces negras",
      "Fiebre",
      "Vómitos repetidos",
      "No puedo retener líquidos",
      "Orinar muy poca cantidad",
      "Ninguno",
    ],
    esAlarma: true,
  },
  {
    id: "diarrea-contexto",
    activadores: ["Diarrea continua", "Heces líquidas"],
    texto: "¿Ha ocurrido algo de esto recientemente?",
    opciones: [
      "Viaje reciente",
      "Antibióticos recientes",
      "Cambio importante de alimentación",
      "Otras personas cercanas tienen síntomas similares",
      "Ninguno",
    ],
  },
  {
    id: "reflujo-patron",
    activadores: ["Acidez", "Reflujo", "Regurgitación", "Quemazón retroesternal"],
    texto: "¿Cuándo aparece más el reflujo?",
    opciones: [
      "Después de comer",
      "Al acostarme",
      "Durante la noche",
      "Con comidas copiosas",
      "No encuentro un patrón",
    ],
  },
  {
    id: "reflujo-alarmas",
    activadores: ["Acidez", "Reflujo", "Regurgitación", "Quemazón retroesternal"],
    texto: "¿Aparece alguno de estos signos con el reflujo?",
    opciones: [
      "Dificultad para tragar",
      "Dolor al tragar",
      "Heces negras",
      "Pérdida de peso",
      "Dolor de pecho",
      "Ninguno",
    ],
    esAlarma: true,
  },
  {
    id: "dispepsia-patron",
    activadores: [
      "Dolor abdomen superior",
      "Ardor epigástrico",
      "Saciedad precoz",
      "Plenitud después de comer",
    ],
    texto: "¿Qué describe mejor la molestia digestiva?",
    opciones: [
      "Me lleno con muy poca comida",
      "Quedo lleno mucho tiempo después de comer",
      "Ardor o dolor en la parte alta del abdomen",
      "Náuseas o eructos frecuentes",
      "No sabría describirlo",
    ],
  },
  {
    id: "dispepsia-alarmas",
    activadores: [
      "Dolor abdomen superior",
      "Ardor epigástrico",
      "Saciedad precoz",
      "Plenitud después de comer",
    ],
    texto: "¿Hay algún signo de alarma digestiva?",
    opciones: [
      "Pérdida de peso",
      "Vómitos repetidos",
      "Heces negras",
      "Dificultad para tragar",
      "Dolor abdominal intenso",
      "Ninguno",
    ],
    esAlarma: true,
  },
  {
    id: "gases-contexto",
    activadores: ["Gases", "Hinchazón abdominal", "Distensión abdominal", "Eructos"],
    texto: "¿Con qué se relaciona la hinchazón o los gases?",
    opciones: [
      "Después de comer",
      "Con alimentos concretos",
      "Con estreñimiento",
      "Con diarrea",
      "Con estrés",
      "No encuentro un patrón",
    ],
  },
  {
    id: "sii-patron",
    activadores: ["Dolor abdominal", "Estreñimiento", "Diarrea continua", "Moco en las heces"],
    texto: "¿Cómo se relaciona el dolor con el intestino?",
    opciones: [
      "Cambia después de defecar",
      "Se acompaña de estreñimiento",
      "Se acompaña de diarrea",
      "Alterno estreñimiento y diarrea",
      "Los síntomas llevan meses o se repiten",
    ],
  },
  {
    id: "sii-alarmas",
    activadores: ["Dolor abdominal", "Estreñimiento", "Diarrea continua", "Moco en las heces"],
    texto: "¿Aparece alguna señal que necesite estudio?",
    opciones: [
      "Sangre roja en las heces",
      "Pérdida de peso",
      "Fiebre",
      "Heces negras",
      "Anemia conocida",
      "Ninguno",
    ],
    esAlarma: true,
  },
  {
    id: "cefalea-patron",
    activadores: ["Dolor de cabeza", "Migraña"],
    texto: "¿Cómo describirías el dolor de cabeza?",
    opciones: [
      "Dolor opresivo en la cabeza",
      "Dolor pulsátil",
      "Dolor en un lado de la cabeza",
      "Dolor en ambos lados de la cabeza",
      "No sabría describirlo",
    ],
  },
  {
    id: "cefalea-acompanantes",
    activadores: ["Dolor de cabeza", "Migraña"],
    texto: "¿Qué acompaña al dolor de cabeza?",
    opciones: [
      "Sensibilidad intensa a la luz",
      "Sensibilidad intensa al sonido",
      "Náuseas",
      "Aura visual",
      "Dolor de cuello",
      "Ninguno",
    ],
  },
  {
    id: "cefalea-alarmas",
    activadores: ["Dolor de cabeza", "Migraña"],
    texto: "¿Ha ocurrido alguna de estas señales?",
    opciones: [
      "Dolor de cabeza súbito e intenso",
      "Pérdida de fuerza",
      "Confusión",
      "Dificultad para hablar",
      "Visión doble nueva",
      "Desmayo",
      "Fiebre con rigidez de cuello",
      "Ninguno",
    ],
    esAlarma: true,
  },
  {
    id: "vertigo-patron",
    activadores: ["Mareo", "Vértigo"],
    texto: "¿Cómo describirías el mareo?",
    opciones: [
      "Todo gira",
      "Vértigo al mover la cabeza",
      "Sensación de desmayo",
      "Inestabilidad al caminar",
      "Aparece al levantarme",
      "No sabría describirlo",
    ],
  },
  {
    id: "vertigo-alarmas",
    activadores: ["Mareo", "Vértigo"],
    texto: "¿Aparece alguna señal neurológica o auditiva?",
    opciones: [
      "Pérdida de fuerza",
      "Confusión",
      "Dificultad para hablar",
      "Visión doble nueva",
      "Pérdida brusca de audición",
      "Ninguno",
    ],
    esAlarma: true,
  },
  {
    id: "lumbalgia-radiacion",
    activadores: ["Dolor lumbar", "Dolor de espalda"],
    texto: "¿El dolor se queda en la espalda o baja hacia la pierna?",
    opciones: [
      "Dolor que baja por la pierna",
      "Dolor en glúteo",
      "Hormigueo en una pierna",
      "Se queda en la zona lumbar",
      "No sabría describirlo",
    ],
  },
  {
    id: "lumbalgia-alarmas",
    activadores: ["Dolor lumbar", "Dolor de espalda", "Dolor que baja por la pierna"],
    texto: "¿Aparece alguna de estas señales con el dolor de espalda?",
    opciones: [
      "Pérdida de control de orina o heces",
      "Adormecimiento en zona genital o perineal",
      "Pérdida de fuerza en ambas piernas",
      "Debilidad progresiva de una pierna",
      "Fiebre",
      "Pérdida de peso",
      "Ninguno",
    ],
    esAlarma: true,
  },
  {
    id: "pierna-vascular",
    activadores: ["Dolor que baja por la pierna", "Hinchazón de piernas", "Hinchazón de una sola pierna"],
    texto: "¿La pierna tiene alguno de estos cambios?",
    opciones: [
      "Hinchazón de una sola pierna",
      "Pierna roja y caliente",
      "Falta de aire",
      "Dolor de pecho",
      "Ninguno",
    ],
    esAlarma: true,
  },
  {
    id: "orina-oscura",
    activadores: ["Orina oscura"],
    texto: "¿Qué otros cambios has notado?",
    opciones: [
      "Bebo poca agua",
      "Piel u ojos amarillos",
      "Dolor en la parte derecha del abdomen",
      "Fiebre",
      "Orina con olor fuerte",
      "Ninguno",
    ],
  },
  {
    id: "dolor-orinar",
    activadores: ["Dolor al orinar"],
    texto: "¿Tienes alguno de estos síntomas urinarios?",
    opciones: [
      "Necesidad urgente de orinar",
      "Orino muchas veces",
      "Fiebre",
      "Dolor lumbar",
      "Sangre en la orina",
      "Ninguno",
    ],
  },
];