import type { Condicion } from "./condiciones";

const oculto = { titulo: "No mostrado", marco: "Módulo no utilizado en la interfaz actual.", intervenciones: [], nivelEvidencia: "tradicional" as const };

export const condicionesCardiometabolicas: Condicion[] = [
  {
    id: "hipertension-compatible", nombre: "Hipertensión arterial compatible", descripcion: "La hipertensión suele no producir síntomas. Una medición elevada repetida requiere confirmación correcta; cefalea, mareo o palpitaciones no permiten diagnosticarla por sí solos.",
    sintomas: [{nombre:"Presión arterial elevada medida",peso:5},{nombre:"Dolor de cabeza",peso:1},{nombre:"Mareo",peso:1},{nombre:"Palpitaciones",peso:1}],
    sintomasAlarma: [{nombre:"Dolor de pecho",gravedad:"urgente"},{nombre:"Falta de aire intensa",gravedad:"urgente"},{nombre:"Confusión",gravedad:"urgente"},{nombre:"Dificultad para hablar",gravedad:"urgente"},{nombre:"Pérdida de fuerza",gravedad:"urgente"}],
    sintomasQueContradicen: [], preguntas: [{texto:"¿Has medido la presión varias veces en reposo y con un manguito adecuado?",importancia:3},{texto:"¿Tomas medicación o suplementos que puedan elevar o bajar la presión?",importancia:2}],
    posiblesCausas:["Hipertensión primaria","Enfermedad renal o endocrina","Medicamentos y otras causas secundarias"], factoresRiesgo:["Edad","Antecedentes familiares","Exceso de peso","Alta ingesta de sodio","Sedentarismo","Alcohol"],
    nutricion:["Patrón tipo DASH o mediterráneo","Reducir sodio y ultraprocesados","Priorizar frutas, verduras, legumbres, frutos secos sin sal y alimentos poco procesados"],
    fitoterapia:["No sustituir antihipertensivos por plantas","Revisar regaliz, estimulantes y suplementos por posibles efectos sobre la presión"], recomendaciones:["Confirmar con mediciones repetidas o monitorización según indicación","Controlar otros factores cardiovasculares"], nivelEvidencia:"alta",
    contraindicaciones:["No suspender medicación antihipertensiva por una lectura normal aislada"], interacciones:["Regaliz puede elevar la presión y alterar potasio; varios suplementos pueden potenciar antihipertensivos"], pruebasMedicasHabituales:["Medición estandarizada de presión","MAPA/AMPA según caso","Función renal, electrolitos, glucosa y lípidos","ECG según contexto"], especialistaRecomendado:["Atención Primaria","Cardiología o Nefrología según caso"], cuandoAcudirMedico:["Cifras muy elevadas acompañadas de dolor torácico, falta de aire o síntomas neurológicos","Elevación repetida de presión"], bibliografia:["Guías europeas de hipertensión arterial"],
    enfoques:{convencional:{titulo:"Medicina convencional",marco:"Confirma la hipertensión, cuantifica el riesgo cardiovascular y trata según cifras y riesgo global.",intervenciones:["Medición correcta","Cambios de estilo de vida","Fármacos cuando están indicados"],nivelEvidencia:"alta"},nutricion:{titulo:"Nutrición",marco:"DASH, patrón mediterráneo y reducción de sodio ayudan al control de la presión.",intervenciones:["Verduras y frutas","Legumbres y cereales integrales","Menos sodio y ultraprocesados"],nivelEvidencia:"alta"},natural:{titulo:"Fitoterapia y suplementación",marco:"Puede haber efectos modestos con algunos productos, pero no sustituyen el tratamiento indicado.",intervenciones:["Revisar seguridad e interacciones antes de suplementar"],nivelEvidencia:"limitada"},medicinaChina:oculto,estiloVida:{titulo:"Estilo de vida",marco:"Peso, ejercicio, sueño, alcohol y tabaco influyen en el riesgo cardiovascular.",intervenciones:["Actividad física regular","Peso saludable","Limitar alcohol","No fumar"],nivelEvidencia:"alta"}}
  },
  {
    id:"dislipemia-compatible", nombre:"Colesterol o triglicéridos elevados", descripcion:"Las alteraciones de colesterol y triglicéridos generalmente no dan síntomas y se detectan mediante analítica. Su importancia depende del perfil completo y del riesgo cardiovascular global.",
    sintomas:[{nombre:"Colesterol elevado en analítica",peso:5},{nombre:"Triglicéridos elevados en analítica",peso:5}], sintomasAlarma:[], sintomasQueContradicen:[], preguntas:[{texto:"¿Dispones de colesterol LDL, HDL y triglicéridos recientes?",importancia:3},{texto:"¿Existe diabetes, hipertensión, tabaquismo o enfermedad cardiovascular?",importancia:3}],
    posiblesCausas:["Predisposición genética","Patrón alimentario y exceso de peso","Diabetes o hipotiroidismo","Alcohol y determinados medicamentos"], factoresRiesgo:["Antecedentes familiares","Diabetes","Hipertensión","Tabaquismo","Obesidad"], nutricion:["Patrón mediterráneo","Sustituir grasas saturadas por grasas insaturadas","Aumentar fibra soluble de avena, cebada, legumbres y frutas","Reducir azúcares y alcohol si predominan triglicéridos altos"], fitoterapia:["Psyllium puede ayudar modestamente a reducir LDL","Esteroles vegetales pueden reducir LDL en determinadas personas","No usar arroz de levadura roja sin supervisión por efectos similares a estatinas y variabilidad del producto"], recomendaciones:["Valorar riesgo cardiovascular global","Repetir analítica según indicación"], nivelEvidencia:"alta", contraindicaciones:["No sustituir estatinas u otros fármacos indicados por suplementos"], interacciones:["Arroz de levadura roja puede compartir riesgos e interacciones de las estatinas"], pruebasMedicasHabituales:["Perfil lipídico","Glucosa/HbA1c","TSH y función hepática según contexto"], especialistaRecomendado:["Atención Primaria","Endocrinología/Cardiología en casos seleccionados"], cuandoAcudirMedico:["Triglicéridos muy elevados requieren valoración por riesgo de pancreatitis","Antecedentes de evento cardiovascular requieren control médico"], bibliografia:["Guías europeas de prevención cardiovascular y dislipemias"],
    enfoques:{convencional:{titulo:"Medicina convencional",marco:"El tratamiento depende del LDL, triglicéridos y riesgo cardiovascular total.",intervenciones:["Estratificar riesgo","Cambios de estilo de vida","Fármacos cuando están indicados"],nivelEvidencia:"alta"},nutricion:{titulo:"Nutrición",marco:"La calidad de grasas y la fibra soluble pueden mejorar el perfil lipídico.",intervenciones:["Patrón mediterráneo","Fibra soluble","Sustituir grasas saturadas por insaturadas"],nivelEvidencia:"alta"},natural:{titulo:"Fitoterapia y suplementación",marco:"Algunas fibras y esteroles tienen efecto modesto; otros suplementos requieren especial cautela.",intervenciones:["Psyllium","Esteroles vegetales cuando proceda"],nivelEvidencia:"moderada"},medicinaChina:oculto,estiloVida:{titulo:"Estilo de vida",marco:"Actividad física, peso y tabaco modifican el riesgo más allá de una cifra aislada de colesterol.",intervenciones:["Ejercicio regular","Peso saludable","No fumar"],nivelEvidencia:"alta"}}
  },
  {
    id:"higado-graso-metabolico", nombre:"Hígado graso metabólico compatible", descripcion:"La esteatosis hepática asociada a alteraciones metabólicas suele ser silenciosa y se identifica por analítica o imagen. La prioridad es valorar fibrosis y factores cardiometabólicos.",
    sintomas:[{nombre:"Hígado graso conocido",peso:5},{nombre:"Enzimas hepáticas elevadas",peso:3},{nombre:"Cansancio",peso:1},{nombre:"Aumento de peso",peso:1}], sintomasAlarma:[{nombre:"Color amarillo en la piel",gravedad:"alta"},{nombre:"Confusión",gravedad:"urgente"}], sintomasQueContradicen:[], preguntas:[{texto:"¿El hígado graso se ha visto en ecografía o analítica?",importancia:3},{texto:"¿Existe diabetes, exceso de peso, triglicéridos altos o consumo relevante de alcohol?",importancia:3}], posiblesCausas:["Resistencia a la insulina y exceso de adiposidad","Diabetes tipo 2","Dislipemia","Otras enfermedades hepáticas que deben excluirse"], factoresRiesgo:["Obesidad abdominal","Diabetes tipo 2","Triglicéridos elevados","Sedentarismo"], nutricion:["Patrón mediterráneo","Reducir bebidas azucaradas y exceso de ultraprocesados","Déficit energético moderado si existe exceso de peso","Evitar o limitar alcohol según valoración clínica"], fitoterapia:["No hay una planta que sustituya la pérdida de peso y el control metabólico","Evitar mezclas herbales de composición incierta por posible toxicidad hepática"], recomendaciones:["Valorar fibrosis y causas alternativas","Controlar peso, glucosa, lípidos y presión arterial"], nivelEvidencia:"alta", contraindicaciones:["No asumir que toda elevación de transaminasas es hígado graso"], interacciones:["Algunos extractos y suplementos pueden causar lesión hepática"], pruebasMedicasHabituales:["Transaminasas y perfil hepático","Ecografía u otras técnicas de imagen","Índices no invasivos de fibrosis","Glucosa y perfil lipídico"], especialistaRecomendado:["Atención Primaria","Digestología/Hepatología según riesgo de fibrosis"], cuandoAcudirMedico:["Ictericia","Confusión","Alteraciones persistentes o riesgo elevado de fibrosis"], bibliografia:["Guías europeas sobre enfermedad hepática esteatósica metabólica"],
    enfoques:{convencional:{titulo:"Medicina convencional",marco:"Evalúa fibrosis, descarta otras causas y trata los factores metabólicos asociados.",intervenciones:["Evaluación hepática","Control de diabetes y lípidos","Seguimiento según fibrosis"],nivelEvidencia:"alta"},nutricion:{titulo:"Nutrición",marco:"La pérdida de peso cuando existe exceso y el patrón mediterráneo son pilares del manejo.",intervenciones:["Patrón mediterráneo","Reducir azúcares líquidos","Déficit energético individualizado"],nivelEvidencia:"alta"},natural:{titulo:"Fitoterapia y suplementación",marco:"No existe un sustituto herbal establecido para el tratamiento metabólico y algunos productos pueden dañar el hígado.",intervenciones:["Evitar productos hepatotóxicos o de composición incierta"],nivelEvidencia:"limitada"},medicinaChina:oculto,estiloVida:{titulo:"Estilo de vida",marco:"Ejercicio y reducción de peso mejoran la salud metabólica y hepática.",intervenciones:["Ejercicio aeróbico y de fuerza","Reducir sedentarismo","Pérdida de peso gradual si procede"],nivelEvidencia:"alta"}}
  },
  {
    id:"sindrome-metabolico-compatible", nombre:"Síndrome metabólico compatible", descripcion:"La combinación de obesidad abdominal, presión elevada, glucosa alterada y triglicéridos/HDL desfavorables aumenta el riesgo de diabetes y enfermedad cardiovascular. Requiere mediciones objetivas.",
    sintomas:[{nombre:"Obesidad abdominal",peso:3},{nombre:"Presión arterial elevada medida",peso:3},{nombre:"Glucosa elevada en analítica",peso:3},{nombre:"Triglicéridos elevados en analítica",peso:3}], sintomasAlarma:[], sintomasQueContradicen:[], preguntas:[{texto:"¿Dispones de perímetro de cintura, presión, glucosa y perfil lipídico?",importancia:3}], posiblesCausas:["Resistencia a la insulina","Exceso de adiposidad visceral","Sedentarismo y predisposición genética"], factoresRiesgo:["Exceso de peso abdominal","Sedentarismo","Antecedentes familiares","Edad"], nutricion:["Patrón mediterráneo rico en vegetales, legumbres, frutos secos y aceite de oliva","Reducir bebidas azucaradas, harinas refinadas y ultraprocesados","Ajustar energía para perder peso cuando proceda"], fitoterapia:["No existe un suplemento único que trate el síndrome metabólico","La fibra soluble puede apoyar glucosa y lípidos dentro de un plan dietético"], recomendaciones:["Medir y tratar cada factor de riesgo","Seguimiento de glucosa, presión y lípidos"], nivelEvidencia:"alta", contraindicaciones:["Evitar dietas extremas o suplementos como sustitutos del tratamiento de factores de riesgo"], interacciones:["Suplementos hipoglucemiantes o hipotensores pueden potenciar medicación"], pruebasMedicasHabituales:["Perímetro de cintura","Presión arterial","Glucosa/HbA1c","Perfil lipídico","Función hepática y renal según contexto"], especialistaRecomendado:["Atención Primaria","Endocrinología según complejidad"], cuandoAcudirMedico:["Valores marcadamente alterados","Síntomas cardiovasculares o hiperglucemia sintomática"], bibliografia:["Guías de prevención cardiovascular y diabetes"],
    enfoques:{convencional:{titulo:"Medicina convencional",marco:"Trata el riesgo global y cada componente alterado.",intervenciones:["Control de presión","Control de glucosa","Control de lípidos"],nivelEvidencia:"alta"},nutricion:{titulo:"Nutrición",marco:"El patrón alimentario y la pérdida de peso cuando procede son intervenciones centrales.",intervenciones:["Patrón mediterráneo","Fibra","Menos ultraprocesados y bebidas azucaradas"],nivelEvidencia:"alta"},natural:{titulo:"Fitoterapia y suplementación",marco:"Puede complementar objetivos concretos, pero no reemplaza el abordaje multifactorial.",intervenciones:["Fibra soluble cuando sea apropiada","Revisar interacciones"],nivelEvidencia:"moderada"},medicinaChina:oculto,estiloVida:{titulo:"Estilo de vida",marco:"Ejercicio, peso, sueño y abandono del tabaco son fundamentales.",intervenciones:["Ejercicio aeróbico y fuerza","Dormir adecuadamente","No fumar"],nivelEvidencia:"alta"}}
  }
];