import type { Condicion } from "./condiciones";

const medicinaChinaOculta = {
  titulo: "No mostrado",
  marco: "Módulo no utilizado en la interfaz actual.",
  intervenciones: [],
  nivelEvidencia: "tradicional" as const,
};

export const condicionesORLVisual: Condicion[] = [
  {
    id: "conjuntivitis-compatible",
    nombre: "Conjuntivitis compatible",
    descripcion: "Ojo rojo, picor, lagrimeo o secreción pueden corresponder a conjuntivitis alérgica, viral o bacteriana. El dolor intenso o la pérdida de visión no son típicos y requieren valoración.",
    sintomas: [{ nombre: "Ojo rojo", peso: 3 },{ nombre: "Picor de ojos", peso: 2 },{ nombre: "Lagrimeo", peso: 2 },{ nombre: "Secreción ocular", peso: 2 }],
    sintomasAlarma: [{ nombre: "Dolor ocular", gravedad: "alta" },{ nombre: "Pérdida brusca de visión", gravedad: "urgente" },{ nombre: "Sensibilidad intensa a la luz", gravedad: "alta" }],
    sintomasQueContradicen: [{ nombre: "Pérdida brusca de visión", peso: 3 }],
    preguntas: [{ texto: "¿Predomina el picor, la secreción o ambos?", importancia: 2 },{ texto: "¿Hay dolor ocular o pérdida de visión?", importancia: 3 }],
    posiblesCausas: ["Conjuntivitis alérgica", "Conjuntivitis viral", "Conjuntivitis bacteriana", "Irritación ocular"],
    factoresRiesgo: ["Alergia", "Contacto con personas infectadas", "Lentes de contacto"],
    nutricion: ["No existe una intervención nutricional específica para la conjuntivitis aguda"],
    fitoterapia: ["Evitar colirios herbales caseros o sustancias no estériles en el ojo"],
    recomendaciones: ["Higiene de manos", "No compartir toallas", "Evitar frotar los ojos"],
    nivelEvidencia: "alta",
    contraindicaciones: ["No aplicar infusiones o preparados no estériles directamente en el ojo"],
    interacciones: ["Revisar colirios si se usan otros tratamientos oculares"],
    pruebasMedicasHabituales: ["Exploración ocular"],
    especialistaRecomendado: ["Atención Primaria", "Oftalmología si hay dolor, fotofobia o alteración visual"],
    cuandoAcudirMedico: ["Dolor ocular", "Pérdida de visión", "Fotofobia intensa", "Uso de lentes de contacto con ojo rojo doloroso"],
    bibliografia: ["Guías clínicas de ojo rojo y conjuntivitis"],
    enfoques: {
      convencional: { titulo: "Medicina convencional", marco: "Distingue causas benignas de cuadros que requieren atención oftalmológica.", intervenciones: ["Exploración ocular", "Tratamiento según causa", "Derivación si hay signos de alarma"], nivelEvidencia: "alta" },
      nutricion: { titulo: "Nutrición", marco: "No es el tratamiento principal del cuadro agudo.", intervenciones: ["Mantener alimentación e hidratación normales"], nivelEvidencia: "moderada" },
      natural: { titulo: "Fitoterapia y suplementación", marco: "No deben aplicarse remedios no estériles sobre el ojo.", intervenciones: ["Evitar preparados caseros intraoculares"], nivelEvidencia: "alta" },
      medicinaChina: medicinaChinaOculta,
      estiloVida: { titulo: "Estilo de vida", marco: "La higiene reduce irritación y transmisión en cuadros infecciosos.", intervenciones: ["Lavado de manos", "No frotar ojos", "Descanso de lentes de contacto si están irritando"], nivelEvidencia: "alta" }
    }
  },
  {
    id: "desprendimiento-retina-compatible",
    nombre: "Alarma visual compatible con desprendimiento de retina",
    descripcion: "Destellos de luz, aparición brusca de muchas moscas volantes o pérdida de una zona del campo visual pueden ser signos de un problema retiniano y requieren valoración urgente.",
    sintomas: [{ nombre: "Destellos de luz", peso: 3 },{ nombre: "Moscas volantes nuevas", peso: 3 },{ nombre: "Pérdida brusca de visión", peso: 4 }],
    sintomasAlarma: [{ nombre: "Pérdida brusca de visión", gravedad: "urgente" },{ nombre: "Destellos de luz", gravedad: "alta" },{ nombre: "Moscas volantes nuevas", gravedad: "alta" }],
    sintomasQueContradicen: [],
    preguntas: [{ texto: "¿Los destellos o las moscas volantes han aparecido de repente?", importancia: 3 }],
    posiblesCausas: ["Desgarro retiniano", "Desprendimiento de retina", "Desprendimiento vítreo posterior", "Otras causas oculares"],
    factoresRiesgo: ["Miopía alta", "Cirugía ocular previa", "Traumatismo ocular", "Edad"],
    nutricion: ["No hay intervención nutricional útil para resolver un desprendimiento agudo"],
    fitoterapia: ["No retrasar atención intentando tratamiento natural"],
    recomendaciones: ["Valoración oftalmológica urgente"],
    nivelEvidencia: "alta",
    contraindicaciones: ["No esperar a que desaparezcan espontáneamente los síntomas si son de inicio brusco"],
    interacciones: [],
    pruebasMedicasHabituales: ["Fondo de ojo dilatado", "Ecografía ocular en situaciones seleccionadas"],
    especialistaRecomendado: ["Urgencias oftalmológicas"],
    cuandoAcudirMedico: ["De inmediato ante pérdida brusca de visión, destellos nuevos o aumento súbito de moscas volantes"],
    bibliografia: ["Guías oftalmológicas de desprendimiento de retina"],
    enfoques: {
      convencional: { titulo: "Medicina convencional", marco: "Es una situación en la que el tiempo puede ser importante para preservar visión.", intervenciones: ["Valoración oftalmológica urgente", "Tratamiento láser o quirúrgico según causa"], nivelEvidencia: "alta" },
      nutricion: { titulo: "Nutrición", marco: "No corrige una lesión retiniana aguda.", intervenciones: [], nivelEvidencia: "alta" },
      natural: { titulo: "Fitoterapia y suplementación", marco: "No existe tratamiento natural sustitutivo para este cuadro.", intervenciones: [], nivelEvidencia: "alta" },
      medicinaChina: medicinaChinaOculta,
      estiloVida: { titulo: "Estilo de vida", marco: "La prioridad es acudir a valoración, no modificar hábitos en casa.", intervenciones: ["Evitar demoras"], nivelEvidencia: "alta" }
    }
  },
  {
    id: "otitis-compatible",
    nombre: "Otitis / inflamación del oído compatible",
    descripcion: "Dolor de oído, sensación de taponamiento, secreción o fiebre pueden aparecer en otitis externa o media. La exploración del oído permite diferenciarlas.",
    sintomas: [{ nombre: "Dolor de oído", peso: 3 },{ nombre: "Oído taponado", peso: 2 },{ nombre: "Secreción por el oído", peso: 2 },{ nombre: "Pérdida de audición", peso: 1 },{ nombre: "Fiebre", peso: 1 }],
    sintomasAlarma: [{ nombre: "Pérdida brusca de audición", gravedad: "urgente" },{ nombre: "Vértigo", gravedad: "alta" }],
    sintomasQueContradicen: [],
    preguntas: [{ texto: "¿Hay secreción, fiebre o dolor al tocar la oreja?", importancia: 2 },{ texto: "¿La audición se ha perdido de forma brusca?", importancia: 3 }],
    posiblesCausas: ["Otitis externa", "Otitis media", "Tapón de cerumen", "Otras causas"],
    factoresRiesgo: ["Baño frecuente", "Infección respiratoria reciente", "Manipulación del oído"],
    nutricion: ["No existe una pauta nutricional específica para resolver una otitis aguda"],
    fitoterapia: ["No introducir aceites o preparados en el oído si existe secreción o posible perforación"],
    recomendaciones: ["Mantener el oído seco hasta valoración si hay secreción", "Evitar bastoncillos"],
    nivelEvidencia: "alta",
    contraindicaciones: ["No introducir líquidos en el oído si se sospecha perforación"],
    interacciones: ["Revisar tratamientos óticos previos"],
    pruebasMedicasHabituales: ["Otoscopia", "Audiometría si persiste pérdida auditiva"],
    especialistaRecomendado: ["Atención Primaria", "Otorrinolaringología"],
    cuandoAcudirMedico: ["Dolor intenso", "Fiebre persistente", "Secreción", "Pérdida brusca de audición"],
    bibliografia: ["Guías clínicas de otitis"],
    enfoques: {
      convencional: { titulo: "Medicina convencional", marco: "La otoscopia diferencia las causas más frecuentes y guía el tratamiento.", intervenciones: ["Analgesia", "Tratamiento tópico u oral según diagnóstico", "Derivación si procede"], nivelEvidencia: "alta" },
      nutricion: { titulo: "Nutrición", marco: "No es el tratamiento principal.", intervenciones: ["Hidratación y alimentación habitual"], nivelEvidencia: "moderada" },
      natural: { titulo: "Fitoterapia y suplementación", marco: "No deben introducirse remedios caseros en un oído con posible perforación.", intervenciones: ["Evitar gotas no indicadas"], nivelEvidencia: "alta" },
      medicinaChina: medicinaChinaOculta,
      estiloVida: { titulo: "Estilo de vida", marco: "Evitar humedad y manipulación puede ayudar en algunos cuadros.", intervenciones: ["No usar bastoncillos", "Mantener oído seco si está indicado"], nivelEvidencia: "moderada" }
    }
  },
  {
    id: "rinitis-alergica-compatible",
    nombre: "Rinitis alérgica compatible",
    descripcion: "Estornudos, picor nasal, congestión, mucosidad acuosa y a veces picor ocular pueden corresponder a rinitis alérgica.",
    sintomas: [{ nombre: "Estornudos", peso: 3 },{ nombre: "Picor nasal", peso: 3 },{ nombre: "Congestión nasal", peso: 2 },{ nombre: "Mucosidad", peso: 2 },{ nombre: "Picor de ojos", peso: 1 },{ nombre: "Lagrimeo", peso: 1 }],
    sintomasAlarma: [{ nombre: "Falta de aire", gravedad: "alta" }],
    sintomasQueContradicen: [{ nombre: "Fiebre", peso: 1 }],
    preguntas: [{ texto: "¿Los síntomas aparecen con polvo, polen, animales o en determinadas épocas?", importancia: 2 }],
    posiblesCausas: ["Polen", "Ácaros", "Epitelios de animales", "Otros alérgenos"],
    factoresRiesgo: ["Alergias previas", "Asma", "Antecedentes familiares"],
    nutricion: ["No existe una dieta curativa específica; evitar restricciones innecesarias"],
    fitoterapia: ["Revisar seguridad y evidencia de productos antialérgicos naturales antes de usarlos"],
    recomendaciones: ["Reducir exposición al alérgeno cuando sea posible", "Lavados nasales con solución salina"],
    nivelEvidencia: "alta",
    contraindicaciones: ["Evitar descongestionantes prolongados sin supervisión"],
    interacciones: ["Algunos antihistamínicos y productos sedantes pueden potenciar somnolencia"],
    pruebasMedicasHabituales: ["Historia clínica", "Pruebas de alergia en casos seleccionados"],
    especialistaRecomendado: ["Atención Primaria", "Alergología u Otorrinolaringología si es persistente"],
    cuandoAcudirMedico: ["Síntomas persistentes mal controlados", "Falta de aire o asma asociado"],
    bibliografia: ["Guías de rinitis alérgica"],
    enfoques: {
      convencional: { titulo: "Medicina convencional", marco: "Controla síntomas y exposición a alérgenos.", intervenciones: ["Antihistamínicos", "Corticoides nasales cuando están indicados", "Inmunoterapia en casos seleccionados"], nivelEvidencia: "alta" },
      nutricion: { titulo: "Nutrición", marco: "No requiere restricciones dietéticas salvo alergia alimentaria independiente.", intervenciones: ["Dieta equilibrada"], nivelEvidencia: "moderada" },
      natural: { titulo: "Fitoterapia y suplementación", marco: "La evidencia de productos naturales es variable y no sustituye tratamientos eficaces cuando son necesarios.", intervenciones: ["Lavados nasales con solución salina"], nivelEvidencia: "moderada" },
      medicinaChina: medicinaChinaOculta,
      estiloVida: { titulo: "Estilo de vida", marco: "Reducir exposición puede disminuir carga de síntomas.", intervenciones: ["Ventilar según niveles de polen", "Higiene ambiental", "Ducha tras exposición intensa a polen"], nivelEvidencia: "moderada" }
    }
  },
  {
    id: "sinusitis-compatible",
    nombre: "Rinosinusitis compatible",
    descripcion: "Congestión nasal, mucosidad y dolor o presión facial pueden corresponder a rinosinusitis, habitualmente viral en fases iniciales.",
    sintomas: [{ nombre: "Congestión nasal", peso: 2 },{ nombre: "Mucosidad", peso: 2 },{ nombre: "Dolor facial", peso: 3 },{ nombre: "Pérdida de olfato", peso: 2 },{ nombre: "Dolor de cabeza", peso: 1 }],
    sintomasAlarma: [{ nombre: "Confusión", gravedad: "urgente" },{ nombre: "Dolor ocular", gravedad: "alta" },{ nombre: "Pérdida brusca de visión", gravedad: "urgente" }],
    sintomasQueContradicen: [],
    preguntas: [{ texto: "¿Los síntomas llevan más de 10 días o empeoraron después de una mejoría inicial?", importancia: 2 }],
    posiblesCausas: ["Infección viral", "Rinosinusitis bacteriana en algunos casos", "Alergia", "Inflamación nasal crónica"],
    factoresRiesgo: ["Rinitis alérgica", "Pólipos nasales", "Infección respiratoria reciente"],
    nutricion: ["Mantener hidratación"],
    fitoterapia: ["No usar aceites esenciales dentro de la nariz", "Los lavados salinos pueden ayudar como medida de apoyo"],
    recomendaciones: ["Lavados nasales con solución salina", "Consultar si dura, empeora o aparecen signos de alarma"],
    nivelEvidencia: "alta",
    contraindicaciones: ["No retrasar atención si aparece hinchazón ocular, alteración visual o deterioro neurológico"],
    interacciones: ["Revisar descongestionantes si existe hipertensión u otras contraindicaciones"],
    pruebasMedicasHabituales: ["Valoración clínica", "Imagen solo en casos seleccionados o complicados"],
    especialistaRecomendado: ["Atención Primaria", "Otorrinolaringología si es recurrente o crónica"],
    cuandoAcudirMedico: ["Síntomas prolongados o intensos", "Empeoramiento tras mejoría", "Dolor o hinchazón ocular", "Alteración visual"],
    bibliografia: ["Guías de rinosinusitis aguda"],
    enfoques: {
      convencional: { titulo: "Medicina convencional", marco: "Diferencia cuadros virales autolimitados de casos con mayor probabilidad bacteriana o complicaciones.", intervenciones: ["Tratamiento sintomático", "Antibiótico solo cuando está indicado", "Derivación si hay complicación"], nivelEvidencia: "alta" },
      nutricion: { titulo: "Nutrición", marco: "La hidratación es una medida de apoyo.", intervenciones: ["Mantener líquidos suficientes"], nivelEvidencia: "moderada" },
      natural: { titulo: "Fitoterapia y suplementación", marco: "Los lavados salinos tienen mejor respaldo que muchos preparados herbales.", intervenciones: ["Lavado nasal salino"], nivelEvidencia: "moderada" },
      medicinaChina: medicinaChinaOculta,
      estiloVida: { titulo: "Estilo de vida", marco: "Descanso y evitar humo ayudan a reducir irritación.", intervenciones: ["Evitar tabaco y humo", "Descanso adecuado"], nivelEvidencia: "moderada" }
    }
  }
];