import type { Condicion } from "./condiciones";

export const condicionesDigestivasExtra: Condicion[] = [
  {
    id: "reflujo-erge",
    nombre: "Reflujo gastroesofágico / ERGE compatible",
    descripcion:
      "Cuadro compatible con reflujo cuando predominan acidez, regurgitación o quemazón retroesternal, especialmente tras comidas o al acostarse.",
    sintomas: [
      { nombre: "Acidez", peso: 3 },
      { nombre: "Reflujo", peso: 3 },
      { nombre: "Regurgitación", peso: 3 },
      { nombre: "Quemazón retroesternal", peso: 2 },
      { nombre: "Ronquera", peso: 1 },
      { nombre: "Tos seca", peso: 1 },
    ],
    sintomasAlarma: [
      { nombre: "Dificultad para tragar", gravedad: "alta" },
      { nombre: "Dolor al tragar", gravedad: "alta" },
      { nombre: "Heces negras", gravedad: "alta" },
      { nombre: "Pérdida de peso", gravedad: "alta" },
      { nombre: "Dolor de pecho", gravedad: "urgente" },
    ],
    sintomasQueContradicen: [
      { nombre: "Heces líquidas", peso: 1 },
      { nombre: "Diarrea continua", peso: 1 },
    ],
    preguntas: [
      { texto: "¿Empeora después de comer o al acostarte?", importancia: 2 },
      { texto: "¿Notas que sube contenido ácido o amargo?", importancia: 3 },
      { texto: "¿Tienes dificultad o dolor al tragar?", importancia: 3 },
    ],
    posiblesCausas: [
      "Relajación o incompetencia del esfínter esofágico inferior",
      "Comidas copiosas o determinados desencadenantes individuales",
      "Sobrepeso u obesidad",
      "Hernia de hiato u otros factores anatómicos",
    ],
    factoresRiesgo: ["Sobrepeso", "Tabaco", "Comidas copiosas", "Síntomas nocturnos"],
    nutricion: [
      "Identificar desencadenantes individuales en lugar de retirar alimentos indiscriminadamente",
      "Evitar comidas muy copiosas si empeoran los síntomas",
      "Separar la cena del momento de acostarse cuando el reflujo es nocturno",
    ],
    fitoterapia: [
      "No sustituir el estudio médico por plantas si hay disfagia, sangrado o pérdida de peso",
      "Evitar recomendar menta si claramente empeora el reflujo",
    ],
    recomendaciones: [
      "Revisar horario y tamaño de comidas",
      "Valorar pérdida de peso si existe exceso de peso",
      "Consultar si los síntomas son frecuentes, persistentes o requieren medicación repetida",
    ],
    nivelEvidencia: "alta",
    contraindicaciones: ["No tratar como simple acidez un dolor torácico de origen incierto"],
    interacciones: ["Revisar medicación que pueda agravar síntomas o interactuar con antiácidos"],
    pruebasMedicasHabituales: [
      "Historia clínica dirigida",
      "Endoscopia si existen signos de alarma o indicación clínica",
      "Pruebas de reflujo o motilidad en casos seleccionados",
    ],
    especialistaRecomendado: ["Médico de Atención Primaria", "Digestólogo"],
    cuandoAcudirMedico: [
      "Dificultad o dolor al tragar",
      "Sangrado digestivo o heces negras",
      "Pérdida de peso involuntaria",
      "Dolor de pecho, falta de aire o síntomas cardiovasculares",
    ],
    bibliografia: ["American College of Gastroenterology: Acid Reflux/GERD"],
    enfoques: {
      convencional: {
        titulo: "Medicina convencional",
        marco: "Diferencia síntomas típicos de reflujo de complicaciones y causas alternativas.",
        intervenciones: [
          "Medidas de estilo de vida individualizadas",
          "Tratamiento antisecretor cuando está indicado",
          "Endoscopia u otras pruebas en presencia de alarmas o mala respuesta",
        ],
        nivelEvidencia: "alta",
      },
      nutricion: {
        titulo: "Nutrición",
        marco: "Busca reducir desencadenantes personales sin imponer restricciones generales innecesarias.",
        intervenciones: [
          "Comidas menos copiosas si existe relación clara",
          "Evitar acostarse inmediatamente después de cenar",
          "Registrar alimentos que reproducen síntomas de forma consistente",
        ],
        nivelEvidencia: "moderada",
      },
      natural: {
        titulo: "Fitoterapia y medicina natural",
        marco: "Puede aportar medidas de apoyo, pero la evidencia de muchos productos es limitada.",
        intervenciones: [
          "Priorizar hábitos antes que preparados complejos",
          "Evitar productos que empeoren el reflujo individual",
          "Consultar antes de usar plantas si se toma medicación crónica",
        ],
        nivelEvidencia: "limitada",
        nota: "No debe retrasar la valoración de disfagia, sangrado o pérdida de peso.",
      },
      medicinaChina: {
        titulo: "Medicina tradicional china",
        marco: "Interpreta el cuadro mediante patrones propios como ascenso rebelde del Qi de Estómago, calor o estancamiento.",
        intervenciones: [
          "Valoración de patrón por profesional formado",
          "Acupuntura o fitoterapia china individualizadas dentro de su marco tradicional",
          "Revisión de interacciones de fórmulas herbales",
        ],
        nivelEvidencia: "tradicional",
        nota: "No equivale a un diagnóstico biomédico de ERGE.",
      },
      estiloVida: {
        titulo: "Estilo de vida",
        marco: "Valora peso, horarios, sueño, tabaco y posición corporal.",
        intervenciones: [
          "Evitar acostarse justo después de comer",
          "Reducir peso si existe exceso de peso y está indicado",
          "Evitar tabaco y revisar hábitos nocturnos",
        ],
        nivelEvidencia: "moderada",
      },
    },
  },
  {
    id: "dispepsia-funcional",
    nombre: "Dispepsia / digestión pesada compatible",
    descripcion:
      "Conjunto de síntomas de la parte alta del abdomen como molestia o ardor, plenitud tras comer, saciedad precoz, náuseas o eructos.",
    sintomas: [
      { nombre: "Dolor abdomen superior", peso: 3 },
      { nombre: "Ardor epigástrico", peso: 3 },
      { nombre: "Saciedad precoz", peso: 3 },
      { nombre: "Plenitud después de comer", peso: 3 },
      { nombre: "Náuseas", peso: 1 },
      { nombre: "Eructos", peso: 1 },
      { nombre: "Hinchazón abdominal", peso: 1 },
    ],
    sintomasAlarma: [
      { nombre: "Pérdida de peso", gravedad: "alta" },
      { nombre: "Heces negras", gravedad: "alta" },
      { nombre: "Vómitos repetidos", gravedad: "alta" },
      { nombre: "Dificultad para tragar", gravedad: "alta" },
      { nombre: "Dolor abdominal intenso", gravedad: "urgente" },
    ],
    sintomasQueContradicen: [{ nombre: "Diarrea continua", peso: 1 }],
    preguntas: [
      { texto: "¿Te llenas con poca cantidad de comida?", importancia: 3 },
      { texto: "¿La molestia está en la parte alta del abdomen?", importancia: 3 },
      { texto: "¿Hay pérdida de peso, vómitos frecuentes o heces negras?", importancia: 3 },
    ],
    posiblesCausas: [
      "Dispepsia funcional",
      "Gastritis o enfermedad ulcerosa",
      "Helicobacter pylori en determinados casos",
      "Efectos de medicamentos u otros trastornos digestivos",
    ],
    factoresRiesgo: ["Uso de AINE", "Tabaco", "Alcohol", "Síntomas persistentes"],
    nutricion: [
      "Comidas de tamaño tolerable",
      "Identificar alimentos que agraven síntomas de forma reproducible",
      "Evitar restricciones amplias sin una razón clara",
    ],
    fitoterapia: [
      "Algunas plantas digestivas tienen uso tradicional, pero la evidencia varía",
      "No usar preparados para ocultar síntomas de alarma",
    ],
    recomendaciones: ["Revisar medicación", "Consultar si persiste", "Valorar H. pylori según contexto clínico"],
    nivelEvidencia: "moderada",
    contraindicaciones: ["No asumir que toda dispepsia es funcional si existen signos de alarma"],
    interacciones: ["Revisar AINE, alcohol, suplementos y preparados herbales irritantes"],
    pruebasMedicasHabituales: [
      "Historia clínica y exploración",
      "Prueba de Helicobacter pylori en casos seleccionados",
      "Endoscopia o pruebas adicionales según edad, alarmas y evolución",
    ],
    especialistaRecomendado: ["Médico de Atención Primaria", "Digestólogo"],
    cuandoAcudirMedico: [
      "Pérdida de peso involuntaria",
      "Vómitos persistentes o con sangre",
      "Heces negras",
      "Dificultad para tragar",
      "Dolor intenso y constante",
    ],
    bibliografia: ["NIDDK: Indigestion (Dyspepsia)"],
    enfoques: {
      convencional: {
        titulo: "Medicina convencional",
        marco: "Busca diferenciar dispepsia funcional de úlcera, gastritis, H. pylori y otras causas.",
        intervenciones: ["Historia y exploración", "H. pylori o tratamiento antisecretor según el caso", "Endoscopia si procede"],
        nivelEvidencia: "alta",
      },
      nutricion: {
        titulo: "Nutrición",
        marco: "Adapta tamaño y composición de comidas según tolerancia.",
        intervenciones: ["Comidas más pequeñas si hay plenitud", "Evitar desencadenantes comprobados", "Mantener dieta suficiente y variada"],
        nivelEvidencia: "moderada",
      },
      natural: {
        titulo: "Fitoterapia y medicina natural",
        marco: "Puede valorar plantas digestivas como apoyo, con evidencia desigual.",
        intervenciones: ["Usar preparados simples y trazables", "Revisar interacciones", "Suspender y consultar si empeora o aparecen alarmas"],
        nivelEvidencia: "limitada",
      },
      medicinaChina: {
        titulo: "Medicina tradicional china",
        marco: "Puede interpretarse mediante patrones de Estómago y Bazo dentro de su sistema tradicional.",
        intervenciones: ["Valoración individual de patrón", "Acupuntura según profesional", "Fitoterapia china con control de interacciones"],
        nivelEvidencia: "tradicional",
        nota: "Marco tradicional separado del diagnóstico biomédico.",
      },
      estiloVida: {
        titulo: "Estilo de vida",
        marco: "Considera velocidad al comer, estrés, alcohol, tabaco y horarios.",
        intervenciones: ["Comer más despacio", "Revisar alcohol y tabaco", "Reducir factores de estrés si agravan los síntomas"],
        nivelEvidencia: "moderada",
      },
    },
  },
  {
    id: "hinchazon-gases",
    nombre: "Hinchazón y gases funcionales compatibles",
    descripcion:
      "Síntomas de distensión, plenitud, eructos o flatulencia que pueden ser funcionales o acompañar otros trastornos digestivos.",
    sintomas: [
      { nombre: "Gases", peso: 3 },
      { nombre: "Hinchazón abdominal", peso: 3 },
      { nombre: "Eructos", peso: 2 },
      { nombre: "Distensión abdominal", peso: 3 },
      { nombre: "Dolor abdominal", peso: 1 },
    ],
    sintomasAlarma: [
      { nombre: "Pérdida de peso", gravedad: "alta" },
      { nombre: "Sangre roja en las heces", gravedad: "alta" },
      { nombre: "Heces negras", gravedad: "alta" },
      { nombre: "Dolor abdominal intenso", gravedad: "urgente" },
    ],
    sintomasQueContradicen: [],
    preguntas: [
      { texto: "¿Se relaciona con alimentos concretos?", importancia: 2 },
      { texto: "¿También hay estreñimiento o diarrea?", importancia: 3 },
      { texto: "¿Ha cambiado bruscamente o hay pérdida de peso?", importancia: 3 },
    ],
    posiblesCausas: [
      "Aerofagia o hábitos al comer",
      "Fermentación de carbohidratos",
      "Estreñimiento, SII u otros trastornos funcionales",
      "Intolerancias o problemas de digestión de determinados carbohidratos",
    ],
    factoresRiesgo: ["Comer deprisa", "Bebidas gaseosas", "Estreñimiento", "Cambios dietéticos"],
    nutricion: ["Registrar relación con alimentos", "Evitar eliminaciones extensas sin evaluación", "Revisar fibra y tolerancia individual"],
    fitoterapia: ["La evidencia de carminativos es variable", "Evitar mezclas si hay síntomas no aclarados"],
    recomendaciones: ["Comer despacio", "Revisar estreñimiento o diarrea asociados", "Consultar ante cambio brusco o alarmas"],
    nivelEvidencia: "moderada",
    contraindicaciones: ["No atribuir a simples gases una distensión persistente con pérdida de peso o sangrado"],
    interacciones: ["Revisar suplementos que aumenten fermentación o alteren tránsito"],
    pruebasMedicasHabituales: ["Historia clínica y dieta", "Exploración", "Pruebas dirigidas si se sospecha una causa concreta"],
    especialistaRecomendado: ["Médico de Atención Primaria", "Digestólogo", "Dietista-nutricionista"],
    cuandoAcudirMedico: ["Pérdida de peso", "Sangrado", "Dolor importante", "Cambio brusco y persistente"],
    bibliografia: ["NIDDK: Gas in the Digestive Tract"],
    enfoques: {
      convencional: {
        titulo: "Medicina convencional",
        marco: "Busca si los gases son aislados o secundarios a otra condición.",
        intervenciones: ["Historia y exploración", "Tratar estreñimiento u otra causa si existe", "Pruebas dirigidas solo cuando están justificadas"],
        nivelEvidencia: "moderada",
      },
      nutricion: {
        titulo: "Nutrición",
        marco: "Relaciona síntomas con fermentación, fibra y tolerancias individuales.",
        intervenciones: ["Diario breve de alimentos y síntomas", "Ajustar fibra gradualmente", "Valorar estrategia FODMAP solo de forma estructurada si está indicada"],
        nivelEvidencia: "moderada",
      },
      natural: {
        titulo: "Fitoterapia y medicina natural",
        marco: "Los carminativos tienen tradición de uso, pero el beneficio depende del producto y del cuadro.",
        intervenciones: ["No sustituir el estudio de síntomas persistentes", "Priorizar medidas dietéticas y hábitos", "Comprobar tolerancia e interacciones"],
        nivelEvidencia: "limitada",
      },
      medicinaChina: {
        titulo: "Medicina tradicional china",
        marco: "Puede relacionar la distensión con patrones de estancamiento o debilidad digestiva dentro de su marco.",
        intervenciones: ["Valoración de patrón", "Acupuntura individualizada", "Fitoterapia china supervisada"],
        nivelEvidencia: "tradicional",
        nota: "No sustituye el estudio de causas orgánicas cuando hay señales de alarma.",
      },
      estiloVida: {
        titulo: "Estilo de vida",
        marco: "Revisa aerofagia, velocidad al comer, actividad y estrés.",
        intervenciones: ["Comer despacio", "Reducir bebidas gaseosas si empeoran", "Actividad física regular"],
        nivelEvidencia: "moderada",
      },
    },
  },
  {
    id: "sii",
    nombre: "Síndrome de intestino irritable compatible",
    descripcion:
      "Patrón compatible con trastorno de interacción intestino-cerebro cuando existe dolor abdominal recurrente asociado a cambios persistentes en el hábito intestinal, sin señales de alarma.",
    sintomas: [
      { nombre: "Dolor abdominal", peso: 3 },
      { nombre: "Hinchazón abdominal", peso: 2 },
      { nombre: "Estreñimiento", peso: 2 },
      { nombre: "Diarrea continua", peso: 2 },
      { nombre: "Sensación de evacuación incompleta", peso: 2 },
      { nombre: "Moco en las heces", peso: 1 },
    ],
    sintomasAlarma: [
      { nombre: "Sangre roja en las heces", gravedad: "alta" },
      { nombre: "Pérdida de peso", gravedad: "alta" },
      { nombre: "Fiebre", gravedad: "alta" },
      { nombre: "Heces negras", gravedad: "alta" },
    ],
    sintomasQueContradicen: [],
    preguntas: [
      { texto: "¿El dolor cambia al defecar?", importancia: 3 },
      { texto: "¿Los cambios intestinales llevan meses o se repiten?", importancia: 3 },
      { texto: "¿Hay sangre, pérdida de peso, fiebre o anemia conocida?", importancia: 3 },
    ],
    posiblesCausas: [
      "Alteración de la interacción intestino-cerebro",
      "Cambios de motilidad y sensibilidad visceral",
      "Factores dietéticos individuales",
      "Estrés y antecedentes de infección intestinal en algunos casos",
    ],
    factoresRiesgo: ["Síntomas recurrentes", "Estrés", "Antecedente de infección intestinal"],
    nutricion: [
      "Ajustar fibra según subtipo y tolerancia",
      "Valorar dieta baja en FODMAP de forma limitada y estructurada cuando proceda",
      "Evitar dietas excesivamente restrictivas",
    ],
    fitoterapia: [
      "Algunos productos como el aceite de menta cuentan con evidencia para síntomas concretos, pero no son adecuados para todos",
      "Revisar especialmente si existe reflujo o medicación concomitante",
    ],
    recomendaciones: ["Identificar subtipo predominante", "Actividad física y sueño", "Manejo del estrés cuando influye"],
    nivelEvidencia: "moderada",
    contraindicaciones: ["No etiquetar como SII si existen señales de alarma sin estudio"],
    interacciones: ["Revisar suplementos y fitoterapia según medicación y síntomas"],
    pruebasMedicasHabituales: [
      "Historia clínica y exploración",
      "Pruebas limitadas dirigidas según subtipo y contexto",
      "Estudio adicional si existen señales de alarma",
    ],
    especialistaRecomendado: ["Médico de Atención Primaria", "Digestólogo", "Dietista-nutricionista"],
    cuandoAcudirMedico: ["Sangrado rectal", "Pérdida de peso", "Fiebre recurrente", "Anemia o síntomas nuevos importantes"],
    bibliografia: ["American College of Gastroenterology: Irritable Bowel Syndrome"],
    enfoques: {
      convencional: {
        titulo: "Medicina convencional",
        marco: "Utiliza una estrategia diagnóstica positiva basada en síntomas, exploración y pruebas limitadas cuando no hay alarmas.",
        intervenciones: ["Clasificar subtipo", "Tratamientos dirigidos a dolor, estreñimiento o diarrea", "Evitar pruebas extensas rutinarias sin indicación"],
        nivelEvidencia: "alta",
      },
      nutricion: {
        titulo: "Nutrición",
        marco: "Adapta fibra y carbohidratos fermentables al patrón individual.",
        intervenciones: ["Fibra soluble cuando esté indicada", "Prueba limitada de dieta baja en FODMAP con reintroducción", "Evitar restricciones crónicas innecesarias"],
        nivelEvidencia: "moderada",
      },
      natural: {
        titulo: "Fitoterapia y medicina natural",
        marco: "Puede considerar recursos con evidencia específica para síntomas concretos.",
        intervenciones: ["Valorar aceite de menta en casos apropiados", "Evitar mezclas sin composición clara", "Revisar contraindicaciones e interacciones"],
        nivelEvidencia: "moderada",
        nota: "El aceite de menta puede empeorar el reflujo en algunas personas.",
      },
      medicinaChina: {
        titulo: "Medicina tradicional china",
        marco: "Interpreta dolor y cambios intestinales mediante patrones propios de Bazo, Hígado, humedad, frío o calor.",
        intervenciones: ["Valoración individual de patrón", "Acupuntura según profesional", "Fitoterapia china supervisada"],
        nivelEvidencia: "tradicional",
        nota: "Marco tradicional distinto de los criterios biomédicos de SII.",
      },
      estiloVida: {
        titulo: "Estilo de vida",
        marco: "Considera sueño, ejercicio y relación intestino-cerebro.",
        intervenciones: ["Actividad física regular", "Rutina de sueño", "Técnicas de manejo del estrés cuando exista relación clara"],
        nivelEvidencia: "moderada",
      },
    },
  },
];