import type { Condicion } from "./condiciones";

export const condicionesGenerales: Condicion[] = [
  {
    id: "sindrome-gripal",
    nombre: "Síndrome gripal / infección viral sistémica compatible",
    descripcion:
      "Fiebre, escalofríos, dolor muscular, cansancio y síntomas respiratorios pueden formar parte de una infección viral como gripe u otros virus respiratorios.",
    sintomas: [
      { nombre: "Fiebre", peso: 2 },
      { nombre: "Escalofríos", peso: 2 },
      { nombre: "Dolor muscular", peso: 2 },
      { nombre: "Cansancio", peso: 1 },
      { nombre: "Dolor de cabeza", peso: 1 },
      { nombre: "Tos seca", peso: 1 },
    ],
    sintomasAlarma: [
      { nombre: "Falta de aire", gravedad: "urgente" },
      { nombre: "Dolor de pecho", gravedad: "urgente" },
      { nombre: "Confusión", gravedad: "urgente" },
      { nombre: "No puedo retener líquidos", gravedad: "alta" },
    ],
    sintomasQueContradicen: [],
    preguntas: [
      { texto: "¿Hay fiebre, dolores musculares y cansancio de inicio reciente?", importancia: 2 },
      { texto: "¿Existe dificultad respiratoria o deterioro importante?", importancia: 3 },
    ],
    posiblesCausas: ["Gripe", "COVID-19 u otros virus respiratorios", "Otras infecciones"],
    factoresRiesgo: ["Edad avanzada", "Enfermedades crónicas", "Inmunosupresión", "Embarazo"],
    nutricion: ["Mantener hidratación", "Alimentación según tolerancia y apetito"],
    fitoterapia: ["No utilizar productos naturales para retrasar valoración si hay dificultad respiratoria o deterioro"],
    recomendaciones: ["Descanso", "Hidratación", "Controlar evolución y signos de alarma"],
    nivelEvidencia: "alta",
    contraindicaciones: ["Evitar automedicación múltiple con productos que repitan principios activos"],
    interacciones: ["Revisar antigripales, descongestionantes y suplementos con la medicación habitual"],
    pruebasMedicasHabituales: ["Evaluación clínica", "Pruebas virales según contexto", "Exploración respiratoria si hay síntomas"],
    especialistaRecomendado: ["Atención Primaria", "Urgencias si hay signos de gravedad"],
    cuandoAcudirMedico: ["Falta de aire", "Dolor de pecho", "Confusión", "Deshidratación", "Empeoramiento importante"],
    bibliografia: ["Guías sobre gripe e infecciones virales respiratorias"],
    enfoques: {
      convencional: {
        titulo: "Medicina convencional",
        marco: "Valora gravedad, factores de riesgo y necesidad de tratamiento antiviral o pruebas específicas según contexto.",
        intervenciones: ["Tratamiento sintomático", "Antivirales en perfiles seleccionados y dentro de ventana apropiada", "Vigilancia de complicaciones"],
        nivelEvidencia: "alta",
      },
      nutricion: {
        titulo: "Nutrición",
        marco: "Hidratación y alimentación tolerable son medidas de apoyo.",
        intervenciones: ["Beber líquidos regularmente", "Mantener ingesta suficiente según tolerancia"],
        nivelEvidencia: "moderada",
      },
      natural: {
        titulo: "Fitoterapia y medicina natural",
        marco: "Puede ofrecer alivio sintomático en algunos casos, pero no sustituye tratamiento específico ni valoración de complicaciones.",
        intervenciones: ["Miel para tos cuando sea apropiada", "Evitar combinaciones herbales de composición incierta"],
        nivelEvidencia: "limitada",
      },
      medicinaChina: {
        titulo: "Medicina tradicional china",
        marco: "Utiliza patrones tradicionales para cuadros febriles y respiratorios.",
        intervenciones: ["Solo como complemento y nunca retrasando atención si hay signos de gravedad"],
        nivelEvidencia: "tradicional",
      },
      estiloVida: {
        titulo: "Estilo de vida",
        marco: "Descanso, ventilación e higiene reducen carga de síntomas y transmisión.",
        intervenciones: ["Dormir suficiente", "Reducir actividad intensa durante la fase aguda", "Higiene respiratoria"],
        nivelEvidencia: "moderada",
      },
    },
  },
  {
    id: "faringitis",
    nombre: "Faringitis / dolor de garganta compatible",
    descripcion:
      "Dolor de garganta, fiebre, ronquera o síntomas catarrales pueden deberse a infección viral o, en algunos casos, bacteriana.",
    sintomas: [
      { nombre: "Dolor de garganta", peso: 3 },
      { nombre: "Fiebre", peso: 2 },
      { nombre: "Ronquera", peso: 1 },
      { nombre: "Congestión nasal", peso: 1 },
      { nombre: "Tos seca", peso: 1 },
    ],
    sintomasAlarma: [
      { nombre: "Dificultad para tragar", gravedad: "alta" },
      { nombre: "Falta de aire", gravedad: "urgente" },
      { nombre: "No puedo tragar saliva", gravedad: "urgente" },
      { nombre: "Voz apagada o dificultad para abrir la boca", gravedad: "alta" },
    ],
    sintomasQueContradicen: [],
    preguntas: [
      { texto: "¿Hay tos y congestión o predominan fiebre y dolor de garganta?", importancia: 2 },
      { texto: "¿Puedes tragar líquidos y saliva con normalidad?", importancia: 3 },
    ],
    posiblesCausas: ["Infección viral", "Faringitis estreptocócica", "Irritación no infecciosa"],
    factoresRiesgo: ["Contacto cercano con personas infectadas", "Edad y contexto epidemiológico"],
    nutricion: ["Líquidos fríos o templados según tolerancia", "Mantener hidratación"],
    fitoterapia: ["Miel puede aliviar irritación en personas adecuadas", "No sustituir antibióticos cuando una infección bacteriana confirmada los requiere"],
    recomendaciones: ["Hidratación", "Analgésicos apropiados si se toleran", "Consultar si el cuadro es intenso o persiste"],
    nivelEvidencia: "alta",
    contraindicaciones: ["No usar miel en menores de un año", "No retrasar atención si hay dificultad para respirar o tragar saliva"],
    interacciones: ["Revisar pastillas, sprays y preparados herbales con medicación habitual"],
    pruebasMedicasHabituales: ["Exploración de garganta", "Test de estreptococo en situaciones seleccionadas"],
    especialistaRecomendado: ["Atención Primaria", "Urgencias si hay obstrucción o deterioro"],
    cuandoAcudirMedico: ["Dificultad respiratoria", "No poder tragar saliva", "Fiebre alta persistente", "Empeoramiento rápido"],
    bibliografia: ["Guías sobre faringitis aguda"],
    enfoques: {
      convencional: {
        titulo: "Medicina convencional",
        marco: "Diferencia cuadros virales de aquellos con mayor probabilidad de infección bacteriana o complicación.",
        intervenciones: ["Tratamiento sintomático", "Pruebas de estreptococo cuando procede", "Antibiótico solo si está indicado"],
        nivelEvidencia: "alta",
      },
      nutricion: {
        titulo: "Nutrición",
        marco: "Se centra en mantener hidratación e ingesta tolerable.",
        intervenciones: ["Bebidas según tolerancia", "Alimentos blandos si tragar resulta molesto"],
        nivelEvidencia: "moderada",
      },
      natural: {
        titulo: "Fitoterapia y medicina natural",
        marco: "Algunos recursos simples pueden aliviar la irritación, pero no determinan la causa.",
        intervenciones: ["Miel cuando sea apropiada", "Gárgaras con agua templada y sal como medida sintomática"],
        nivelEvidencia: "moderada",
      },
      medicinaChina: {
        titulo: "Medicina tradicional china",
        marco: "Clasifica el dolor de garganta mediante patrones tradicionales.",
        intervenciones: ["Uso complementario si no hay signos de alarma"],
        nivelEvidencia: "tradicional",
      },
      estiloVida: {
        titulo: "Estilo de vida",
        marco: "Descanso e higiene ayudan a la recuperación y a reducir transmisión.",
        intervenciones: ["Descansar", "Evitar humo y alcohol si irritan", "Higiene de manos"],
        nivelEvidencia: "moderada",
      },
    },
  },
  {
    id: "deshidratacion-compatible",
    nombre: "Deshidratación compatible",
    descripcion:
      "Poca ingesta de líquidos, orina oscura o escasa, debilidad y mareo pueden indicar deshidratación, especialmente tras vómitos, diarrea, fiebre o calor.",
    sintomas: [
      { nombre: "Poca hidratación", peso: 2 },
      { nombre: "Orina oscura", peso: 2 },
      { nombre: "Orinar muy poca cantidad", peso: 3 },
      { nombre: "Debilidad", peso: 1 },
      { nombre: "Mareo", peso: 1 },
    ],
    sintomasAlarma: [
      { nombre: "Confusión", gravedad: "urgente" },
      { nombre: "Desmayo", gravedad: "urgente" },
      { nombre: "No puedo retener líquidos", gravedad: "alta" },
      { nombre: "Orinar muy poca cantidad", gravedad: "alta" },
    ],
    sintomasQueContradicen: [{ nombre: "Orinar mucha cantidad", peso: 1 }],
    preguntas: [
      { texto: "¿Has tenido vómitos, diarrea, fiebre o exposición a calor?", importancia: 2 },
      { texto: "¿Puedes beber y retener líquidos?", importancia: 3 },
    ],
    posiblesCausas: ["Baja ingesta", "Pérdidas por diarrea o vómitos", "Fiebre", "Calor o ejercicio", "Diuréticos u otras causas médicas"],
    factoresRiesgo: ["Edad avanzada", "Enfermedad renal o cardíaca", "Uso de diuréticos", "Vómitos o diarrea"],
    nutricion: ["Reposición de agua y electrolitos según el tipo y magnitud de las pérdidas"],
    fitoterapia: ["Evitar plantas diuréticas durante deshidratación"],
    recomendaciones: ["Beber en pequeñas cantidades frecuentes si se tolera", "Usar solución de rehidratación oral cuando está indicada"],
    nivelEvidencia: "alta",
    contraindicaciones: ["No recomendar grandes volúmenes de líquidos sin individualizar en insuficiencia cardíaca o renal"],
    interacciones: ["Revisar diuréticos y medicación que aumente pérdidas o altere electrolitos"],
    pruebasMedicasHabituales: ["Valoración clínica", "Electrolitos y función renal si el cuadro es moderado o grave"],
    especialistaRecomendado: ["Atención Primaria", "Urgencias si hay confusión, síncope o incapacidad para beber"],
    cuandoAcudirMedico: ["Confusión", "Desmayo", "No poder retener líquidos", "Orina muy escasa", "Deterioro progresivo"],
    bibliografia: ["Guías sobre rehidratación y deshidratación"],
    enfoques: {
      convencional: {
        titulo: "Medicina convencional",
        marco: "Valora gravedad, causa y alteraciones de electrolitos o función renal.",
        intervenciones: ["Rehidratación oral si es posible", "Fluidoterapia intravenosa si el cuadro es grave", "Tratar la causa"],
        nivelEvidencia: "alta",
      },
      nutricion: {
        titulo: "Nutrición",
        marco: "La reposición adecuada de agua y electrolitos es el centro del tratamiento de pérdidas digestivas leves o moderadas.",
        intervenciones: ["Solución de rehidratación oral cuando procede", "Reponer líquidos de forma fraccionada"],
        nivelEvidencia: "alta",
      },
      natural: {
        titulo: "Fitoterapia y medicina natural",
        marco: "No debe utilizar diuréticos o remedios que aumenten pérdidas de líquido.",
        intervenciones: ["Priorizar rehidratación", "Evitar productos diuréticos"],
        nivelEvidencia: "alta",
      },
      medicinaChina: {
        titulo: "Medicina tradicional china",
        marco: "Puede describir el cuadro mediante patrones tradicionales, pero no sustituye la reposición de líquidos y electrolitos.",
        intervenciones: ["Solo complemento tras corregir la deshidratación"],
        nivelEvidencia: "tradicional",
      },
      estiloVida: {
        titulo: "Estilo de vida",
        marco: "Prevenir pérdidas excesivas y beber de acuerdo con actividad y temperatura reduce riesgo.",
        intervenciones: ["Planificar hidratación en calor o ejercicio", "Aumentar vigilancia en enfermedad aguda"],
        nivelEvidencia: "alta",
      },
    },
  },
];