import type { Condicion } from "./condiciones";

const oculto = { titulo:"No mostrado", marco:"Módulo no utilizado en la interfaz actual.", intervenciones:[], nivelEvidencia:"tradicional" as const };

export const condicionesComunesExtra: Condicion[] = [
{
id:"rinosinusitis-aguda-compatible",nombre:"Rinosinusitis aguda / sinusitis compatible",descripcion:"Congestión nasal, mucosidad y dolor o presión facial pueden aparecer en una rinosinusitis aguda. La mayoría comienza tras una infección viral; la duración y la evolución ayudan a valorar si necesita revisión médica.",
sintomas:[{nombre:"Congestión nasal",peso:3},{nombre:"Mucosidad",peso:2},{nombre:"Dolor facial",peso:3},{nombre:"Pérdida de olfato",peso:2},{nombre:"Dolor de cabeza",peso:1},{nombre:"Fiebre",peso:1}],
sintomasAlarma:[{nombre:"Hinchazón alrededor de los ojos",gravedad:"alta"},{nombre:"Visión doble nueva",gravedad:"urgente"},{nombre:"Confusión",gravedad:"urgente"}],sintomasQueContradicen:[{nombre:"Picor nasal",peso:1},{nombre:"Estornudos",peso:1}],
preguntas:[{texto:"¿Los síntomas llevan más de 10 días sin mejorar o empeoraron después de una mejoría inicial?",importancia:3},{texto:"¿Hay dolor facial intenso, fiebre alta o hinchazón alrededor del ojo?",importancia:3}],
posiblesCausas:["Infección viral de vías respiratorias altas","Rinosinusitis bacteriana en una minoría de casos","Inflamación nasal asociada a alergia"],factoresRiesgo:["Rinitis alérgica","Tabaquismo","Alteraciones anatómicas nasales","Infección respiratoria reciente"],
nutricion:["Mantener hidratación suficiente","Alimentación habitual equilibrada según tolerancia"],fitoterapia:["Los lavados nasales con solución salina pueden ayudar al alivio sintomático","No sustituir valoración médica por aceites esenciales o preparados irritantes"],recomendaciones:["Lavados nasales con solución salina cuando se toleren","Descanso e hidratación","Consultar si persiste, empeora o aparecen señales de alarma"],nivelEvidencia:"alta",contraindicaciones:["No aplicar aceites esenciales concentrados dentro de la nariz","No retrasar atención ante síntomas oculares o neurológicos"],interacciones:["Descongestionantes pueden no ser apropiados en hipertensión o con determinados medicamentos"],pruebasMedicasHabituales:["Historia clínica y exploración","Generalmente no requiere imagen en cuadros no complicados"],especialistaRecomendado:["Atención Primaria","Otorrinolaringología si es recurrente o complicada"],cuandoAcudirMedico:["Síntomas persistentes o empeoramiento tras mejoría inicial","Hinchazón alrededor del ojo","Visión doble","Dolor intenso o deterioro importante"],bibliografia:["Guías clínicas de rinosinusitis aguda"],
enfoques:{convencional:{titulo:"Medicina convencional",marco:"Distingue cuadros virales autolimitados de situaciones con mayor probabilidad bacteriana o complicación.",intervenciones:["Tratamiento sintomático","Antibióticos solo cuando están indicados","Valoración de complicaciones"],nivelEvidencia:"alta"},nutricion:{titulo:"Nutrición",marco:"La hidratación y una ingesta adecuada apoyan la recuperación, pero no curan por sí solas la infección.",intervenciones:["Líquidos suficientes","Dieta equilibrada"],nivelEvidencia:"moderada"},natural:{titulo:"Fitoterapia y suplementación",marco:"Las medidas locales sencillas tienen mejor respaldo que muchas mezclas herbales.",intervenciones:["Solución salina nasal","Evitar productos irritantes"],nivelEvidencia:"moderada"},medicinaChina:oculto,estiloVida:{titulo:"Estilo de vida",marco:"Descanso, evitar humo y mantener humedad ambiental confortable pueden aliviar síntomas.",intervenciones:["Evitar humo","Descansar","Higiene nasal"],nivelEvidencia:"moderada"}}
},
{
id:"bronquitis-aguda-compatible",nombre:"Bronquitis aguda compatible",descripcion:"Tos de varios días, seca o con mucosidad, tras un cuadro respiratorio puede ser compatible con bronquitis aguda. Suele ser viral y la tos puede durar varias semanas.",
sintomas:[{nombre:"Tos seca",peso:3},{nombre:"Tos con mucosidad",peso:3},{nombre:"Mucosidad",peso:1},{nombre:"Cansancio",peso:1},{nombre:"Dolor de pecho al moverme",peso:1}],sintomasAlarma:[{nombre:"Falta de aire intensa",gravedad:"urgente"},{nombre:"Labios azulados",gravedad:"urgente"},{nombre:"Dolor de pecho",gravedad:"urgente"},{nombre:"Confusión",gravedad:"urgente"}],sintomasQueContradicen:[],preguntas:[{texto:"¿La tos apareció tras un resfriado y lleva menos de unas semanas?",importancia:2},{texto:"¿Hay falta de aire importante, fiebre persistente o empeoramiento general?",importancia:3}],posiblesCausas:["Infección viral respiratoria","Irritación bronquial","Otras causas de tos que deben valorarse si persiste"],factoresRiesgo:["Tabaquismo","Asma o enfermedad pulmonar","Edad avanzada","Inmunosupresión"],nutricion:["Hidratación regular","Miel para aliviar la tos en adultos y mayores de un año cuando sea apropiada"],fitoterapia:["No hay una planta que sustituya la valoración ante dificultad respiratoria","Evitar preparados múltiples de composición incierta"],recomendaciones:["Descanso","Evitar humo","Consultar si la tos se prolonga mucho, empeora o aparecen señales de alarma"],nivelEvidencia:"alta",contraindicaciones:["No usar miel en menores de un año","No asumir que toda tos con mucosidad necesita antibiótico"],interacciones:["Revisar antitusivos, descongestionantes y productos herbales con la medicación habitual"],pruebasMedicasHabituales:["Exploración clínica","Saturación de oxígeno si procede","Radiografía solo si se sospecha neumonía u otra causa"],especialistaRecomendado:["Atención Primaria","Urgencias si existe dificultad respiratoria importante"],cuandoAcudirMedico:["Falta de aire","Dolor torácico","Fiebre persistente o deterioro","Tos prolongada o sangre al toser"],bibliografia:["Guías sobre tos aguda y bronquitis"],
enfoques:{convencional:{titulo:"Medicina convencional",marco:"Descarta neumonía y otras causas y evita antibióticos innecesarios en cuadros virales.",intervenciones:["Tratamiento sintomático","Exploración respiratoria","Antibiótico solo cuando existe otra indicación"],nivelEvidencia:"alta"},nutricion:{titulo:"Nutrición",marco:"Hidratación y alimentación suficiente apoyan la recuperación.",intervenciones:["Líquidos regulares","Miel cuando sea apropiada"],nivelEvidencia:"moderada"},natural:{titulo:"Fitoterapia y suplementación",marco:"El beneficio de muchas plantas es limitado; la prioridad es reconocer complicaciones.",intervenciones:["Medidas sintomáticas sencillas","Evitar mezclas innecesarias"],nivelEvidencia:"limitada"},medicinaChina:oculto,estiloVida:{titulo:"Estilo de vida",marco:"Evitar humo y descansar reduce irritación y facilita la recuperación.",intervenciones:["No fumar","Descanso","Ventilación adecuada"],nivelEvidencia:"moderada"}}
},
{
id:"conjuntivitis-compatible",nombre:"Conjuntivitis compatible",descripcion:"Ojo rojo con lagrimeo, picor o secreción puede corresponder a conjuntivitis alérgica, viral o bacteriana. El dolor ocular importante o la pérdida de visión no son propios de una conjuntivitis simple.",
sintomas:[{nombre:"Ojo rojo",peso:3},{nombre:"Lagrimeo",peso:2},{nombre:"Secreción ocular",peso:3},{nombre:"Picor de ojos",peso:2}],sintomasAlarma:[{nombre:"Dolor ocular",gravedad:"alta"},{nombre:"Pérdida brusca de visión",gravedad:"urgente"},{nombre:"Sensibilidad intensa a la luz",gravedad:"alta"}],sintomasQueContradicen:[],preguntas:[{texto:"¿Predomina el picor y afecta a ambos ojos, o existe secreción espesa?",importancia:2},{texto:"¿Hay dolor fuerte, fotofobia o pérdida de visión?",importancia:3}],posiblesCausas:["Conjuntivitis viral","Conjuntivitis alérgica","Conjuntivitis bacteriana","Irritación ocular"],factoresRiesgo:["Contacto con personas con conjuntivitis","Alergia","Lentes de contacto","Higiene de manos deficiente"],nutricion:["No existe un alimento que trate una conjuntivitis aguda","Mantener dieta equilibrada general"],fitoterapia:["No aplicar manzanilla, infusiones ni extractos vegetales directamente en el ojo por riesgo de irritación o contaminación"],recomendaciones:["Higiene de manos","No compartir toallas","Evitar lentes de contacto hasta resolver el cuadro y recibir indicación si procede"],nivelEvidencia:"alta",contraindicaciones:["No colocar preparados caseros dentro del ojo","Usuarios de lentes de contacto con ojo rojo doloroso requieren valoración rápida"],interacciones:[],pruebasMedicasHabituales:["Exploración ocular","Pruebas adicionales si existen signos atípicos o complicaciones"],especialistaRecomendado:["Atención Primaria","Oftalmología ante dolor, fotofobia, pérdida visual o uso de lentes de contacto con sospecha de queratitis"],cuandoAcudirMedico:["Dolor ocular","Pérdida o disminución de visión","Fotofobia intensa","Empeoramiento o falta de mejoría"],bibliografia:["Guías clínicas de ojo rojo y conjuntivitis"],
enfoques:{convencional:{titulo:"Medicina convencional",marco:"Distingue conjuntivitis de queratitis, uveítis y otras causas de ojo rojo que pueden amenazar la visión.",intervenciones:["Exploración ocular","Tratamiento según causa","Antibiótico tópico solo cuando está indicado"],nivelEvidencia:"alta"},nutricion:{titulo:"Nutrición",marco:"No existe un tratamiento nutricional específico para la conjuntivitis aguda.",intervenciones:["Dieta equilibrada general"],nivelEvidencia:"alta"},natural:{titulo:"Fitoterapia y suplementación",marco:"Los preparados vegetales caseros en el ojo pueden contaminar o irritar.",intervenciones:["No aplicar infusiones o aceites esenciales en el ojo"],nivelEvidencia:"alta"},medicinaChina:oculto,estiloVida:{titulo:"Cuidados",marco:"La higiene reduce transmisión y reinfección en cuadros infecciosos.",intervenciones:["Lavado de manos","No compartir toallas","Evitar tocarse los ojos"],nivelEvidencia:"alta"}}
}
];