import type { Condicion } from "./condiciones";

export const condicionesAbdominalesUrgentes: Condicion[] = [
  {
    id: "apendicitis-compatible",
    nombre: "Apendicitis compatible",
    descripcion:
      "Dolor abdominal que se localiza en la parte inferior derecha, especialmente si se acompaña de náuseas, pérdida de apetito o fiebre, puede ser compatible con apendicitis y requiere valoración médica.",
    sintomas: [
      { nombre: "Dolor abdominal", peso: 1 },
      { nombre: "Parte inferior derecha", peso: 3 },
      { nombre: "Náuseas", peso: 1 },
      { nombre: "Pérdida de apetito", peso: 1 },
      { nombre: "Fiebre", peso: 2 },
    ],
    sintomasAlarma: [
      { nombre: "Dolor abdominal intenso", gravedad: "urgente" },
      { nombre: "Vómitos repetidos", gravedad: "alta" },
      { nombre: "Confusión", gravedad: "urgente" },
    ],
    sintomasQueContradicen: [],
    preguntas: [
      { texto: "¿El dolor se localiza en la parte inferior derecha?", importancia: 3 },
      { texto: "¿Hay fiebre, náuseas o pérdida de apetito?", importancia: 2 },
    ],
    posiblesCausas: ["Inflamación del apéndice", "Otras causas abdominales o pélvicas que pueden imitar apendicitis"],
    factoresRiesgo: ["Puede aparecer a cualquier edad"],
    nutricion: ["No forzar comida si existe dolor abdominal importante y se está pendiente de valoración"],
    fitoterapia: ["No tratar una posible apendicitis con plantas, laxantes o remedios caseros"],
    recomendaciones: ["Buscar valoración médica si el patrón es compatible", "No retrasar atención si el dolor progresa"],
    nivelEvidencia: "alta",
    contraindicaciones: ["Evitar laxantes o medidas que retrasen la evaluación de un abdomen agudo"],
    interacciones: ["Informar de analgésicos y suplementos tomados antes de la valoración"],
    pruebasMedicasHabituales: ["Exploración abdominal", "Analítica", "Ecografía o TC según contexto"],
    especialistaRecomendado: ["Urgencias", "Cirugía general si se confirma"],
    cuandoAcudirMedico: ["Dolor que progresa o se localiza abajo a la derecha", "Fiebre", "Vómitos", "Dolor intenso"],
    bibliografia: ["Guías sobre dolor abdominal agudo y apendicitis"],
    enfoques: {
      convencional: {
        titulo: "Medicina convencional",
        marco: "Confirma o descarta apendicitis mediante exploración, analítica e imagen cuando está indicada.",
        intervenciones: ["Valoración urgente", "Analgesia y fluidoterapia según necesidad", "Tratamiento quirúrgico o antibiótico según diagnóstico y protocolo"],
        nivelEvidencia: "alta",
      },
      nutricion: {
        titulo: "Nutrición",
        marco: "No es un cuadro para intentar resolver con dieta.",
        intervenciones: ["Seguir las indicaciones médicas sobre ayuno o ingesta"],
        nivelEvidencia: "alta",
      },
      natural: {
        titulo: "Fitoterapia y medicina natural",
        marco: "No tiene un papel como tratamiento sustitutivo de una posible apendicitis.",
        intervenciones: ["No retrasar valoración médica"],
        nivelEvidencia: "limitada",
      },
      medicinaChina: {
        titulo: "Medicina tradicional china",
        marco: "No debe utilizarse para retrasar la evaluación de un posible abdomen agudo.",
        intervenciones: ["Sin intervención sustitutiva antes de descartar urgencia quirúrgica"],
        nivelEvidencia: "tradicional",
      },
      estiloVida: {
        titulo: "Estilo de vida",
        marco: "No existen medidas de estilo de vida que sustituyan la evaluación del cuadro agudo.",
        intervenciones: ["Buscar atención y vigilar empeoramiento"],
        nivelEvidencia: "alta",
      },
    },
  },
  {
    id: "vesicula-biliar-compatible",
    nombre: "Cólico biliar / colecistitis compatible",
    descripcion:
      "Dolor en la parte superior derecha del abdomen, con náuseas o vómitos y especialmente con fiebre, puede relacionarse con cálculos biliares o inflamación de la vesícula.",
    sintomas: [
      { nombre: "Dolor abdominal", peso: 1 },
      { nombre: "Parte superior derecha", peso: 3 },
      { nombre: "Náuseas", peso: 1 },
      { nombre: "Vómitos", peso: 1 },
      { nombre: "Fiebre", peso: 2 },
    ],
    sintomasAlarma: [
      { nombre: "Dolor abdominal intenso", gravedad: "urgente" },
      { nombre: "Color amarillo en la piel", gravedad: "alta" },
      { nombre: "Confusión", gravedad: "urgente" },
    ],
    sintomasQueContradicen: [],
    preguntas: [
      { texto: "¿El dolor está en la parte superior derecha?", importancia: 3 },
      { texto: "¿Hay fiebre, vómitos o color amarillo en piel u ojos?", importancia: 3 },
    ],
    posiblesCausas: ["Cálculos biliares", "Inflamación de la vesícula", "Otras causas hepáticas o digestivas"],
    factoresRiesgo: ["Antecedentes de cálculos biliares", "Obesidad", "Pérdida rápida de peso", "Edad y otros factores metabólicos"],
    nutricion: ["Evitar comidas muy grasas puede reducir desencadenantes en personas con cólico biliar conocido, pero no trata una colecistitis"],
    fitoterapia: ["Evitar plantas coleréticas o colagogas si se sospecha obstrucción biliar"],
    recomendaciones: ["Buscar valoración si el dolor es intenso, persistente o se acompaña de fiebre o ictericia"],
    nivelEvidencia: "alta",
    contraindicaciones: ["No usar preparados que estimulen la salida de bilis si existe posible obstrucción"],
    interacciones: ["Revisar suplementos hepatobiliares y medicación habitual"],
    pruebasMedicasHabituales: ["Ecografía abdominal", "Analítica hepática e inflamatoria", "Otras pruebas según evolución"],
    especialistaRecomendado: ["Urgencias o Atención Primaria según intensidad", "Cirugía/Digestivo según diagnóstico"],
    cuandoAcudirMedico: ["Fiebre", "Dolor persistente o intenso", "Ictericia", "Vómitos persistentes"],
    bibliografia: ["Guías sobre litiasis biliar y colecistitis"],
    enfoques: {
      convencional: {
        titulo: "Medicina convencional",
        marco: "Diferencia cólico biliar no complicado de colecistitis u obstrucción mediante clínica, analítica e imagen.",
        intervenciones: ["Analgesia", "Ecografía", "Antibióticos o cirugía cuando están indicados"],
        nivelEvidencia: "alta",
      },
      nutricion: {
        titulo: "Nutrición",
        marco: "La dieta puede modular síntomas entre episodios, pero no resuelve una inflamación u obstrucción aguda.",
        intervenciones: ["Reducir comidas muy grasas si desencadenan episodios", "Evitar restricciones extremas sin indicación"],
        nivelEvidencia: "moderada",
      },
      natural: {
        titulo: "Fitoterapia y medicina natural",
        marco: "Los productos coleréticos pueden ser inadecuados si existe obstrucción biliar.",
        intervenciones: ["No utilizar plantas para intentar expulsar cálculos durante un cuadro agudo"],
        nivelEvidencia: "limitada",
      },
      medicinaChina: {
        titulo: "Medicina tradicional china",
        marco: "Puede ofrecer un marco tradicional para molestias digestivas, pero no sustituye ecografía ni tratamiento de complicaciones biliares.",
        intervenciones: ["Solo complemento fuera de cuadros agudos complicados"],
        nivelEvidencia: "tradicional",
      },
      estiloVida: {
        titulo: "Estilo de vida",
        marco: "Peso estable y hábitos dietéticos pueden influir en riesgo y síntomas a largo plazo.",
        intervenciones: ["Evitar pérdidas de peso extremas", "Mantener actividad física y patrón dietético equilibrado"],
        nivelEvidencia: "moderada",
      },
    },
  },
  {
    id: "pancreatitis-compatible",
    nombre: "Pancreatitis aguda compatible",
    descripcion:
      "Dolor intenso en la parte alta o central del abdomen, a veces irradiado hacia la espalda y acompañado de náuseas o vómitos, puede ser compatible con pancreatitis y necesita valoración médica.",
    sintomas: [
      { nombre: "Dolor abdomen superior", peso: 3 },
      { nombre: "Dolor de espalda", peso: 1 },
      { nombre: "Náuseas", peso: 1 },
      { nombre: "Vómitos", peso: 2 },
      { nombre: "Dolor abdominal", peso: 1 },
    ],
    sintomasAlarma: [
      { nombre: "Dolor abdominal intenso", gravedad: "urgente" },
      { nombre: "Confusión", gravedad: "urgente" },
      { nombre: "Falta de aire", gravedad: "urgente" },
      { nombre: "Vómitos repetidos", gravedad: "alta" },
    ],
    sintomasQueContradicen: [],
    preguntas: [
      { texto: "¿El dolor está en la parte alta y se irradia a la espalda?", importancia: 3 },
      { texto: "¿Hay vómitos persistentes o deterioro general?", importancia: 3 },
    ],
    posiblesCausas: ["Cálculos biliares", "Alcohol", "Triglicéridos muy elevados", "Fármacos y otras causas"],
    factoresRiesgo: ["Litiasis biliar", "Consumo elevado de alcohol", "Hipertrigliceridemia", "Antecedentes de pancreatitis"],
    nutricion: ["La alimentación durante un episodio agudo debe seguir indicación clínica"],
    fitoterapia: ["No utilizar plantas o suplementos para tratar un posible episodio agudo"],
    recomendaciones: ["Buscar valoración médica", "No retrasar atención si el dolor es intenso o persiste"],
    nivelEvidencia: "alta",
    contraindicaciones: ["No automedicarse intentando ocultar dolor abdominal intenso"],
    interacciones: ["Informar de alcohol, medicamentos y suplementos que puedan ser relevantes"],
    pruebasMedicasHabituales: ["Lipasa y analítica", "Ecografía", "TC u otras pruebas según gravedad y evolución"],
    especialistaRecomendado: ["Urgencias", "Digestivo según evolución"],
    cuandoAcudirMedico: ["Dolor abdominal intenso persistente", "Vómitos repetidos", "Dificultad respiratoria", "Confusión"],
    bibliografia: ["Guías sobre pancreatitis aguda"],
    enfoques: {
      convencional: {
        titulo: "Medicina convencional",
        marco: "Confirma pancreatitis, valora gravedad y trata complicaciones y causa subyacente.",
        intervenciones: ["Analgesia y fluidoterapia", "Monitorización", "Tratamiento de la causa y complicaciones"],
        nivelEvidencia: "alta",
      },
      nutricion: {
        titulo: "Nutrición",
        marco: "La estrategia nutricional forma parte del manejo clínico y depende de gravedad y tolerancia.",
        intervenciones: ["Seguir pauta hospitalaria o médica sobre ingesta y reintroducción de alimentación"],
        nivelEvidencia: "alta",
      },
      natural: {
        titulo: "Fitoterapia y medicina natural",
        marco: "No existe un tratamiento natural sustitutivo para una pancreatitis aguda.",
        intervenciones: ["No retrasar atención médica"],
        nivelEvidencia: "limitada",
      },
      medicinaChina: {
        titulo: "Medicina tradicional china",
        marco: "No debe utilizarse para sustituir la atención de una pancreatitis aguda.",
        intervenciones: ["Sin papel sustitutivo en el episodio agudo"],
        nivelEvidencia: "tradicional",
      },
      estiloVida: {
        titulo: "Estilo de vida",
        marco: "Tras resolver el episodio, reducir factores causales puede prevenir recurrencias.",
        intervenciones: ["Evitar alcohol si fue factor causal", "Controlar triglicéridos y peso", "Tratar litiasis biliar si corresponde"],
        nivelEvidencia: "alta",
      },
    },
  },
];