import type { Condicion } from "./condiciones";

export const condicionesMusculoExtra: Condicion[] = [
  {
    id: "cervicalgia",
    nombre: "Cervicalgia mecánica compatible",
    descripcion:
      "Dolor y rigidez de cuello relacionados con postura, sobrecarga o movimiento, sin déficit neurológico ni traumatismo importante.",
    sintomas: [
      { nombre: "Dolor de cuello", peso: 3 },
      { nombre: "Rigidez", peso: 2 },
      { nombre: "Limitación de movimiento", peso: 2 },
      { nombre: "Dolor muscular", peso: 1 },
    ],
    sintomasAlarma: [
      { nombre: "Pérdida de fuerza", gravedad: "alta" },
      { nombre: "Fiebre con rigidez de cuello", gravedad: "urgente" },
      { nombre: "Confusión", gravedad: "urgente" },
    ],
    sintomasQueContradicen: [],
    preguntas: [
      { texto: "¿El dolor empeora con postura o movimiento?", importancia: 2 },
      { texto: "¿Existe pérdida de fuerza, hormigueo intenso o fiebre?", importancia: 3 },
    ],
    posiblesCausas: ["Sobrecarga muscular", "Postura mantenida", "Degeneración cervical", "Traumatismo menor"],
    factoresRiesgo: ["Trabajo sedentario", "Posturas prolongadas", "Estrés", "Sobrecarga repetitiva"],
    nutricion: ["No existe una dieta específica para cervicalgia mecánica"],
    fitoterapia: ["Los antiinflamatorios naturales tienen evidencia variable y deben revisarse si se toman anticoagulantes u otra medicación"],
    recomendaciones: ["Mantener movimiento suave", "Evitar reposo prolongado", "Revisar ergonomía"],
    nivelEvidencia: "moderada",
    contraindicaciones: ["No manipular el cuello ante síntomas neurológicos o tras traumatismo importante"],
    interacciones: ["Revisar suplementos con efecto antiagregante si se usan junto a anticoagulantes"],
    pruebasMedicasHabituales: ["Exploración clínica", "Imagen solo si hay traumatismo, déficit neurológico o sospecha específica"],
    especialistaRecomendado: ["Atención Primaria", "Fisioterapia", "Traumatología/Neurología según hallazgos"],
    cuandoAcudirMedico: ["Pérdida de fuerza", "Fiebre con rigidez", "Dolor tras traumatismo importante", "Empeoramiento progresivo"],
    bibliografia: ["Guías sobre dolor cervical mecánico"],
    enfoques: {
      convencional: {
        titulo: "Medicina convencional",
        marco: "Descarta lesión neurológica o traumática y trata el dolor mecánico con medidas conservadoras.",
        intervenciones: ["Analgesia apropiada", "Ejercicio y fisioterapia", "Pruebas si existen señales de alarma"],
        nivelEvidencia: "alta",
      },
      nutricion: {
        titulo: "Nutrición",
        marco: "No es un tratamiento principal; se mantiene un patrón saludable general.",
        intervenciones: ["Mantener alimentación equilibrada"],
        nivelEvidencia: "limitada",
      },
      natural: {
        titulo: "Fitoterapia y medicina natural",
        marco: "Puede usarse como complemento para molestias leves, revisando evidencia e interacciones.",
        intervenciones: ["Calor local si resulta confortable", "Valorar recursos antiinflamatorios solo como complemento"],
        nivelEvidencia: "limitada",
      },
      medicinaChina: {
        titulo: "Medicina tradicional china",
        marco: "Acupuntura y técnicas tradicionales se utilizan para dolor cervical dentro de su propio marco.",
        intervenciones: ["Acupuntura como complemento en dolor cervical no complicado"],
        nivelEvidencia: "tradicional",
      },
      estiloVida: {
        titulo: "Estilo de vida",
        marco: "Ergonomía, movimiento y pausas activas influyen en recaídas.",
        intervenciones: ["Pausas frecuentes", "Fortalecimiento progresivo", "Evitar posturas mantenidas"],
        nivelEvidencia: "moderada",
      },
    },
  },
  {
    id: "sobrecarga-muscular",
    nombre: "Sobrecarga o dolor muscular compatible",
    descripcion:
      "Dolor localizado tras esfuerzo, ejercicio, trabajo físico o postura mantenida, sin signos de lesión grave o enfermedad sistémica.",
    sintomas: [
      { nombre: "Dolor muscular", peso: 3 },
      { nombre: "Rigidez", peso: 1 },
      { nombre: "Limitación de movimiento", peso: 1 },
      { nombre: "Calambres", peso: 1 },
    ],
    sintomasAlarma: [
      { nombre: "Debilidad muscular", gravedad: "alta" },
      { nombre: "Orina oscura", gravedad: "alta" },
      { nombre: "Fiebre", gravedad: "alta" },
    ],
    sintomasQueContradicen: [],
    preguntas: [
      { texto: "¿Empezó tras ejercicio, esfuerzo o trabajo físico?", importancia: 2 },
      { texto: "¿Existe debilidad real, fiebre o orina muy oscura?", importancia: 3 },
    ],
    posiblesCausas: ["Sobrecarga", "Ejercicio no habitual", "Tensión muscular", "Calambres por fatiga"],
    factoresRiesgo: ["Incremento brusco de actividad", "Mala recuperación", "Deshidratación"],
    nutricion: ["Asegurar ingesta suficiente de energía, proteína y líquidos según actividad"],
    fitoterapia: ["Algunos productos tópicos pueden aliviar síntomas, con evidencia variable"],
    recomendaciones: ["Reposo relativo", "Movimiento suave", "Retorno progresivo a actividad"],
    nivelEvidencia: "moderada",
    contraindicaciones: ["Dolor muscular intenso con debilidad u orina oscura requiere valoración"],
    interacciones: ["Revisar analgésicos y suplementos deportivos"],
    pruebasMedicasHabituales: ["Generalmente ninguna en sobrecarga leve", "Analítica si se sospecha daño muscular importante"],
    especialistaRecomendado: ["Atención Primaria", "Fisioterapia"],
    cuandoAcudirMedico: ["Debilidad marcada", "Orina oscura", "Fiebre", "Dolor desproporcionado o persistente"],
    bibliografia: ["Guías de lesiones musculares y ejercicio"],
    enfoques: {
      convencional: {
        titulo: "Medicina convencional",
        marco: "Diferencia sobrecarga simple de lesión estructural o daño muscular relevante.",
        intervenciones: ["Reposo relativo", "Analgesia si procede", "Rehabilitación progresiva"],
        nivelEvidencia: "alta",
      },
      nutricion: {
        titulo: "Nutrición",
        marco: "Una recuperación adecuada necesita suficiente energía, proteína y líquidos.",
        intervenciones: ["Proteína suficiente", "Hidratación", "Evitar déficits energéticos prolongados"],
        nivelEvidencia: "moderada",
      },
      natural: {
        titulo: "Fitoterapia y medicina natural",
        marco: "Puede ofrecer apoyo sintomático, pero no sustituye diagnóstico si el dolor es severo.",
        intervenciones: ["Calor o frío según tolerancia", "Masaje suave si no hay lesión aguda importante"],
        nivelEvidencia: "limitada",
      },
      medicinaChina: {
        titulo: "Medicina tradicional china",
        marco: "Acupuntura y técnicas manuales se utilizan para dolor muscular en su marco tradicional.",
        intervenciones: ["Uso complementario en cuadros no complicados"],
        nivelEvidencia: "tradicional",
      },
      estiloVida: {
        titulo: "Estilo de vida",
        marco: "La progresión del entrenamiento y el descanso influyen en recaídas.",
        intervenciones: ["Aumentar cargas gradualmente", "Dormir suficiente", "Programar recuperación"],
        nivelEvidencia: "moderada",
      },
    },
  },
  {
    id: "dolor-articular-degenerativo",
    nombre: "Dolor articular mecánico / artrosis compatible",
    descripcion:
      "Dolor articular que empeora con uso y puede acompañarse de rigidez y limitación de movimiento puede ser compatible con un problema mecánico o degenerativo.",
    sintomas: [
      { nombre: "Dolor articular", peso: 3 },
      { nombre: "Rigidez", peso: 2 },
      { nombre: "Limitación de movimiento", peso: 2 },
      { nombre: "Inflamación", peso: 1 },
    ],
    sintomasAlarma: [
      { nombre: "Fiebre", gravedad: "alta" },
      { nombre: "Articulación roja y muy caliente", gravedad: "urgente" },
      { nombre: "No puedo apoyar tras traumatismo", gravedad: "alta" },
    ],
    sintomasQueContradicen: [],
    preguntas: [
      { texto: "¿El dolor empeora con uso y mejora parcialmente con reposo?", importancia: 2 },
      { texto: "¿La articulación está roja, muy caliente o hay fiebre?", importancia: 3 },
    ],
    posiblesCausas: ["Artrosis", "Sobrecarga articular", "Tendinopatía periarticular", "Otras artritis"],
    factoresRiesgo: ["Edad", "Sobrepeso", "Lesiones previas", "Sobrecarga repetitiva"],
    nutricion: ["Si existe exceso de peso, una reducción gradual puede disminuir carga articular"],
    fitoterapia: ["Algunos extractos antiinflamatorios tienen evidencia modesta y posibles interacciones"],
    recomendaciones: ["Ejercicio adaptado", "Fortalecimiento", "Mantener movilidad"],
    nivelEvidencia: "moderada",
    contraindicaciones: ["Articulación roja, caliente y dolorosa con fiebre necesita valoración urgente"],
    interacciones: ["Revisar cúrcuma, boswellia u otros productos si se usan anticoagulantes o medicación crónica"],
    pruebasMedicasHabituales: ["Exploración", "Radiografía si cambia manejo", "Analítica si se sospecha artritis inflamatoria"],
    especialistaRecomendado: ["Atención Primaria", "Fisioterapia", "Reumatología/Traumatología según patrón"],
    cuandoAcudirMedico: ["Fiebre y articulación caliente", "Traumatismo con incapacidad para apoyar", "Inflamación persistente"],
    bibliografia: ["Guías sobre artrosis y dolor articular"],
    enfoques: {
      convencional: {
        titulo: "Medicina convencional",
        marco: "Diferencia dolor degenerativo de artritis inflamatoria, infección o lesión traumática.",
        intervenciones: ["Ejercicio terapéutico", "Control del dolor", "Tratamientos específicos según articulación y diagnóstico"],
        nivelEvidencia: "alta",
      },
      nutricion: {
        titulo: "Nutrición",
        marco: "El peso corporal y el patrón dietético influyen en carga articular y salud metabólica.",
        intervenciones: ["Pérdida de peso gradual si existe exceso de peso", "Patrón mediterráneo equilibrado"],
        nivelEvidencia: "moderada",
      },
      natural: {
        titulo: "Fitoterapia y medicina natural",
        marco: "Algunos productos pueden ofrecer alivio modesto, con variabilidad entre preparaciones.",
        intervenciones: ["Valorar curcuminoides o boswellia solo tras revisar medicación y expectativas"],
        nivelEvidencia: "limitada",
      },
      medicinaChina: {
        titulo: "Medicina tradicional china",
        marco: "Acupuntura se utiliza como complemento para dolor articular en algunos contextos.",
        intervenciones: ["Acupuntura complementaria en dolor crónico seleccionado"],
        nivelEvidencia: "tradicional",
      },
      estiloVida: {
        titulo: "Estilo de vida",
        marco: "Mantener fuerza y actividad es una de las estrategias más importantes a largo plazo.",
        intervenciones: ["Ejercicio regular", "Fortalecimiento", "Evitar inactividad prolongada"],
        nivelEvidencia: "alta",
      },
    },
  },
  {
    id: "insuficiencia-venosa",
    nombre: "Pesadez venosa / insuficiencia venosa compatible",
    descripcion:
      "Pesadez o hinchazón de ambas piernas que empeora al final del día o tras estar mucho tiempo de pie puede relacionarse con insuficiencia venosa, siempre diferenciándola de trombosis o causas cardíacas/renales.",
    sintomas: [
      { nombre: "Hinchazón de piernas", peso: 2 },
      { nombre: "Pesadez de piernas", peso: 3 },
      { nombre: "Varices", peso: 2 },
      { nombre: "Mejora al elevar las piernas", peso: 2 },
    ],
    sintomasAlarma: [
      { nombre: "Hinchazón de una sola pierna", gravedad: "alta" },
      { nombre: "Pierna roja y caliente", gravedad: "alta" },
      { nombre: "Falta de aire", gravedad: "urgente" },
      { nombre: "Dolor de pecho", gravedad: "urgente" },
    ],
    sintomasQueContradicen: [],
    preguntas: [
      { texto: "¿La hinchazón es en ambas piernas y empeora al final del día?", importancia: 2 },
      { texto: "¿Una pierna está claramente más hinchada, roja o caliente?", importancia: 3 },
    ],
    posiblesCausas: ["Insuficiencia venosa", "Estar muchas horas de pie", "Varices", "Otras causas de edema"],
    factoresRiesgo: ["Varices", "Sedentarismo", "Trabajo de pie", "Embarazo", "Edad"],
    nutricion: ["Mantener peso saludable y moderar exceso de sal si contribuye a retención, según contexto"],
    fitoterapia: ["Algunos extractos venotónicos tienen evidencia limitada o moderada y posibles interacciones"],
    recomendaciones: ["Caminar", "Elevar piernas", "Evitar inmovilidad prolongada", "Valorar compresión si un profesional la indica"],
    nivelEvidencia: "moderada",
    contraindicaciones: ["No usar compresión sin valoración si existe enfermedad arterial significativa o sospecha de trombosis"],
    interacciones: ["Revisar castaño de Indias y otros venotónicos si se usan anticoagulantes"],
    pruebasMedicasHabituales: ["Exploración vascular", "Eco-Doppler si hay dudas o síntomas relevantes"],
    especialistaRecomendado: ["Atención Primaria", "Cirugía vascular/Angiología según caso"],
    cuandoAcudirMedico: ["Hinchazón unilateral", "Pierna roja y caliente", "Falta de aire", "Dolor torácico"],
    bibliografia: ["Guías sobre insuficiencia venosa crónica"],
    enfoques: {
      convencional: {
        titulo: "Medicina convencional",
        marco: "Diferencia insuficiencia venosa de trombosis y otras causas de edema.",
        intervenciones: ["Medidas compresivas cuando están indicadas", "Ejercicio", "Tratamientos venosos específicos según gravedad"],
        nivelEvidencia: "alta",
      },
      nutricion: {
        titulo: "Nutrición",
        marco: "Peso y consumo elevado de sal pueden influir en síntomas de edema en algunos casos.",
        intervenciones: ["Mantener peso saludable", "Evitar exceso de sal si existe retención"],
        nivelEvidencia: "moderada",
      },
      natural: {
        titulo: "Fitoterapia y medicina natural",
        marco: "Algunos venotónicos vegetales pueden reducir síntomas, pero deben revisarse por interacciones.",
        intervenciones: ["Valorar extractos estandarizados solo como complemento"],
        nivelEvidencia: "limitada",
      },
      medicinaChina: {
        titulo: "Medicina tradicional china",
        marco: "Interpreta edema y pesadez mediante patrones propios.",
        intervenciones: ["Uso complementario después de descartar trombosis y causas sistémicas"],
        nivelEvidencia: "tradicional",
      },
      estiloVida: {
        titulo: "Estilo de vida",
        marco: "El movimiento de la pantorrilla y evitar inmovilidad prolongada favorecen retorno venoso.",
        intervenciones: ["Caminar", "Mover tobillos si se permanece sentado", "Elevar piernas", "Evitar estar inmóvil muchas horas"],
        nivelEvidencia: "moderada",
      },
    },
  },
];