import type { Condicion } from "./condiciones";

export const condicionesDermatologicas: Condicion[] = [
  {
    id: "dermatitis-eczema",
    nombre: "Dermatitis / eczema compatible",
    descripcion:
      "Picor, sequedad, enrojecimiento y descamación pueden aparecer en dermatitis irritativa, alérgica o atópica. La orientación depende de la localización, duración y posibles desencadenantes.",
    sintomas: [
      { nombre: "Picor", peso: 3 },
      { nombre: "Sequedad de piel", peso: 2 },
      { nombre: "Enrojecimiento", peso: 2 },
      { nombre: "Descamación", peso: 2 },
      { nombre: "Erupción", peso: 1 },
    ],
    sintomasAlarma: [
      { nombre: "Fiebre", gravedad: "alta" },
      { nombre: "Hinchazón de cara o labios", gravedad: "urgente" },
      { nombre: "Falta de aire", gravedad: "urgente" },
      { nombre: "Dolor intenso en la piel", gravedad: "alta" },
    ],
    sintomasQueContradicen: [
      { nombre: "Ampollas agrupadas", peso: 2 },
      { nombre: "Ronchas", peso: 1 },
    ],
    preguntas: [
      { texto: "¿La piel está seca, roja y con picor?", importancia: 2 },
      { texto: "¿Ha aparecido tras usar un jabón, cosmético, metal, guante o producto nuevo?", importancia: 2 },
      { texto: "¿Hay fiebre, dolor intenso o signos de infección?", importancia: 3 },
    ],
    posiblesCausas: [
      "Dermatitis atópica",
      "Dermatitis de contacto irritativa",
      "Dermatitis de contacto alérgica",
      "Irritación por humedad, sudor o fricción",
    ],
    factoresRiesgo: ["Piel atópica", "Alergias", "Exposición laboral a irritantes", "Lavados frecuentes"],
    nutricion: [
      "No eliminar grupos de alimentos sin una relación clara o una indicación profesional",
      "Mantener una alimentación suficiente y variada",
    ],
    fitoterapia: [
      "Evitar aceites esenciales y extractos concentrados sobre piel inflamada sin valorar tolerancia",
      "Algunos emolientes de origen vegetal pueden ser útiles si no producen irritación o alergia",
    ],
    recomendaciones: [
      "Usar limpiadores suaves",
      "Aplicar emoliente sin perfume varias veces al día",
      "Evitar el producto desencadenante si se identifica",
      "No rascar ni aplicar remedios irritantes",
    ],
    nivelEvidencia: "alta",
    contraindicaciones: ["No aplicar sustancias irritantes, alcohol o aceites esenciales sobre lesiones abiertas"],
    interacciones: ["Revisar productos tópicos si se utilizan varios tratamientos a la vez"],
    pruebasMedicasHabituales: [
      "Exploración de la piel",
      "Pruebas epicutáneas si se sospecha alergia de contacto persistente",
    ],
    especialistaRecomendado: ["Atención Primaria", "Dermatología", "Alergología en casos seleccionados"],
    cuandoAcudirMedico: [
      "Fiebre",
      "Dolor intenso",
      "Supuración extensa",
      "Hinchazón de cara o labios",
      "Dificultad respiratoria",
      "Lesiones persistentes o muy extensas",
    ],
    bibliografia: ["Guías clínicas de dermatitis atópica y dermatitis de contacto"],
    enfoques: {
      convencional: {
        titulo: "Medicina convencional",
        marco: "Distingue dermatitis de otras enfermedades cutáneas y valora infección, alergia y gravedad.",
        intervenciones: ["Emolientes", "Corticoides tópicos u otros tratamientos cuando están indicados", "Evitar desencadenantes"],
        nivelEvidencia: "alta",
      },
      nutricion: {
        titulo: "Nutrición",
        marco: "Las restricciones dietéticas solo deben hacerse cuando existe una relación demostrada o una indicación concreta.",
        intervenciones: ["Evitar dietas de exclusión innecesarias", "Mantener una dieta variada"],
        nivelEvidencia: "moderada",
      },
      natural: {
        titulo: "Fitoterapia y medicina natural",
        marco: "Prioriza medidas suaves de cuidado de barrera y evita sustancias sensibilizantes o irritantes.",
        intervenciones: ["Emolientes bien tolerados", "Evitar aceites esenciales en piel inflamada"],
        nivelEvidencia: "limitada",
      },
      medicinaChina: {
        titulo: "Medicina tradicional china",
        marco: "Puede utilizar patrones tradicionales para describir lesiones cutáneas, pero no sustituye la valoración dermatológica.",
        intervenciones: ["Uso solo complementario y con productos de composición conocida"],
        nivelEvidencia: "tradicional",
      },
      estiloVida: {
        titulo: "Estilo de vida",
        marco: "El cuidado de la barrera cutánea y la reducción de irritantes son fundamentales.",
        intervenciones: ["Duchas cortas y templadas", "Ropa suave", "Evitar perfumes y detergentes irritantes"],
        nivelEvidencia: "alta",
      },
    },
  },
  {
    id: "urticaria",
    nombre: "Urticaria compatible",
    descripcion:
      "Ronchas elevadas, rojizas o pálidas, muy pruriginosas y cambiantes de localización son compatibles con urticaria. La presencia de dificultad respiratoria o hinchazón de lengua o garganta es una urgencia.",
    sintomas: [
      { nombre: "Ronchas", peso: 3 },
      { nombre: "Picor", peso: 2 },
      { nombre: "Enrojecimiento", peso: 1 },
      { nombre: "Hinchazón de cara o labios", peso: 2 },
    ],
    sintomasAlarma: [
      { nombre: "Falta de aire", gravedad: "urgente" },
      { nombre: "Hinchazón de lengua o garganta", gravedad: "urgente" },
      { nombre: "Desmayo", gravedad: "urgente" },
      { nombre: "Hinchazón de cara o labios", gravedad: "alta" },
    ],
    sintomasQueContradicen: [
      { nombre: "Descamación", peso: 1 },
      { nombre: "Ampollas agrupadas", peso: 2 },
    ],
    preguntas: [
      { texto: "¿Las ronchas aparecen y desaparecen o cambian de lugar en horas?", importancia: 2 },
      { texto: "¿Ha habido alimento, medicamento, picadura o producto nuevo?", importancia: 2 },
      { texto: "¿Hay dificultad para respirar o hinchazón de lengua o garganta?", importancia: 3 },
    ],
    posiblesCausas: ["Urticaria espontánea", "Reacción a medicamentos", "Alimentos", "Picaduras", "Infecciones", "Estímulos físicos"],
    factoresRiesgo: ["Antecedentes alérgicos", "Nuevos medicamentos", "Picaduras", "Infecciones recientes"],
    nutricion: ["No hacer dietas restrictivas amplias sin identificar un desencadenante reproducible"],
    fitoterapia: ["Evitar productos herbales nuevos durante un episodio si pueden ser el desencadenante"],
    recomendaciones: [
      "Suspender un posible desencadenante no esencial si existe una relación temporal clara",
      "Evitar calor intenso y rascado",
      "Consultar si los episodios se repiten o duran varias semanas",
    ],
    nivelEvidencia: "alta",
    contraindicaciones: ["No confiar en remedios caseros ante signos de anafilaxia"],
    interacciones: ["Algunos antihistamínicos producen somnolencia; revisar combinación con alcohol, sedantes u otros fármacos"],
    pruebasMedicasHabituales: ["Historia clínica y exploración", "Estudios dirigidos solo cuando la evolución lo justifica"],
    especialistaRecomendado: ["Atención Primaria", "Alergología", "Dermatología", "Urgencias si hay síntomas respiratorios"],
    cuandoAcudirMedico: [
      "Dificultad respiratoria",
      "Hinchazón de lengua o garganta",
      "Desmayo",
      "Afectación extensa persistente",
      "Episodios repetidos sin causa clara",
    ],
    bibliografia: ["Guías internacionales de urticaria"],
    enfoques: {
      convencional: {
        titulo: "Medicina convencional",
        marco: "Prioriza descartar anafilaxia y tratar síntomas con antihistamínicos cuando corresponde.",
        intervenciones: ["Antihistamínicos de segunda generación", "Adrenalina intramuscular en anafilaxia", "Buscar desencadenantes cuando procede"],
        nivelEvidencia: "alta",
      },
      nutricion: {
        titulo: "Nutrición",
        marco: "Solo tiene un papel específico cuando existe relación reproducible con un alimento.",
        intervenciones: ["Evitar únicamente desencadenantes demostrados", "No hacer restricciones extensas sin supervisión"],
        nivelEvidencia: "moderada",
      },
      natural: {
        titulo: "Fitoterapia y medicina natural",
        marco: "No existe un sustituto natural fiable para tratar una reacción alérgica grave.",
        intervenciones: ["Evitar nuevos suplementos durante el episodio", "Medidas calmantes no irritantes"],
        nivelEvidencia: "limitada",
      },
      medicinaChina: {
        titulo: "Medicina tradicional china",
        marco: "Puede utilizarse como complemento en cuadros crónicos seleccionados, nunca en una reacción aguda grave.",
        intervenciones: ["Solo tras descartar causas graves y con seguimiento"],
        nivelEvidencia: "tradicional",
      },
      estiloVida: {
        titulo: "Estilo de vida",
        marco: "Evitar desencadenantes conocidos y calor excesivo puede reducir síntomas.",
        intervenciones: ["Ropa holgada", "Evitar duchas muy calientes", "Registrar posibles desencadenantes"],
        nivelEvidencia: "moderada",
      },
    },
  },
  {
    id: "psoriasis-compatible",
    nombre: "Psoriasis compatible",
    descripcion:
      "Placas rojas bien delimitadas con descamación, especialmente en codos, rodillas, cuero cabelludo o zona lumbar, pueden ser compatibles con psoriasis. Requiere confirmación clínica porque otras dermatosis pueden parecerse.",
    sintomas: [
      { nombre: "Descamación", peso: 3 },
      { nombre: "Enrojecimiento", peso: 2 },
      { nombre: "Picor", peso: 1 },
      { nombre: "Placas en la piel", peso: 3 },
      { nombre: "Dolor articular", peso: 1 },
    ],
    sintomasAlarma: [
      { nombre: "Fiebre", gravedad: "alta" },
      { nombre: "Enrojecimiento casi generalizado", gravedad: "alta" },
      { nombre: "Dolor articular intenso", gravedad: "alta" },
    ],
    sintomasQueContradicen: [
      { nombre: "Ronchas", peso: 2 },
      { nombre: "Ampollas agrupadas", peso: 2 },
    ],
    preguntas: [
      { texto: "¿Hay placas rojas con escamas que persisten en las mismas zonas?", importancia: 2 },
      { texto: "¿También existe dolor, rigidez o inflamación articular?", importancia: 3 },
    ],
    posiblesCausas: ["Psoriasis en placas", "Otras dermatosis descamativas"],
    factoresRiesgo: ["Antecedentes familiares", "Tabaquismo", "Obesidad", "Estrés", "Algunos medicamentos"],
    nutricion: [
      "Si existe exceso de peso, su reducción puede mejorar salud general y respuesta al tratamiento",
      "No existe una dieta única que sustituya el tratamiento dermatológico",
    ],
    fitoterapia: ["Evitar productos tópicos irritantes sobre placas activas", "Revisar suplementos por posibles interacciones con tratamientos sistémicos"],
    recomendaciones: ["Hidratar la piel", "Evitar traumatismos repetidos", "Consultar si hay afectación articular"],
    nivelEvidencia: "alta",
    contraindicaciones: ["No suspender tratamientos sistémicos de forma brusca sin indicación médica"],
    interacciones: ["Los tratamientos sistémicos para psoriasis pueden tener interacciones relevantes; revisar cualquier suplemento"],
    pruebasMedicasHabituales: ["Exploración dermatológica", "Valoración articular si hay síntomas", "Analíticas según tratamiento"],
    especialistaRecomendado: ["Dermatología", "Reumatología si se sospecha artritis psoriásica", "Atención Primaria"],
    cuandoAcudirMedico: ["Extensión rápida", "Fiebre", "Dolor articular persistente", "Afectación importante de uñas o articulaciones"],
    bibliografia: ["Guías clínicas de psoriasis y artritis psoriásica"],
    enfoques: {
      convencional: {
        titulo: "Medicina convencional",
        marco: "Clasifica gravedad, extensión y posible afectación articular para elegir tratamiento tópico, fototerapia o tratamiento sistémico.",
        intervenciones: ["Tratamientos tópicos", "Fototerapia", "Fármacos sistémicos o biológicos según gravedad"],
        nivelEvidencia: "alta",
      },
      nutricion: {
        titulo: "Nutrición",
        marco: "El control del peso y del riesgo cardiometabólico forma parte del manejo integral.",
        intervenciones: ["Patrón alimentario saludable", "Reducción de peso si existe obesidad"],
        nivelEvidencia: "moderada",
      },
      natural: {
        titulo: "Fitoterapia y medicina natural",
        marco: "Puede aportar medidas complementarias de cuidado de piel, pero la evidencia para sustituir tratamientos es insuficiente.",
        intervenciones: ["Emolientes bien tolerados", "Evitar productos irritantes"],
        nivelEvidencia: "limitada",
      },
      medicinaChina: {
        titulo: "Medicina tradicional china",
        marco: "Se ha estudiado como complemento en algunos contextos, con evidencia heterogénea.",
        intervenciones: ["Solo complemento con supervisión y productos controlados"],
        nivelEvidencia: "tradicional",
      },
      estiloVida: {
        titulo: "Estilo de vida",
        marco: "Controlar tabaco, alcohol, peso y estrés puede mejorar salud general y algunos desencadenantes.",
        intervenciones: ["No fumar", "Actividad física", "Control de peso", "Manejo del estrés"],
        nivelEvidencia: "moderada",
      },
    },
  },
  {
    id: "infeccion-cutanea-compatible",
    nombre: "Infección cutánea compatible",
    descripcion:
      "Una zona de piel cada vez más roja, caliente, dolorosa o hinchada, especialmente si se extiende o aparece fiebre, puede ser compatible con una infección cutánea y necesita valoración médica.",
    sintomas: [
      { nombre: "Enrojecimiento", peso: 2 },
      { nombre: "Calor local", peso: 2 },
      { nombre: "Dolor en la piel", peso: 2 },
      { nombre: "Hinchazón", peso: 2 },
      { nombre: "Supuración", peso: 3 },
      { nombre: "Fiebre", peso: 2 },
    ],
    sintomasAlarma: [
      { nombre: "Fiebre", gravedad: "alta" },
      { nombre: "Enrojecimiento que avanza rápidamente", gravedad: "urgente" },
      { nombre: "Dolor intenso en la piel", gravedad: "urgente" },
      { nombre: "Confusión", gravedad: "urgente" },
      { nombre: "Líneas rojas que ascienden por la extremidad", gravedad: "alta" },
    ],
    sintomasQueContradicen: [
      { nombre: "Ronchas", peso: 1 },
      { nombre: "Sequedad de piel", peso: 1 },
    ],
    preguntas: [
      { texto: "¿La zona está caliente, dolorosa y cada vez más roja o hinchada?", importancia: 3 },
      { texto: "¿Hay pus, herida, picadura o puerta de entrada?", importancia: 2 },
      { texto: "¿El enrojecimiento se extiende rápidamente o hay fiebre?", importancia: 3 },
    ],
    posiblesCausas: ["Celulitis bacteriana", "Absceso", "Infección de una herida", "Foliculitis u otras infecciones cutáneas"],
    factoresRiesgo: ["Diabetes", "Mala circulación", "Heridas", "Edema crónico", "Inmunosupresión"],
    nutricion: ["Mantener hidratación y alimentación adecuada durante una infección"],
    fitoterapia: ["No aplicar preparados herbales sobre una infección profunda o una herida abierta sin valoración"],
    recomendaciones: [
      "Mantener limpia la zona",
      "No exprimir abscesos",
      "Marcar el borde del enrojecimiento puede ayudar a observar si progresa mientras se busca atención",
    ],
    nivelEvidencia: "alta",
    contraindicaciones: ["No retrasar antibióticos o drenaje cuando estén indicados"],
    interacciones: ["Revisar suplementos si se prescribe tratamiento antibiótico o anticoagulante"],
    pruebasMedicasHabituales: ["Exploración", "Cultivo si existe pus en casos seleccionados", "Analítica si hay afectación sistémica"],
    especialistaRecomendado: ["Atención Primaria", "Urgencias", "Cirugía si requiere drenaje"],
    cuandoAcudirMedico: [
      "Fiebre",
      "Extensión rápida",
      "Dolor intenso",
      "Afectación de cara u ojos",
      "Diabetes o inmunosupresión con infección cutánea",
    ],
    bibliografia: ["Guías de infecciones de piel y tejidos blandos"],
    enfoques: {
      convencional: {
        titulo: "Medicina convencional",
        marco: "Diferencia celulitis, absceso y otras causas para decidir antibióticos, drenaje o pruebas.",
        intervenciones: ["Antibióticos cuando están indicados", "Drenaje de absceso", "Control de complicaciones"],
        nivelEvidencia: "alta",
      },
      nutricion: {
        titulo: "Nutrición",
        marco: "La nutrición adecuada apoya la recuperación, pero no trata por sí sola una infección bacteriana.",
        intervenciones: ["Hidratación", "Ingesta suficiente de energía y proteína"],
        nivelEvidencia: "moderada",
      },
      natural: {
        titulo: "Fitoterapia y medicina natural",
        marco: "No debe sustituir antibióticos o drenaje si hay una infección profunda.",
        intervenciones: ["Cuidados locales no irritantes", "Evitar productos contaminantes o cáusticos"],
        nivelEvidencia: "limitada",
      },
      medicinaChina: {
        titulo: "Medicina tradicional china",
        marco: "No debe retrasar el tratamiento convencional de una infección que progresa.",
        intervenciones: ["Solo complemento después de la valoración médica"],
        nivelEvidencia: "tradicional",
      },
      estiloVida: {
        titulo: "Estilo de vida",
        marco: "La higiene de heridas y el control de enfermedades predisponentes reducen riesgo.",
        intervenciones: ["Cuidado correcto de heridas", "Control de glucosa en diabetes", "No manipular lesiones"],
        nivelEvidencia: "alta",
      },
    },
  },
  {
    id: "herpes-zoster-compatible",
    nombre: "Herpes zóster compatible",
    descripcion:
      "Dolor, ardor u hormigueo seguido de ampollas agrupadas en una franja localizada, habitualmente en un solo lado del cuerpo o de la cara, puede ser compatible con herpes zóster. El tratamiento temprano puede ser importante.",
    sintomas: [
      { nombre: "Ampollas agrupadas", peso: 3 },
      { nombre: "Dolor en la piel", peso: 2 },
      { nombre: "Hormigueo", peso: 1 },
      { nombre: "Ardor en la piel", peso: 2 },
      { nombre: "Erupción", peso: 1 },
    ],
    sintomasAlarma: [
      { nombre: "Erupción cerca del ojo", gravedad: "urgente" },
      { nombre: "Visión borrosa", gravedad: "urgente" },
      { nombre: "Debilidad facial", gravedad: "alta" },
      { nombre: "Fiebre", gravedad: "alta" },
      { nombre: "Erupción muy extendida", gravedad: "alta" },
    ],
    sintomasQueContradicen: [
      { nombre: "Ronchas", peso: 2 },
      { nombre: "Sequedad de piel", peso: 1 },
    ],
    preguntas: [
      { texto: "¿Las ampollas y el dolor están concentrados en una franja de un solo lado?", importancia: 3 },
      { texto: "¿Las lesiones afectan a la frente, nariz o zona cercana al ojo?", importancia: 3 },
      { texto: "¿Han comenzado en los últimos pocos días?", importancia: 2 },
    ],
    posiblesCausas: ["Reactivación del virus varicela-zóster"],
    factoresRiesgo: ["Edad avanzada", "Inmunosupresión", "Antecedente de varicela"],
    nutricion: ["Mantener alimentación e hidratación suficientes"],
    fitoterapia: ["No aplicar aceites esenciales o sustancias irritantes sobre vesículas", "No sustituir antivirales por preparados naturales"],
    recomendaciones: [
      "Consultar pronto para valorar tratamiento antiviral",
      "Mantener las lesiones limpias y cubiertas cuando sea posible",
      "Evitar contacto directo de las lesiones con embarazadas no inmunes, recién nacidos o personas inmunodeprimidas",
    ],
    nivelEvidencia: "alta",
    contraindicaciones: ["No retrasar valoración si afecta cara u ojo"],
    interacciones: ["Revisar medicación habitual si se indican antivirales o analgésicos"],
    pruebasMedicasHabituales: ["Diagnóstico clínico", "Pruebas virológicas si la presentación es atípica"],
    especialistaRecomendado: ["Atención Primaria", "Urgencias u Oftalmología si afecta el ojo", "Dermatología en casos dudosos"],
    cuandoAcudirMedico: [
      "Lesiones cerca del ojo",
      "Cambios de visión",
      "Debilidad facial",
      "Inmunosupresión",
      "Erupción extensa",
      "Dolor intenso",
    ],
    bibliografia: ["Guías clínicas sobre herpes zóster"],
    enfoques: {
      convencional: {
        titulo: "Medicina convencional",
        marco: "Valora antivirales tempranos, control del dolor y afectación ocular o neurológica.",
        intervenciones: ["Antivirales cuando están indicados", "Control del dolor", "Valoración ocular urgente si procede"],
        nivelEvidencia: "alta",
      },
      nutricion: {
        titulo: "Nutrición",
        marco: "No existe una intervención nutricional que sustituya el tratamiento antiviral cuando está indicado.",
        intervenciones: ["Mantener ingesta adecuada", "Evitar restricciones innecesarias"],
        nivelEvidencia: "moderada",
      },
      natural: {
        titulo: "Fitoterapia y medicina natural",
        marco: "Las medidas naturales solo pueden ser complementarias y no deben irritar las lesiones.",
        intervenciones: ["Compresas frescas si alivian", "Evitar sustancias irritantes"],
        nivelEvidencia: "limitada",
      },
      medicinaChina: {
        titulo: "Medicina tradicional china",
        marco: "Puede utilizar enfoques tradicionales para dolor, pero no debe retrasar antivirales ni valoración ocular.",
        intervenciones: ["Solo complemento después de valoración médica"],
        nivelEvidencia: "tradicional",
      },
      estiloVida: {
        titulo: "Estilo de vida",
        marco: "El cuidado de las lesiones y la prevención de transmisión son importantes mientras existan vesículas activas.",
        intervenciones: ["Cubrir lesiones", "Lavado de manos", "Descanso"],
        nivelEvidencia: "alta",
      },
    },
  },
];