import type { Condicion } from "./condiciones";

const noMostrado = { titulo: "No mostrado", marco: "Módulo no utilizado en la interfaz actual.", intervenciones: [], nivelEvidencia: "tradicional" as const };

export const condicionesInfecciosas: Condicion[] = [
  {
    id: "infeccion-respiratoria-alta-compatible", nombre: "Infección respiratoria alta compatible",
    descripcion: "Congestión, mucosidad, dolor de garganta, tos y malestar pueden ser compatibles con una infección respiratoria alta, con frecuencia viral. Los síntomas aislados no permiten identificar con seguridad el microorganismo.",
    sintomas: [{ nombre: "Congestión nasal", peso: 2 },{ nombre: "Mucosidad", peso: 2 },{ nombre: "Dolor de garganta", peso: 2 },{ nombre: "Tos seca", peso: 1 },{ nombre: "Tos con mucosidad", peso: 1 },{ nombre: "Fiebre", peso: 1 },{ nombre: "Cansancio", peso: 1 }],
    sintomasAlarma: [{ nombre: "Falta de aire intensa", gravedad: "urgente" },{ nombre: "Labios azulados", gravedad: "urgente" },{ nombre: "Confusión", gravedad: "urgente" }], sintomasQueContradicen: [],
    preguntas: [{ texto: "¿Desde cuándo tienes los síntomas y están mejorando o empeorando?", importancia: 2 },{ texto: "¿Hay dificultad respiratoria, dolor torácico o fiebre persistente?", importancia: 3 }],
    posiblesCausas: ["Virus respiratorios", "Otras infecciones respiratorias", "Rinitis no infecciosa"], factoresRiesgo: ["Edad avanzada", "Enfermedad respiratoria crónica", "Inmunosupresión"],
    nutricion: ["Mantener hidratación y alimentación según tolerancia"], fitoterapia: ["Algunos preparados pueden aliviar síntomas, pero no sustituyen valoración ante señales de alarma"], recomendaciones: ["Descanso e hidratación", "Valorar pruebas o consulta según contexto epidemiológico, duración y gravedad"], nivelEvidencia: "alta",
    contraindicaciones: ["No usar antibióticos sobrantes ni asumir que toda mucosidad requiere antibiótico"], interacciones: ["Revisar descongestionantes y productos combinados si existe hipertensión o se toman otros medicamentos"], pruebasMedicasHabituales: ["Exploración", "Pruebas microbiológicas cuando están indicadas"], especialistaRecomendado: ["Atención Primaria", "Urgencias si hay dificultad respiratoria grave"], cuandoAcudirMedico: ["Falta de aire", "Dolor torácico importante", "Confusión", "Empeoramiento marcado o persistente"], bibliografia: ["Guías clínicas de infecciones respiratorias agudas"],
    enfoques: { convencional: { titulo: "Medicina convencional", marco: "El tratamiento depende de la causa y gravedad; muchas infecciones altas son virales.", intervenciones: ["Tratamiento sintomático", "Antibióticos solo cuando están indicados"], nivelEvidencia: "alta" }, nutricion: { titulo: "Nutrición", marco: "La prioridad es mantener hidratación y una ingesta tolerable.", intervenciones: ["Líquidos", "Alimentación según apetito"], nivelEvidencia: "moderada" }, natural: { titulo: "Fitoterapia y suplementación", marco: "Puede ser complementaria para algunos síntomas, revisando evidencia, dosis e interacciones.", intervenciones: ["No sustituir atención médica ante señales de alarma"], nivelEvidencia: "moderada" }, medicinaChina: noMostrado, estiloVida: { titulo: "Cuidados", marco: "Descanso, higiene y ventilación ayudan al manejo y a reducir transmisión.", intervenciones: ["Descanso", "Lavado de manos", "Ventilación"], nivelEvidencia: "alta" } }
  },
  {
    id: "gastroenteritis-aguda-compatible", nombre: "Gastroenteritis aguda compatible",
    descripcion: "Diarrea, náuseas, vómitos y dolor abdominal de inicio reciente pueden ser compatibles con gastroenteritis. La principal complicación es la deshidratación.",
    sintomas: [{ nombre: "Diarrea continua", peso: 3 },{ nombre: "Heces líquidas", peso: 2 },{ nombre: "Náuseas", peso: 1 },{ nombre: "Vómitos", peso: 2 },{ nombre: "Dolor abdominal", peso: 1 },{ nombre: "Fiebre", peso: 1 }],
    sintomasAlarma: [{ nombre: "Sangre roja en las heces", gravedad: "alta" },{ nombre: "Confusión", gravedad: "urgente" },{ nombre: "Desmayo", gravedad: "urgente" },{ nombre: "Orinar muy poca cantidad", gravedad: "alta" }], sintomasQueContradicen: [],
    preguntas: [{ texto: "¿Puedes mantener líquidos sin vomitarlos?", importancia: 3 },{ texto: "¿Hay sangre en las heces, fiebre alta o dolor abdominal intenso?", importancia: 3 }],
    posiblesCausas: ["Virus", "Bacterias", "Toxinas alimentarias", "Otras causas digestivas"], factoresRiesgo: ["Edad avanzada", "Inmunosupresión", "Viajes", "Alimentos o agua contaminados"],
    nutricion: ["Priorizar rehidratación oral", "Reintroducir alimentación según tolerancia"], fitoterapia: ["Evitar productos laxantes; no retrasar valoración si hay sangre, deshidratación o deterioro"], recomendaciones: ["Vigilar hidratación y cantidad de orina", "Higiene de manos para reducir contagio"], nivelEvidencia: "alta",
    contraindicaciones: ["No usar antidiarreicos a ciegas si hay sangre o fiebre importante"], interacciones: ["Vómitos y diarrea pueden alterar la absorción y seguridad de medicamentos habituales"], pruebasMedicasHabituales: ["Exploración", "Analítica o estudio de heces en casos seleccionados"], especialistaRecomendado: ["Atención Primaria", "Urgencias si hay deshidratación grave"], cuandoAcudirMedico: ["No poder retener líquidos", "Sangre en heces", "Orina muy escasa", "Desmayo o confusión"], bibliografia: ["Guías clínicas de diarrea aguda y rehidratación"],
    enfoques: { convencional: { titulo: "Medicina convencional", marco: "La rehidratación es el tratamiento fundamental; otras medidas dependen de la causa.", intervenciones: ["Rehidratación oral", "Tratamiento dirigido cuando procede"], nivelEvidencia: "alta" }, nutricion: { titulo: "Nutrición", marco: "La reposición de agua y electrolitos es prioritaria.", intervenciones: ["Solución de rehidratación oral cuando corresponda", "Alimentación progresiva"], nivelEvidencia: "alta" }, natural: { titulo: "Fitoterapia y suplementación", marco: "Debe evitarse cualquier producto que empeore pérdidas o retrase la atención.", intervenciones: ["No usar laxantes ni mezclas irritantes"], nivelEvidencia: "alta" }, medicinaChina: noMostrado, estiloVida: { titulo: "Cuidados", marco: "Higiene y descanso ayudan a limitar transmisión y recuperación.", intervenciones: ["Lavado de manos", "Descanso"], nivelEvidencia: "alta" } }
  },
  {
    id: "sepsis-posible", nombre: "Infección grave / sepsis posible",
    descripcion: "Una infección acompañada de confusión, dificultad respiratoria marcada, desmayo o deterioro general intenso puede ser una emergencia. La app no debe intentar manejar estos cuadros únicamente con autocuidados.",
    sintomas: [{ nombre: "Fiebre", peso: 2 },{ nombre: "Escalofríos", peso: 2 },{ nombre: "Confusión", peso: 5 },{ nombre: "Falta de aire intensa", peso: 5 },{ nombre: "Desmayo", peso: 5 },{ nombre: "Debilidad", peso: 1 }],
    sintomasAlarma: [{ nombre: "Confusión", gravedad: "urgente" },{ nombre: "Falta de aire intensa", gravedad: "urgente" },{ nombre: "Desmayo", gravedad: "urgente" },{ nombre: "Labios azulados", gravedad: "urgente" }], sintomasQueContradicen: [],
    preguntas: [{ texto: "¿Existe una infección conocida o sospechada y un empeoramiento rápido?", importancia: 3 }],
    posiblesCausas: ["Infección bacteriana grave", "Infección viral grave", "Otras infecciones sistémicas"], factoresRiesgo: ["Edad avanzada", "Inmunosupresión", "Enfermedad crónica", "Infección reciente"],
    nutricion: [], fitoterapia: ["No usar fitoterapia como sustitución de atención urgente"], recomendaciones: ["Solicitar atención de emergencias si existe deterioro grave"], nivelEvidencia: "alta",
    contraindicaciones: ["No retrasar atención urgente"], interacciones: [], pruebasMedicasHabituales: ["Evaluación urgente, constantes, analítica, cultivos y pruebas dirigidas"], especialistaRecomendado: ["Urgencias"], cuandoAcudirMedico: ["Inmediatamente ante confusión, desmayo, dificultad respiratoria marcada o deterioro rápido"], bibliografia: ["Guías clínicas de sepsis"],
    enfoques: { convencional: { titulo: "Emergencias", marco: "La sospecha de sepsis requiere evaluación y tratamiento hospitalario rápidos.", intervenciones: ["Valoración urgente", "Tratamiento de soporte y antimicrobiano cuando corresponde"], nivelEvidencia: "alta" }, nutricion: { titulo: "Nutrición", marco: "No es el tratamiento del episodio agudo.", intervenciones: [], nivelEvidencia: "alta" }, natural: { titulo: "Fitoterapia y suplementación", marco: "No tiene papel como sustituto del tratamiento urgente.", intervenciones: [], nivelEvidencia: "alta" }, medicinaChina: noMostrado, estiloVida: { titulo: "Prevención", marco: "Vacunación indicada, higiene y control de enfermedades crónicas reducen algunos riesgos infecciosos.", intervenciones: ["Prevención y atención temprana de infecciones"], nivelEvidencia: "alta" } }
  }
];