import type { Condicion } from "./condiciones";

export const condicionesUrinarias: Condicion[] = [
  {
    id: "cistitis",
    nombre: "Cistitis / infección urinaria baja compatible",
    descripcion:
      "Cuadro compatible con infección urinaria baja cuando predominan escozor o dolor al orinar, urgencia y aumento de frecuencia sin señales de afectación general o renal.",
    sintomas: [
      { nombre: "Dolor al orinar", peso: 3 },
      { nombre: "Urgencia para orinar", peso: 2 },
      { nombre: "Orinar con mucha frecuencia", peso: 2 },
      { nombre: "Orina turbia", peso: 1 },
      { nombre: "Olor fuerte", peso: 1 },
    ],
    sintomasAlarma: [
      { nombre: "Fiebre", gravedad: "alta" },
      { nombre: "Dolor lumbar", gravedad: "alta" },
      { nombre: "Sangre en la orina", gravedad: "alta" },
      { nombre: "Vómitos", gravedad: "alta" },
    ],
    sintomasQueContradicen: [],
    preguntas: [
      { texto: "¿Tienes fiebre o dolor en la zona lumbar?", importancia: 3 },
      { texto: "¿Has visto sangre en la orina?", importancia: 3 },
      { texto: "¿Los síntomas son nuevos o recurrentes?", importancia: 2 },
    ],
    posiblesCausas: ["Infección bacteriana urinaria baja", "Irritación urinaria de otra causa"],
    factoresRiesgo: ["Antecedentes de infecciones urinarias", "Actividad sexual", "Alteraciones urológicas"],
    nutricion: ["Mantener hidratación adecuada salvo restricción médica"],
    fitoterapia: ["No utilizar plantas como sustituto de antibióticos cuando existe infección bacteriana que requiere tratamiento"],
    recomendaciones: ["Consultar si los síntomas son intensos, recurrentes o no mejoran", "No retrasar valoración si aparece fiebre o dolor lumbar"],
    nivelEvidencia: "alta",
    contraindicaciones: ["No tratar como cistitis simple si existe fiebre, dolor lumbar, embarazo, inmunosupresión o deterioro general"],
    interacciones: ["Revisar productos diuréticos o irritantes urinarios si se utilizan suplementos"],
    pruebasMedicasHabituales: ["Tira reactiva o análisis de orina", "Urocultivo en situaciones seleccionadas"],
    especialistaRecomendado: ["Atención Primaria", "Urgencias si hay deterioro o sospecha de infección alta"],
    cuandoAcudirMedico: ["Fiebre", "Dolor lumbar", "Vómitos", "Sangre visible en orina", "Empeoramiento o recurrencia"],
    bibliografia: ["Guías sobre infección urinaria baja"],
    enfoques: {
      convencional: {
        titulo: "Medicina convencional",
        marco: "Distingue infección urinaria baja de afectación renal y decide si son necesarias pruebas y antibióticos.",
        intervenciones: ["Análisis de orina cuando procede", "Antibiótico si está indicado", "Reevaluación si persiste o recurre"],
        nivelEvidencia: "alta",
      },
      nutricion: {
        titulo: "Nutrición",
        marco: "La hidratación adecuada puede ser útil como medida de apoyo, pero no sustituye el tratamiento cuando existe infección.",
        intervenciones: ["Mantener hidratación suficiente salvo contraindicación"],
        nivelEvidencia: "moderada",
      },
      natural: {
        titulo: "Fitoterapia y medicina natural",
        marco: "Algunos recursos se han estudiado sobre todo en prevención de recurrencias, no como sustitutos del tratamiento de una infección activa complicada.",
        intervenciones: ["Valorar arándano en prevención de recurrencias en perfiles seleccionados", "Evitar mezclas diuréticas si hay dolor, fiebre o sospecha de obstrucción"],
        nivelEvidencia: "moderada",
        nota: "En infección activa con señales de alarma, la prioridad es médica.",
      },
      medicinaChina: {
        titulo: "Medicina tradicional china",
        marco: "Puede clasificar síntomas urinarios mediante patrones tradicionales propios.",
        intervenciones: ["Uso complementario solo tras descartar complicaciones y sin sustituir tratamiento indicado"],
        nivelEvidencia: "tradicional",
      },
      estiloVida: {
        titulo: "Estilo de vida",
        marco: "Algunos hábitos pueden reducir recurrencias en determinadas personas.",
        intervenciones: ["No retrasar la micción", "Mantener hidratación", "Revisar factores desencadenantes recurrentes"],
        nivelEvidencia: "moderada",
      },
    },
  },
  {
    id: "pielonefritis",
    nombre: "Infección urinaria alta / pielonefritis compatible",
    descripcion:
      "La combinación de fiebre, dolor lumbar o en el costado, síntomas urinarios y mal estado general puede ser compatible con infección renal y requiere valoración médica.",
    sintomas: [
      { nombre: "Fiebre", peso: 2 },
      { nombre: "Dolor lumbar", peso: 2 },
      { nombre: "Dolor en el costado", peso: 3 },
      { nombre: "Dolor al orinar", peso: 1 },
      { nombre: "Náuseas", peso: 1 },
      { nombre: "Vómitos", peso: 1 },
    ],
    sintomasAlarma: [
      { nombre: "Confusión", gravedad: "urgente" },
      { nombre: "Vómitos repetidos", gravedad: "alta" },
      { nombre: "Orinar muy poca cantidad", gravedad: "alta" },
    ],
    sintomasQueContradicen: [],
    preguntas: [
      { texto: "¿Hay fiebre y dolor en un costado o zona lumbar?", importancia: 3 },
      { texto: "¿Puedes beber y retener líquidos?", importancia: 3 },
    ],
    posiblesCausas: ["Infección bacteriana del tracto urinario superior"],
    factoresRiesgo: ["Infección urinaria previa", "Obstrucción urinaria", "Litiasis", "Embarazo", "Diabetes o inmunosupresión"],
    nutricion: ["Mantener hidratación si se tolera y no existe restricción médica"],
    fitoterapia: ["No tratar una posible pielonefritis únicamente con plantas o suplementos"],
    recomendaciones: ["Buscar valoración médica", "Vigilar hidratación y deterioro general"],
    nivelEvidencia: "alta",
    contraindicaciones: ["No retrasar atención médica por intentar medidas naturales"],
    interacciones: ["Revisar medicación renal y suplementos si existe deterioro de función renal"],
    pruebasMedicasHabituales: ["Análisis de orina", "Urocultivo", "Analítica sanguínea", "Imagen si se sospecha obstrucción o complicación"],
    especialistaRecomendado: ["Atención Primaria o Urgencias", "Urología según complicaciones"],
    cuandoAcudirMedico: ["Fiebre con dolor lumbar o costado", "Vómitos", "Confusión", "Reducción importante de orina"],
    bibliografia: ["Guías sobre pielonefritis e infección urinaria complicada"],
    enfoques: {
      convencional: {
        titulo: "Medicina convencional",
        marco: "Considera la pielonefritis una infección que requiere evaluación y, habitualmente, tratamiento antibiótico.",
        intervenciones: ["Antibiótico según contexto", "Urocultivo", "Valorar ingreso o imagen si hay complicaciones"],
        nivelEvidencia: "alta",
      },
      nutricion: {
        titulo: "Nutrición",
        marco: "La hidratación es de apoyo y debe adaptarse a tolerancia y situación clínica.",
        intervenciones: ["Líquidos según tolerancia y recomendaciones médicas"],
        nivelEvidencia: "moderada",
      },
      natural: {
        titulo: "Fitoterapia y medicina natural",
        marco: "No es un cuadro para tratar exclusivamente con fitoterapia.",
        intervenciones: ["No retrasar antibióticos o valoración cuando están indicados"],
        nivelEvidencia: "limitada",
      },
      medicinaChina: {
        titulo: "Medicina tradicional china",
        marco: "Puede ofrecer apoyo complementario, pero no sustituye el tratamiento de una infección renal.",
        intervenciones: ["Solo complemento tras valoración médica"],
        nivelEvidencia: "tradicional",
      },
      estiloVida: {
        titulo: "Estilo de vida",
        marco: "El descanso y la hidratación acompañan al tratamiento, pero la prioridad es resolver la infección.",
        intervenciones: ["Descanso", "Cumplir tratamiento prescrito", "Vigilar empeoramiento"],
        nivelEvidencia: "moderada",
      },
    },
  },
  {
    id: "colico-renal",
    nombre: "Cólico renal / litiasis compatible",
    descripcion:
      "Dolor intenso en un costado o zona lumbar que puede irradiar hacia la ingle y acompañarse de náuseas o sangre en orina puede ser compatible con litiasis urinaria.",
    sintomas: [
      { nombre: "Dolor en el costado", peso: 3 },
      { nombre: "Dolor lumbar intenso", peso: 3 },
      { nombre: "Dolor hacia la ingle", peso: 2 },
      { nombre: "Sangre en la orina", peso: 2 },
      { nombre: "Náuseas", peso: 1 },
    ],
    sintomasAlarma: [
      { nombre: "Fiebre", gravedad: "urgente" },
      { nombre: "Orinar muy poca cantidad", gravedad: "alta" },
      { nombre: "Vómitos repetidos", gravedad: "alta" },
      { nombre: "Confusión", gravedad: "urgente" },
    ],
    sintomasQueContradicen: [],
    preguntas: [
      { texto: "¿El dolor baja hacia la ingle?", importancia: 2 },
      { texto: "¿Hay fiebre o disminución marcada de la orina?", importancia: 3 },
    ],
    posiblesCausas: ["Cálculo renal o ureteral", "Otras causas de dolor lumbar o abdominal"],
    factoresRiesgo: ["Antecedentes de litiasis", "Baja ingesta de líquidos", "Algunos trastornos metabólicos"],
    nutricion: ["La prevención dietética depende del tipo de cálculo y antecedentes"],
    fitoterapia: ["No utilizar diuréticos herbales si existe sospecha de obstrucción o dolor intenso sin valoración"],
    recomendaciones: ["Consultar para confirmar diagnóstico y valorar tamaño/localización del cálculo", "Buscar atención urgente si hay fiebre o anuria"],
    nivelEvidencia: "alta",
    contraindicaciones: ["No forzar líquidos de forma indiscriminada durante dolor intenso con posible obstrucción"],
    interacciones: ["Revisar suplementos minerales y fármacos según tipo de litiasis"],
    pruebasMedicasHabituales: ["Análisis de orina", "Analítica", "Ecografía o TC según contexto"],
    especialistaRecomendado: ["Urgencias o Atención Primaria según intensidad", "Urología según tamaño, obstrucción o recurrencia"],
    cuandoAcudirMedico: ["Fiebre", "Dolor incontrolable", "Vómitos persistentes", "Orinar muy poco o nada"],
    bibliografia: ["Guías sobre litiasis urinaria"],
    enfoques: {
      convencional: {
        titulo: "Medicina convencional",
        marco: "Confirma la litiasis, controla el dolor y descarta infección u obstrucción significativa.",
        intervenciones: ["Analgesia", "Imagen según necesidad", "Tratamiento expulsivo o urológico en casos seleccionados"],
        nivelEvidencia: "alta",
      },
      nutricion: {
        titulo: "Nutrición",
        marco: "La prevención se individualiza según composición del cálculo y factores metabólicos.",
        intervenciones: ["Hidratación preventiva adecuada", "Ajustes dietéticos según tipo de cálculo"],
        nivelEvidencia: "alta",
      },
      natural: {
        titulo: "Fitoterapia y medicina natural",
        marco: "No hay que intentar forzar la expulsión con diuréticos herbales si existe obstrucción o complicación.",
        intervenciones: ["Priorizar diagnóstico y control del dolor", "Valorar apoyos solo en prevención y con contexto clínico"],
        nivelEvidencia: "limitada",
      },
      medicinaChina: {
        titulo: "Medicina tradicional china",
        marco: "Puede abordar dolor y síntomas urinarios mediante patrones tradicionales, pero no sustituye imagen ni valoración urológica cuando está indicada.",
        intervenciones: ["Uso complementario tras descartar obstrucción e infección"],
        nivelEvidencia: "tradicional",
      },
      estiloVida: {
        titulo: "Estilo de vida",
        marco: "La prevención se apoya en hidratación y hábitos dietéticos adaptados al riesgo de recurrencia.",
        intervenciones: ["Mantener hidratación regular", "Reducir factores dietéticos de riesgo según estudio"],
        nivelEvidencia: "alta",
      },
    },
  },
  {
    id: "sintomas-urinarios-bajos",
    nombre: "Síntomas urinarios bajos compatibles",
    descripcion:
      "Frecuencia, urgencia, nocturia, chorro débil o dificultad para iniciar la micción pueden deberse a múltiples causas vesicales, prostáticas, metabólicas o farmacológicas.",
    sintomas: [
      { nombre: "Orinar con mucha frecuencia", peso: 2 },
      { nombre: "Levantarse por la noche a orinar", peso: 2 },
      { nombre: "Urgencia para orinar", peso: 2 },
      { nombre: "Chorro urinario débil", peso: 3 },
      { nombre: "Dificultad para empezar a orinar", peso: 2 },
      { nombre: "Sensación de vaciado incompleto", peso: 2 },
    ],
    sintomasAlarma: [
      { nombre: "Sangre en la orina", gravedad: "alta" },
      { nombre: "No puedo orinar", gravedad: "urgente" },
      { nombre: "Fiebre", gravedad: "alta" },
    ],
    sintomasQueContradicen: [],
    preguntas: [
      { texto: "¿Hay dificultad para iniciar o mantener el chorro?", importancia: 2 },
      { texto: "¿Existe sangre, fiebre o imposibilidad para orinar?", importancia: 3 },
    ],
    posiblesCausas: ["Hiperplasia prostática benigna", "Vejiga hiperactiva", "Infección urinaria", "Diabetes", "Efectos de medicación"],
    factoresRiesgo: ["Edad", "Enfermedad prostática", "Diabetes", "Medicaciones"],
    nutricion: ["Revisar cafeína y alcohol si empeoran urgencia o nocturia"],
    fitoterapia: ["No iniciar suplementos prostáticos sin descartar causas relevantes y revisar interacciones"],
    recomendaciones: ["Registrar frecuencia y patrón urinario", "Consultar si los síntomas son persistentes o progresivos"],
    nivelEvidencia: "moderada",
    contraindicaciones: ["Retención urinaria aguda requiere atención médica urgente"],
    interacciones: ["Algunos descongestionantes, antihistamínicos y otros fármacos pueden empeorar retención urinaria"],
    pruebasMedicasHabituales: ["Historia clínica", "Análisis de orina", "Exploración y pruebas urológicas según edad y contexto"],
    especialistaRecomendado: ["Atención Primaria", "Urología según hallazgos"],
    cuandoAcudirMedico: ["No poder orinar", "Sangre visible en orina", "Fiebre", "Empeoramiento progresivo"],
    bibliografia: ["Guías sobre síntomas urinarios bajos"],
    enfoques: {
      convencional: {
        titulo: "Medicina convencional",
        marco: "Busca la causa de los síntomas urinarios y diferencia vejiga, próstata, infección, causas metabólicas y efectos farmacológicos.",
        intervenciones: ["Evaluación clínica", "Tratamiento farmacológico según causa", "Derivación urológica cuando procede"],
        nivelEvidencia: "alta",
      },
      nutricion: {
        titulo: "Nutrición",
        marco: "Cafeína, alcohol y distribución de líquidos pueden influir en frecuencia y nocturia.",
        intervenciones: ["Reducir cafeína si empeora urgencia", "Ajustar líquidos nocturnos sin provocar deshidratación"],
        nivelEvidencia: "moderada",
      },
      natural: {
        titulo: "Fitoterapia y medicina natural",
        marco: "Algunos extractos se comercializan para síntomas prostáticos, pero la eficacia es variable y no sustituyen la evaluación diagnóstica.",
        intervenciones: ["Valorar suplementos solo tras conocer la causa y revisar medicación"],
        nivelEvidencia: "limitada",
      },
      medicinaChina: {
        titulo: "Medicina tradicional china",
        marco: "Interpreta frecuencia, urgencia y debilidad urinaria mediante patrones tradicionales.",
        intervenciones: ["Uso complementario, no sustitutivo de valoración urológica"],
        nivelEvidencia: "tradicional",
      },
      estiloVida: {
        titulo: "Estilo de vida",
        marco: "Horarios de líquidos, cafeína, peso y hábitos miccionales pueden modificar síntomas en algunos casos.",
        intervenciones: ["Evitar exceso de líquidos justo antes de dormir", "Reducir irritantes vesicales si existe relación", "No retrasar de forma excesiva la micción"],
        nivelEvidencia: "moderada",
      },
    },
  },
];