import type { Condicion } from "./condiciones";

export const condicionesCardioResp: Condicion[] = [
  {
    id: "palpitaciones",
    nombre: "Palpitaciones sin señales de alarma compatibles",
    descripcion:
      "Percepción incómoda o llamativa del latido cardíaco. Puede relacionarse con estrés, cafeína, falta de sueño, deshidratación o alteraciones del ritmo, por lo que conviene valorar el contexto y las señales de alarma.",
    sintomas: [
      { nombre: "Palpitaciones", peso: 3 },
      { nombre: "Latidos rápidos", peso: 2 },
      { nombre: "Latidos irregulares", peso: 2 },
      { nombre: "Ansiedad", peso: 1 },
      { nombre: "Estrés", peso: 1 },
    ],
    sintomasAlarma: [
      { nombre: "Dolor de pecho", gravedad: "urgente" },
      { nombre: "Falta de aire", gravedad: "urgente" },
      { nombre: "Desmayo", gravedad: "urgente" },
      { nombre: "Confusión", gravedad: "urgente" },
    ],
    sintomasQueContradicen: [],
    preguntas: [
      { texto: "¿Las palpitaciones son rápidas, irregulares o ambas?", importancia: 3 },
      { texto: "¿Aparecen con ejercicio, reposo, estrés o estimulantes?", importancia: 2 },
      { texto: "¿Se acompañan de dolor torácico, falta de aire o desmayo?", importancia: 3 },
    ],
    posiblesCausas: [
      "Estrés o ansiedad",
      "Cafeína, alcohol u otros estimulantes",
      "Falta de sueño o deshidratación",
      "Alteraciones del ritmo cardíaco",
      "Anemia, alteraciones tiroideas u otras causas médicas",
    ],
    factoresRiesgo: [
      "Antecedentes de cardiopatía",
      "Uso de estimulantes",
      "Alteraciones tiroideas",
      "Anemia",
    ],
    nutricion: [
      "Mantener hidratación adecuada",
      "Reducir exceso de cafeína y bebidas energéticas si existe relación temporal",
    ],
    fitoterapia: [
      "No utilizar plantas sedantes o cardiotónicas para ocultar palpitaciones de causa no aclarada",
    ],
    recomendaciones: [
      "Registrar duración, frecuencia y desencadenantes",
      "Consultar si son nuevas, persistentes o recurrentes",
    ],
    nivelEvidencia: "alta",
    contraindicaciones: [
      "Evitar automedicación con preparados que puedan alterar la frecuencia cardíaca o la presión arterial",
    ],
    interacciones: [
      "Revisar descongestionantes, estimulantes, suplementos y medicación que puedan favorecer palpitaciones",
    ],
    pruebasMedicasHabituales: [
      "Historia clínica y exploración",
      "Electrocardiograma",
      "Analítica según contexto",
      "Monitorización ambulatoria si los episodios son intermitentes",
    ],
    especialistaRecomendado: ["Atención Primaria", "Cardiología según hallazgos"],
    cuandoAcudirMedico: [
      "Dolor de pecho",
      "Falta de aire importante",
      "Desmayo o casi desmayo",
      "Palpitaciones persistentes con deterioro general",
    ],
    bibliografia: ["Guías clínicas sobre palpitaciones y arritmias"],
    enfoques: {
      convencional: {
        titulo: "Medicina convencional",
        marco:
          "Busca distinguir desencadenantes benignos de arritmias u otras causas médicas mediante historia, exploración y ECG cuando procede.",
        intervenciones: [
          "ECG y pruebas dirigidas según el patrón",
          "Tratar la causa identificada",
          "Derivar si existen hallazgos de riesgo",
        ],
        nivelEvidencia: "alta",
      },
      nutricion: {
        titulo: "Nutrición",
        marco:
          "Revisa hidratación y consumo de sustancias que pueden aumentar la percepción o frecuencia del latido.",
        intervenciones: [
          "Hidratación adecuada",
          "Reducir estimulantes si existe relación clara",
          "Evitar ayunos prolongados si provocan síntomas",
        ],
        nivelEvidencia: "moderada",
      },
      natural: {
        titulo: "Fitoterapia y medicina natural",
        marco:
          "No debe sustituir la evaluación de palpitaciones nuevas o persistentes.",
        intervenciones: [
          "Priorizar técnicas de relajación si el cuadro se relaciona con estrés y ya se han descartado señales de alarma",
          "Evitar preparados estimulantes o combinaciones de composición incierta",
        ],
        nivelEvidencia: "limitada",
        nota: "Las palpitaciones no deben tratarse a ciegas con plantas.",
      },
      medicinaChina: {
        titulo: "Medicina tradicional china",
        marco:
          "Puede interpretar las palpitaciones mediante patrones propios, pero no sustituye un ECG o valoración médica cuando está indicada.",
        intervenciones: ["Acupuntura o abordaje tradicional solo como complemento tras descartar causas relevantes"],
        nivelEvidencia: "tradicional",
      },
      estiloVida: {
        titulo: "Estilo de vida",
        marco:
          "Sueño, estrés, ejercicio y estimulantes pueden influir en la aparición de palpitaciones.",
        intervenciones: [
          "Dormir de forma regular",
          "Evitar exceso de estimulantes",
          "Registrar desencadenantes y duración",
        ],
        nivelEvidencia: "moderada",
      },
    },
  },
  {
    id: "mareo-ortostatico",
    nombre: "Mareo ortostático compatible",
    descripcion:
      "Sensación de mareo o casi desmayo que aparece al ponerse de pie y mejora al sentarse o tumbarse, a menudo relacionada con cambios de presión arterial, hidratación o medicación.",
    sintomas: [
      { nombre: "Aparece al levantarme", peso: 3 },
      { nombre: "Sensación de desmayo", peso: 2 },
      { nombre: "Mareo", peso: 1 },
      { nombre: "Poca hidratación", peso: 1 },
    ],
    sintomasAlarma: [
      { nombre: "Desmayo", gravedad: "alta" },
      { nombre: "Dolor de pecho", gravedad: "urgente" },
      { nombre: "Falta de aire", gravedad: "urgente" },
      { nombre: "Pérdida de fuerza", gravedad: "urgente" },
      { nombre: "Dificultad para hablar", gravedad: "urgente" },
    ],
    sintomasQueContradicen: [{ nombre: "Todo gira", peso: 2 }],
    preguntas: [
      { texto: "¿Aparece justo al incorporarte o también sentado?", importancia: 3 },
      { texto: "¿Mejora al sentarte o tumbarte?", importancia: 2 },
      { texto: "¿Has cambiado medicación o bebido menos líquidos?", importancia: 2 },
    ],
    posiblesCausas: [
      "Deshidratación",
      "Efecto de medicación",
      "Hipotensión ortostática",
      "Anemia u otras causas médicas",
    ],
    factoresRiesgo: ["Edad avanzada", "Medicaciones antihipertensivas", "Deshidratación"],
    nutricion: ["Mantener una hidratación suficiente salvo restricción médica"],
    fitoterapia: ["No utilizar estimulantes para compensar el mareo sin conocer su causa"],
    recomendaciones: ["Levantarse de forma progresiva", "Consultar si es recurrente o provoca caídas"],
    nivelEvidencia: "alta",
    contraindicaciones: ["No aumentar sal o líquidos de forma indiscriminada si existe cardiopatía o enfermedad renal"],
    interacciones: ["Revisar fármacos que puedan bajar la presión arterial"],
    pruebasMedicasHabituales: ["Presión arterial tumbado y de pie", "Revisión de medicación", "Analítica según contexto"],
    especialistaRecomendado: ["Atención Primaria", "Urgencias si hay síncope o síntomas de alarma"],
    cuandoAcudirMedico: ["Desmayo", "Dolor torácico", "Falta de aire", "Síntomas neurológicos nuevos"],
    bibliografia: ["Guías sobre síncope e hipotensión ortostática"],
    enfoques: {
      convencional: {
        titulo: "Medicina convencional",
        marco: "Valora presión arterial, medicación, hidratación y causas cardíacas o neurológicas si el cuadro lo requiere.",
        intervenciones: ["Medir presión en cambios posturales", "Revisar medicación", "Investigar causas secundarias si persiste"],
        nivelEvidencia: "alta",
      },
      nutricion: {
        titulo: "Nutrición",
        marco: "La hidratación puede ser relevante, pero debe individualizarse.",
        intervenciones: ["Mantener aporte de líquidos adecuado salvo contraindicación"],
        nivelEvidencia: "moderada",
      },
      natural: {
        titulo: "Fitoterapia y medicina natural",
        marco: "No hay una planta de elección que deba recomendarse sin conocer la causa del mareo ortostático.",
        intervenciones: ["Priorizar medidas posturales y valoración de la causa"],
        nivelEvidencia: "limitada",
      },
      medicinaChina: {
        titulo: "Medicina tradicional china",
        marco: "Puede utilizar categorías tradicionales para mareo y debilidad, pero no sustituye el estudio de síncope o hipotensión.",
        intervenciones: ["Abordaje tradicional solo como complemento"],
        nivelEvidencia: "tradicional",
      },
      estiloVida: {
        titulo: "Estilo de vida",
        marco: "Las transiciones posturales lentas y evitar calor o deshidratación pueden disminuir episodios en algunos casos.",
        intervenciones: ["Levantarse lentamente", "Evitar largos periodos de pie si desencadenan síntomas", "Prevenir deshidratación"],
        nivelEvidencia: "moderada",
      },
    },
  },
  {
    id: "resfriado-viral",
    nombre: "Infección respiratoria alta / resfriado compatible",
    descripcion:
      "Cuadro compatible con infección viral de vías respiratorias altas cuando predominan congestión nasal, mucosidad, dolor de garganta y tos sin señales de gravedad.",
    sintomas: [
      { nombre: "Congestión nasal", peso: 3 },
      { nombre: "Mucosidad", peso: 2 },
      { nombre: "Dolor de garganta", peso: 2 },
      { nombre: "Tos seca", peso: 1 },
      { nombre: "Ronquera", peso: 1 },
    ],
    sintomasAlarma: [
      { nombre: "Falta de aire", gravedad: "urgente" },
      { nombre: "Dolor de pecho", gravedad: "urgente" },
      { nombre: "Confusión", gravedad: "urgente" },
    ],
    sintomasQueContradicen: [],
    preguntas: [
      { texto: "¿Desde cuándo tienes los síntomas?", importancia: 2 },
      { texto: "¿Hay fiebre alta o dificultad respiratoria?", importancia: 3 },
    ],
    posiblesCausas: ["Infección viral respiratoria"],
    factoresRiesgo: ["Contacto con personas enfermas", "Época epidémica"],
    nutricion: ["Mantener hidratación", "Alimentación habitual según apetito"],
    fitoterapia: ["Miel en adultos y mayores de un año puede aliviar la tos", "Evitar preparados múltiples sin necesidad"],
    recomendaciones: ["Descanso", "Hidratación", "Higiene de manos"],
    nivelEvidencia: "alta",
    contraindicaciones: ["No usar miel en menores de un año"],
    interacciones: ["Revisar descongestionantes si existe hipertensión o medicación cardiovascular"],
    pruebasMedicasHabituales: ["Generalmente ninguna si el cuadro es leve", "Pruebas específicas según contexto epidemiológico o gravedad"],
    especialistaRecomendado: ["Atención Primaria si persiste o empeora"],
    cuandoAcudirMedico: ["Dificultad respiratoria", "Dolor de pecho", "Fiebre persistente con deterioro", "Síntomas prolongados o empeoramiento claro"],
    bibliografia: ["Guías sobre infecciones respiratorias altas"],
    enfoques: {
      convencional: {
        titulo: "Medicina convencional",
        marco: "Suele ser un cuadro autolimitado; el objetivo es aliviar síntomas y reconocer complicaciones.",
        intervenciones: ["Tratamiento sintomático", "No usar antibióticos de rutina en infecciones virales", "Valorar complicaciones si empeora"],
        nivelEvidencia: "alta",
      },
      nutricion: {
        titulo: "Nutrición",
        marco: "Prioriza hidratación y una dieta tolerable, sin necesidad de restricciones especiales.",
        intervenciones: ["Beber líquidos con regularidad", "Mantener ingesta según apetito"],
        nivelEvidencia: "moderada",
      },
      natural: {
        titulo: "Fitoterapia y medicina natural",
        marco: "Algunas medidas sencillas pueden aliviar síntomas, pero no acortan necesariamente la infección.",
        intervenciones: ["Miel para la tos cuando sea apropiada", "Lavados nasales con solución salina"],
        nivelEvidencia: "moderada",
      },
      medicinaChina: {
        titulo: "Medicina tradicional china",
        marco: "Clasifica los cuadros respiratorios mediante patrones tradicionales propios.",
        intervenciones: ["Puede utilizarse como complemento sintomático, no como sustituto de la valoración si aparecen signos de gravedad"],
        nivelEvidencia: "tradicional",
      },
      estiloVida: {
        titulo: "Estilo de vida",
        marco: "Descanso, hidratación y medidas de prevención ayudan a tolerar el cuadro y reducir contagios.",
        intervenciones: ["Dormir suficiente", "Lavado de manos", "Ventilar espacios"],
        nivelEvidencia: "moderada",
      },
    },
  },
  {
    id: "bronquitis-aguda",
    nombre: "Tos aguda / bronquitis aguda compatible",
    descripcion:
      "Tos de inicio reciente, seca o con mucosidad, que puede aparecer tras una infección respiratoria y que en muchos casos es viral.",
    sintomas: [
      { nombre: "Tos con mucosidad", peso: 3 },
      { nombre: "Tos seca", peso: 2 },
      { nombre: "Mucosidad", peso: 1 },
      { nombre: "Ronquera", peso: 1 },
    ],
    sintomasAlarma: [
      { nombre: "Falta de aire", gravedad: "urgente" },
      { nombre: "Dolor al respirar", gravedad: "alta" },
      { nombre: "Dolor de pecho", gravedad: "urgente" },
      { nombre: "Confusión", gravedad: "urgente" },
    ],
    sintomasQueContradicen: [],
    preguntas: [
      { texto: "¿Cuánto tiempo llevas con tos?", importancia: 3 },
      { texto: "¿Hay fiebre, falta de aire o dolor al respirar?", importancia: 3 },
    ],
    posiblesCausas: ["Infección viral respiratoria", "Irritación bronquial", "Otras causas de tos que requieren estudio si persiste"],
    factoresRiesgo: ["Tabaquismo", "Enfermedad respiratoria previa"],
    nutricion: ["Hidratación adecuada"],
    fitoterapia: ["Miel puede aliviar la tos en personas adecuadas", "Evitar aceites esenciales ingeridos sin supervisión"],
    recomendaciones: ["Descanso", "Evitar humo y tabaco", "Consultar si la tos persiste o empeora"],
    nivelEvidencia: "alta",
    contraindicaciones: ["No retrasar valoración si hay dificultad respiratoria o deterioro"],
    interacciones: ["Revisar jarabes y descongestionantes con la medicación habitual"],
    pruebasMedicasHabituales: ["Exploración respiratoria", "Radiografía si se sospecha neumonía u otra complicación"],
    especialistaRecomendado: ["Atención Primaria", "Urgencias si dificultad respiratoria importante"],
    cuandoAcudirMedico: ["Falta de aire", "Dolor torácico", "Fiebre alta persistente", "Confusión", "Tos prolongada"],
    bibliografia: ["Guías sobre tos aguda y bronquitis"],
    enfoques: {
      convencional: {
        titulo: "Medicina convencional",
        marco: "Distingue bronquitis no complicada de neumonía, asma u otras causas de tos.",
        intervenciones: ["Tratamiento sintomático", "Evitar antibióticos rutinarios cuando el cuadro es viral", "Investigar si hay signos de neumonía o persistencia"],
        nivelEvidencia: "alta",
      },
      nutricion: {
        titulo: "Nutrición",
        marco: "No existe una dieta específica; mantener líquidos puede mejorar confort y secreciones.",
        intervenciones: ["Hidratación regular"],
        nivelEvidencia: "moderada",
      },
      natural: {
        titulo: "Fitoterapia y medicina natural",
        marco: "Algunos recursos sintomáticos pueden ayudar, pero no sustituyen el diagnóstico diferencial respiratorio.",
        intervenciones: ["Miel para aliviar tos cuando sea apropiada", "Evitar humo y otros irritantes"],
        nivelEvidencia: "moderada",
      },
      medicinaChina: {
        titulo: "Medicina tradicional china",
        marco: "Interpreta tos y mucosidad mediante patrones propios.",
        intervenciones: ["Uso complementario solo si no existen signos de alarma"],
        nivelEvidencia: "tradicional",
      },
      estiloVida: {
        titulo: "Estilo de vida",
        marco: "El descanso y la reducción de irritantes favorecen la recuperación.",
        intervenciones: ["No fumar", "Descansar", "Ventilar espacios"],
        nivelEvidencia: "moderada",
      },
    },
  },
  {
    id: "asma-compatible",
    nombre: "Broncoespasmo / asma compatible",
    descripcion:
      "Episodios de silbidos, falta de aire, opresión torácica o tos que pueden ser compatibles con asma, especialmente si son variables o aparecen con ejercicio, alérgenos o infecciones.",
    sintomas: [
      { nombre: "Silbidos al respirar", peso: 3 },
      { nombre: "Falta de aire", peso: 2 },
      { nombre: "Opresión en el pecho", peso: 2 },
      { nombre: "Tos seca", peso: 1 },
    ],
    sintomasAlarma: [
      { nombre: "Falta de aire intensa", gravedad: "urgente" },
      { nombre: "No puedo hablar frases completas", gravedad: "urgente" },
      { nombre: "Labios azulados", gravedad: "urgente" },
      { nombre: "Confusión", gravedad: "urgente" },
    ],
    sintomasQueContradicen: [],
    preguntas: [
      { texto: "¿Los síntomas aparecen por episodios y luego mejoran?", importancia: 2 },
      { texto: "¿Se relacionan con ejercicio, alergias, aire frío o infecciones?", importancia: 2 },
      { texto: "¿Puedes hablar frases completas sin ahogarte?", importancia: 3 },
    ],
    posiblesCausas: ["Asma", "Broncoespasmo por infección, ejercicio o irritantes", "Otras causas respiratorias o cardíacas"],
    factoresRiesgo: ["Antecedentes de alergia", "Asma previa", "Exposición a humo o irritantes"],
    nutricion: ["No existe una dieta de rescate para una crisis asmática"],
    fitoterapia: ["No utilizar plantas o aceites esenciales como sustitutos de inhaladores prescritos"],
    recomendaciones: ["Seguir el plan de acción prescrito si existe", "Evitar desencadenantes conocidos", "Solicitar valoración para confirmar diagnóstico si no está establecido"],
    nivelEvidencia: "alta",
    contraindicaciones: ["No sustituir medicación inhalada indicada por remedios naturales"],
    interacciones: ["Revisar suplementos estimulantes o inhalados no prescritos"],
    pruebasMedicasHabituales: ["Espirometría con prueba broncodilatadora", "Medición de flujo espiratorio según contexto", "Evaluación clínica"],
    especialistaRecomendado: ["Atención Primaria", "Neumología/Alergología según caso", "Urgencias si crisis grave"],
    cuandoAcudirMedico: ["Falta de aire intensa", "Dificultad para hablar", "Coloración azulada", "Empeoramiento pese al tratamiento habitual"],
    bibliografia: ["Guías internacionales y nacionales sobre asma"],
    enfoques: {
      convencional: {
        titulo: "Medicina convencional",
        marco: "Confirma el diagnóstico con historia y pruebas funcionales y utiliza tratamiento inhalado según gravedad y control.",
        intervenciones: ["Broncodilatadores y tratamiento controlador según prescripción", "Plan de acción", "Evaluación de desencadenantes y control"],
        nivelEvidencia: "alta",
      },
      nutricion: {
        titulo: "Nutrición",
        marco: "La alimentación saludable apoya salud general, pero no sustituye el tratamiento del broncoespasmo.",
        intervenciones: ["Mantener patrón alimentario equilibrado", "Evitar alimentos solo si existe alergia confirmada"],
        nivelEvidencia: "moderada",
      },
      natural: {
        titulo: "Fitoterapia y medicina natural",
        marco: "No existe una intervención natural que deba sustituir el tratamiento inhalado de una crisis asmática.",
        intervenciones: ["Puede centrarse en evitar irritantes y técnicas respiratorias complementarias fuera de crisis"],
        nivelEvidencia: "limitada",
        nota: "En una crisis, el tratamiento médico tiene prioridad.",
      },
      medicinaChina: {
        titulo: "Medicina tradicional china",
        marco: "Puede utilizarse como complemento en síntomas crónicos seleccionados, pero no reemplaza el tratamiento estándar ni el rescate urgente.",
        intervenciones: ["Abordaje complementario fuera de crisis y con seguimiento clínico"],
        nivelEvidencia: "tradicional",
      },
      estiloVida: {
        titulo: "Estilo de vida",
        marco: "Evitar humo, conocer desencadenantes y mantener adherencia al tratamiento reduce exacerbaciones.",
        intervenciones: ["No fumar", "Reducir exposición a desencadenantes conocidos", "Mantener actividad física adaptada cuando el asma está controlada"],
        nivelEvidencia: "alta",
      },
    },
  },
  {
    id: "dolor-pared-toracica",
    nombre: "Dolor de pared torácica compatible",
    descripcion:
      "Dolor localizado en el pecho que se reproduce con movimiento, respiración profunda o presión sobre una zona concreta puede ser musculoesquelético, pero cualquier dolor torácico nuevo debe valorarse con prudencia.",
    sintomas: [
      { nombre: "Dolor de pecho", peso: 1 },
      { nombre: "Dolor de pecho al moverme", peso: 3 },
      { nombre: "Dolor de pecho al tocar", peso: 3 },
      { nombre: "Dolor al respirar", peso: 1 },
    ],
    sintomasAlarma: [
      { nombre: "Presión en el pecho", gravedad: "urgente" },
      { nombre: "Falta de aire", gravedad: "urgente" },
      { nombre: "Sudor frío", gravedad: "urgente" },
      { nombre: "Desmayo", gravedad: "urgente" },
      { nombre: "Dolor hacia brazo, espalda o mandíbula", gravedad: "urgente" },
    ],
    sintomasQueContradicen: [{ nombre: "Presión u opresión", peso: 2 }],
    preguntas: [
      { texto: "¿El dolor aparece al mover el tronco o al presionar una zona concreta?", importancia: 3 },
      { texto: "¿Se acompaña de falta de aire, sudor frío o dolor irradiado?", importancia: 3 },
    ],
    posiblesCausas: ["Sobrecarga muscular", "Costocondritis", "Traumatismo", "Otras causas torácicas que deben descartarse según el contexto"],
    factoresRiesgo: ["Esfuerzo físico reciente", "Tos intensa", "Traumatismo"],
    nutricion: ["No existe una dieta específica para el dolor de pared torácica"],
    fitoterapia: ["No utilizar antiinflamatorios naturales para retrasar la valoración de un dolor torácico nuevo"],
    recomendaciones: ["Evitar el esfuerzo que reproduce el dolor", "Consultar si el dolor es nuevo, intenso o no mejora"],
    nivelEvidencia: "moderada",
    contraindicaciones: ["No asumir origen muscular si existen señales cardiovasculares o respiratorias"],
    interacciones: ["Revisar antiinflamatorios y suplementos si se plantean medidas para el dolor"],
    pruebasMedicasHabituales: ["Exploración clínica", "ECG u otras pruebas si el contexto no permite descartar causas cardíacas"],
    especialistaRecomendado: ["Atención Primaria", "Urgencias si hay señales de alarma"],
    cuandoAcudirMedico: ["Dolor opresivo", "Falta de aire", "Sudor frío", "Dolor irradiado", "Desmayo"],
    bibliografia: ["Guías sobre evaluación del dolor torácico"],
    enfoques: {
      convencional: {
        titulo: "Medicina convencional",
        marco: "Primero descarta causas cardíacas o pulmonares cuando el contexto lo exige; después valora origen musculoesquelético.",
        intervenciones: ["Exploración", "Analgesia apropiada", "Pruebas si existen dudas diagnósticas"],
        nivelEvidencia: "alta",
      },
      nutricion: {
        titulo: "Nutrición",
        marco: "No desempeña un papel principal en un episodio de dolor de pared torácica.",
        intervenciones: ["Mantener alimentación habitual equilibrada"],
        nivelEvidencia: "limitada",
      },
      natural: {
        titulo: "Fitoterapia y medicina natural",
        marco: "Puede considerarse apoyo sintomático solo después de descartar causas graves.",
        intervenciones: ["Medidas locales suaves y reposo relativo según tolerancia"],
        nivelEvidencia: "limitada",
      },
      medicinaChina: {
        titulo: "Medicina tradicional china",
        marco: "Puede abordar dolor musculoesquelético mediante su marco propio, pero no debe utilizarse para descartar causas cardíacas.",
        intervenciones: ["Uso complementario tras valoración apropiada"],
        nivelEvidencia: "tradicional",
      },
      estiloVida: {
        titulo: "Estilo de vida",
        marco: "La recuperación suele beneficiarse de evitar temporalmente movimientos que disparan el dolor y volver progresivamente a la actividad.",
        intervenciones: ["Reposo relativo", "Retorno progresivo a actividad", "Evitar sobrecarga repetitiva"],
        nivelEvidencia: "moderada",
      },
    },
  },
];