import type { Condicion } from "./condiciones";

export const condicionesNeuroMusculo: Condicion[] = [
  {
    id: "cefalea-tensional",
    nombre: "Cefalea tensional compatible",
    descripcion:
      "Dolor de cabeza habitualmente opresivo, bilateral y de intensidad leve o moderada, sin las características típicas de una migraña.",
    sintomas: [
      { nombre: "Dolor de cabeza", peso: 2 },
      { nombre: "Dolor opresivo en la cabeza", peso: 3 },
      { nombre: "Dolor en ambos lados de la cabeza", peso: 2 },
      { nombre: "Dolor de cuello", peso: 1 },
      { nombre: "Estrés", peso: 1 },
    ],
    sintomasAlarma: [
      { nombre: "Dolor de cabeza súbito e intenso", gravedad: "urgente" },
      { nombre: "Fiebre con rigidez de cuello", gravedad: "urgente" },
      { nombre: "Pérdida de fuerza", gravedad: "urgente" },
      { nombre: "Confusión", gravedad: "urgente" },
      { nombre: "Desmayo", gravedad: "urgente" },
    ],
    sintomasQueContradicen: [
      { nombre: "Dolor pulsátil", peso: 2 },
      { nombre: "Sensibilidad intensa a la luz", peso: 2 },
      { nombre: "Aura visual", peso: 2 },
    ],
    preguntas: [
      { texto: "¿El dolor es opresivo o pulsátil?", importancia: 3 },
      { texto: "¿Es bilateral o predomina en un lado?", importancia: 2 },
      { texto: "¿Empeora con la actividad habitual?", importancia: 2 },
    ],
    posiblesCausas: [
      "Cefalea primaria tensional",
      "Estrés y tensión muscular",
      "Alteraciones del sueño",
      "Sobrecarga cervical",
    ],
    factoresRiesgo: ["Estrés", "Mal sueño", "Tensión cervical", "Fatiga"],
    nutricion: [
      "Mantener hidratación y comidas regulares",
      "Evitar ayunos prolongados si actúan como desencadenante",
    ],
    fitoterapia: [
      "No existe una planta de primera línea con evidencia sólida para abortar una cefalea tensional",
      "Los recursos naturales deben considerarse apoyo y no sustituir la valoración ante signos de alarma",
    ],
    recomendaciones: [
      "Registrar frecuencia y posibles desencadenantes",
      "Revisar sueño, estrés y ergonomía",
      "Evitar uso excesivo de analgésicos",
    ],
    nivelEvidencia: "alta",
    contraindicaciones: ["No tratar como cefalea primaria si existen señales de alarma"],
    interacciones: ["Revisar medicamentos y suplementos si las cefaleas son nuevas o han cambiado"],
    pruebasMedicasHabituales: [
      "Historia clínica y exploración neurológica",
      "No suele requerir neuroimagen cuando el patrón es típico y no existen señales de alarma",
    ],
    especialistaRecomendado: ["Atención Primaria", "Neurología si el patrón es atípico o persistente"],
    cuandoAcudirMedico: [
      "Inicio súbito y máxima intensidad en pocos minutos",
      "Déficit neurológico, confusión o pérdida de conciencia",
      "Fiebre con empeoramiento de la cefalea o rigidez de cuello",
      "Cambio importante respecto a cefaleas habituales",
    ],
    bibliografia: ["NICE CG150 Headaches in over 12s"],
    enfoques: {
      convencional: {
        titulo: "Medicina convencional",
        marco: "Clasifica el tipo de cefalea mediante historia clínica y exploración, y descarta causas secundarias mediante señales de alarma.",
        intervenciones: [
          "Tratamiento analgésico apropiado según antecedentes y contraindicaciones",
          "Evitar sobreuso de medicación para el dolor",
          "Diario de cefaleas si son recurrentes",
        ],
        nivelEvidencia: "alta",
      },
      nutricion: {
        titulo: "Nutrición",
        marco: "Busca reducir desencadenantes evitables como deshidratación o irregularidad de comidas.",
        intervenciones: ["Hidratación adecuada", "Horarios regulares de comida", "Registrar desencadenantes individuales sin imponer restricciones generales"],
        nivelEvidencia: "moderada",
      },
      natural: {
        titulo: "Fitoterapia y medicina natural",
        marco: "Puede valorar medidas complementarias de relajación o recursos con evidencia limitada, evitando atribuirles capacidad diagnóstica.",
        intervenciones: ["Técnicas de relajación", "Valorar masaje o abordaje de tensión muscular si no hay contraindicaciones", "Evitar combinaciones herbales sin revisar interacciones"],
        nivelEvidencia: "limitada",
      },
      medicinaChina: {
        titulo: "Medicina tradicional china",
        marco: "Interpreta la cefalea mediante patrones propios relacionados con localización, cualidad del dolor y otros signos.",
        intervenciones: ["Acupuntura individualizada por profesional cualificado", "Valoración de patrones tradicionales", "Fitoterapia china solo con revisión profesional"],
        nivelEvidencia: "tradicional",
        nota: "Este marco no sustituye la exclusión de causas neurológicas secundarias.",
      },
      estiloVida: {
        titulo: "Estilo de vida",
        marco: "El sueño, el estrés, la postura y la actividad pueden influir en la frecuencia de cefaleas tensionales.",
        intervenciones: ["Regularidad de sueño", "Pausas y ergonomía", "Actividad física regular y manejo del estrés"],
        nivelEvidencia: "moderada",
      },
    },
  },
  {
    id: "migrana",
    nombre: "Migraña compatible",
    descripcion:
      "Cefalea recurrente que suele ser pulsátil, de intensidad moderada o intensa, a menudo unilateral y acompañada de náuseas o sensibilidad a luz y sonido; puede presentarse con aura.",
    sintomas: [
      { nombre: "Migraña", peso: 3 },
      { nombre: "Dolor pulsátil", peso: 3 },
      { nombre: "Dolor en un lado de la cabeza", peso: 2 },
      { nombre: "Sensibilidad intensa a la luz", peso: 2 },
      { nombre: "Sensibilidad intensa al sonido", peso: 2 },
      { nombre: "Náuseas", peso: 1 },
      { nombre: "Aura visual", peso: 2 },
    ],
    sintomasAlarma: [
      { nombre: "Dolor de cabeza súbito e intenso", gravedad: "urgente" },
      { nombre: "Pérdida de fuerza", gravedad: "urgente" },
      { nombre: "Confusión", gravedad: "urgente" },
      { nombre: "Desmayo", gravedad: "urgente" },
      { nombre: "Visión doble nueva", gravedad: "alta" },
    ],
    sintomasQueContradicen: [
      { nombre: "Dolor opresivo en la cabeza", peso: 1 },
      { nombre: "Dolor en ambos lados de la cabeza", peso: 1 },
    ],
    preguntas: [
      { texto: "¿Dura entre varias horas y tres días?", importancia: 2 },
      { texto: "¿Empeora o limita la actividad habitual?", importancia: 2 },
      { texto: "¿Hay aura visual, sensitiva o del habla completamente reversible?", importancia: 3 },
    ],
    posiblesCausas: ["Trastorno neurológico primario tipo migraña", "Desencadenantes individuales de sueño, estrés, ciclo hormonal o alimentación"],
    factoresRiesgo: ["Antecedentes familiares", "Alteraciones del sueño", "Estrés", "Cambios hormonales en algunas personas"],
    nutricion: ["Evitar ayunos prolongados", "Mantener hidratación", "Identificar desencadenantes individuales mediante diario en vez de dietas restrictivas generales"],
    fitoterapia: ["Algunos complementos se han estudiado en prevención, pero deben revisarse dosis, calidad, embarazo e interacciones antes de recomendarlos"],
    recomendaciones: ["Diario de migrañas", "Revisar frecuencia y uso de analgésicos", "Consulta si aumenta la frecuencia o cambia el patrón"],
    nivelEvidencia: "alta",
    contraindicaciones: ["No asumir migraña ante síntomas neurológicos nuevos, persistentes o atípicos"],
    interacciones: ["Revisar tratamientos preventivos o agudos con un profesional antes de combinar con suplementos"],
    pruebasMedicasHabituales: ["Historia clínica y exploración neurológica", "La neuroimagen no se indica solo para tranquilizar cuando el cuadro es típico y no hay señales de alarma"],
    especialistaRecomendado: ["Atención Primaria", "Neurología si es frecuente, atípica, refractaria o existen dudas diagnósticas"],
    cuandoAcudirMedico: ["Cefalea explosiva", "Déficit neurológico nuevo", "Alteración de conciencia", "Aura atípica o síntomas que no revierten", "Cambio sustancial del patrón"],
    bibliografia: ["NICE CG150 Headaches in over 12s"],
    enfoques: {
      convencional: {
        titulo: "Medicina convencional",
        marco: "Distingue migraña con o sin aura de otros tipos de cefalea y selecciona tratamiento agudo o preventivo según frecuencia e impacto.",
        intervenciones: ["Tratamiento agudo individualizado", "Prevención farmacológica cuando está indicada", "Evitar sobreuso de medicación"],
        nivelEvidencia: "alta",
      },
      nutricion: {
        titulo: "Nutrición",
        marco: "La prioridad es regularidad e identificación individual de desencadenantes, evitando listas universales de alimentos prohibidos.",
        intervenciones: ["Comidas regulares", "Hidratación", "Diario de desencadenantes"],
        nivelEvidencia: "moderada",
      },
      natural: {
        titulo: "Fitoterapia y medicina natural",
        marco: "Algunos suplementos y técnicas complementarias se han estudiado sobre todo en prevención, con evidencia desigual.",
        intervenciones: ["Valorar solo productos con composición conocida y evidencia específica", "Revisar embarazo, medicación e interacciones", "No sustituir tratamiento médico si la migraña es incapacitante o frecuente"],
        nivelEvidencia: "limitada",
      },
      medicinaChina: {
        titulo: "Medicina tradicional china",
        marco: "Utiliza patrones tradicionales y puede incluir acupuntura como intervención complementaria.",
        intervenciones: ["Acupuntura por profesional cualificado", "Patrón tradicional individualizado", "Evitar fitoterapia china sin revisión de interacciones"],
        nivelEvidencia: "tradicional",
      },
      estiloVida: {
        titulo: "Estilo de vida",
        marco: "Regularidad de sueño, actividad, estrés y hábitos puede disminuir la exposición a desencadenantes.",
        intervenciones: ["Sueño regular", "Ejercicio progresivo", "Manejo del estrés", "Registro de frecuencia y desencadenantes"],
        nivelEvidencia: "moderada",
      },
    },
  },
  {
    id: "vertigo-posicional",
    nombre: "Vértigo periférico / posicional compatible",
    descripcion:
      "Sensación rotatoria que puede aparecer con movimientos de la cabeza; cuando es breve y posicional puede ser compatible con vértigo posicional benigno, pero deben excluirse causas neurológicas centrales.",
    sintomas: [
      { nombre: "Vértigo", peso: 3 },
      { nombre: "Todo gira", peso: 3 },
      { nombre: "Vértigo al mover la cabeza", peso: 3 },
      { nombre: "Náuseas", peso: 1 },
      { nombre: "Inestabilidad al caminar", peso: 1 },
    ],
    sintomasAlarma: [
      { nombre: "Pérdida de fuerza", gravedad: "urgente" },
      { nombre: "Confusión", gravedad: "urgente" },
      { nombre: "Dificultad para hablar", gravedad: "urgente" },
      { nombre: "Visión doble nueva", gravedad: "urgente" },
      { nombre: "Pérdida brusca de audición", gravedad: "alta" },
    ],
    sintomasQueContradicen: [
      { nombre: "Sensación de desmayo", peso: 2 },
      { nombre: "Aparece al levantarme", peso: 1 },
    ],
    preguntas: [
      { texto: "¿Lo desencadena mover la cabeza o girarte en la cama?", importancia: 3 },
      { texto: "¿Dura segundos, minutos u horas?", importancia: 2 },
      { texto: "¿Hay síntomas neurológicos o pérdida de audición?", importancia: 3 },
    ],
    posiblesCausas: ["Vértigo posicional paroxístico benigno", "Otros trastornos vestibulares periféricos", "Migraña vestibular"],
    factoresRiesgo: ["Antecedente de traumatismo craneal", "Labirintitis previa", "Edad"],
    nutricion: ["Mantener hidratación adecuada", "No asumir que toda sensación de mareo tiene causa nutricional"],
    fitoterapia: ["No priorizar fitoterapia antes de diferenciar vértigo periférico de causas neurológicas o cardiovasculares"],
    recomendaciones: ["Evitar conducir o alturas durante episodios", "Levantarse con precaución", "Valoración si es nuevo, intenso o persistente"],
    nivelEvidencia: "alta",
    contraindicaciones: ["No realizar maniobras por cuenta propia si existe enfermedad cervical inestable o dudas neurológicas"],
    interacciones: ["Revisar fármacos que puedan producir mareo"],
    pruebasMedicasHabituales: ["Exploración neurológica y vestibular", "Maniobra de Hallpike cuando el patrón es posicional y procede"],
    especialistaRecomendado: ["Atención Primaria", "Otorrinolaringología", "Neurología o Urgencias ante signos centrales"],
    cuandoAcudirMedico: ["Déficit neurológico", "Incapacidad marcada para caminar", "Pérdida brusca de audición", "Cefalea intensa nueva asociada"],
    bibliografia: ["NICE NG127 Suspected neurological conditions"],
    enfoques: {
      convencional: {
        titulo: "Medicina convencional",
        marco: "Diferencia causas vestibulares periféricas de causas neurológicas y cardiovasculares; en BPPV puede utilizar maniobras diagnósticas y de reposicionamiento.",
        intervenciones: ["Exploración dirigida", "Hallpike cuando procede", "Maniobra de reposicionamiento si se confirma BPPV y no hay contraindicaciones"],
        nivelEvidencia: "alta",
      },
      nutricion: {
        titulo: "Nutrición",
        marco: "La nutrición tiene un papel secundario salvo que exista deshidratación u otra causa concreta.",
        intervenciones: ["Hidratación", "Comidas regulares si el mareo se relaciona con ayuno", "Evitar atribuciones dietéticas sin evidencia"],
        nivelEvidencia: "limitada",
      },
      natural: {
        titulo: "Fitoterapia y medicina natural",
        marco: "No debe retrasar el diagnóstico diferencial de un vértigo nuevo.",
        intervenciones: ["Medidas de seguridad postural", "Evitar productos sedantes que puedan aumentar caídas", "Revisar interacciones"],
        nivelEvidencia: "limitada",
      },
      medicinaChina: {
        titulo: "Medicina tradicional china",
        marco: "Interpreta el mareo mediante patrones tradicionales, pero no distingue por sí sola un ictus de una causa vestibular periférica.",
        intervenciones: ["Acupuntura como complemento tras evaluación", "Patrón tradicional individualizado"],
        nivelEvidencia: "tradicional",
      },
      estiloVida: {
        titulo: "Estilo de vida",
        marco: "La prevención de caídas y la adaptación temporal de actividades son importantes durante episodios.",
        intervenciones: ["Evitar conducir durante vértigo activo", "Movimientos prudentes", "Rehabilitación vestibular si está indicada"],
        nivelEvidencia: "moderada",
      },
    },
  },
  {
    id: "lumbalgia",
    nombre: "Lumbalgia inespecífica compatible",
    descripcion:
      "Dolor localizado en la zona lumbar sin características claras de compresión radicular ni señales que sugieran una causa grave.",
    sintomas: [
      { nombre: "Dolor lumbar", peso: 3 },
      { nombre: "Dolor de espalda", peso: 2 },
      { nombre: "Rigidez", peso: 1 },
      { nombre: "Limitación de movimiento", peso: 1 },
      { nombre: "Dolor muscular", peso: 1 },
    ],
    sintomasAlarma: [
      { nombre: "Pérdida de control de orina o heces", gravedad: "urgente" },
      { nombre: "Adormecimiento en zona genital o perineal", gravedad: "urgente" },
      { nombre: "Pérdida de fuerza en ambas piernas", gravedad: "urgente" },
      { nombre: "Fiebre", gravedad: "alta" },
      { nombre: "Pérdida de peso", gravedad: "alta" },
    ],
    sintomasQueContradicen: [
      { nombre: "Dolor que baja por la pierna", peso: 2 },
      { nombre: "Hormigueo en una pierna", peso: 1 },
    ],
    preguntas: [
      { texto: "¿El dolor queda en la espalda o baja por una pierna?", importancia: 3 },
      { texto: "¿Hay debilidad, adormecimiento perineal o cambios de esfínteres?", importancia: 3 },
      { texto: "¿Hubo traumatismo importante?", importancia: 2 },
    ],
    posiblesCausas: ["Dolor lumbar mecánico inespecífico", "Sobrecarga muscular", "Cambios degenerativos no necesariamente causales"],
    factoresRiesgo: ["Sobrecarga física", "Sedentarismo", "Episodios previos", "Factores psicosociales y laborales"],
    nutricion: ["No existe una dieta específica para la lumbalgia inespecífica", "Mantener alimentación equilibrada y peso saludable puede formar parte del manejo general"],
    fitoterapia: ["La evidencia de productos herbales es variable; no deben sustituir ejercicio, educación y valoración cuando existen alarmas"],
    recomendaciones: ["Mantener actividad según tolerancia", "Evitar reposo prolongado", "Progresar ejercicio y función"],
    nivelEvidencia: "alta",
    contraindicaciones: ["No tratar como lumbalgia simple si existen signos neurológicos progresivos o síndrome de cola de caballo"],
    interacciones: ["Revisar analgésicos, antiinflamatorios y suplementos con otros tratamientos y antecedentes"],
    pruebasMedicasHabituales: ["Historia y exploración", "No se recomienda imagen rutinaria en lumbalgia inespecífica sin sospecha de patología grave"],
    especialistaRecomendado: ["Atención Primaria", "Fisioterapia", "Urgencias o especialista si existen señales de alarma"],
    cuandoAcudirMedico: ["Alteración de esfínteres", "Anestesia perineal", "Debilidad progresiva", "Fiebre o pérdida de peso inexplicada", "Traumatismo importante"],
    bibliografia: ["NICE NG59 Low back pain and sciatica"],
    enfoques: {
      convencional: {
        titulo: "Medicina convencional",
        marco: "Distingue dolor lumbar inespecífico de fractura, infección, cáncer, enfermedad inflamatoria y compromiso neurológico.",
        intervenciones: ["Educación y mantenimiento de actividad", "Analgesia individualizada cuando procede", "Evitar imagen rutinaria sin indicación clínica"],
        nivelEvidencia: "alta",
      },
      nutricion: {
        titulo: "Nutrición",
        marco: "No existe una dieta curativa específica; el papel es de apoyo a la salud general.",
        intervenciones: ["Alimentación equilibrada", "Peso saludable", "Aporte adecuado de proteína y micronutrientes según necesidades"],
        nivelEvidencia: "limitada",
      },
      natural: {
        titulo: "Fitoterapia y medicina natural",
        marco: "Puede incluir intervenciones complementarias para dolor, pero la evidencia varía y debe priorizarse la recuperación funcional.",
        intervenciones: ["Calor local si resulta confortable", "Valorar técnicas manuales dentro de un programa con ejercicio", "Revisar seguridad de productos naturales"],
        nivelEvidencia: "limitada",
      },
      medicinaChina: {
        titulo: "Medicina tradicional china",
        marco: "Puede incluir acupuntura y patrones tradicionales como complemento, sin sustituir la detección de patología grave.",
        intervenciones: ["Acupuntura por profesional cualificado", "Valoración tradicional individualizada"],
        nivelEvidencia: "tradicional",
      },
      estiloVida: {
        titulo: "Estilo de vida",
        marco: "La actividad y la recuperación funcional progresiva son centrales.",
        intervenciones: ["Evitar reposo prolongado", "Ejercicio progresivo", "Ergonomía y adaptación de carga", "Sueño y manejo de factores psicosociales"],
        nivelEvidencia: "alta",
      },
    },
  },
  {
    id: "ciatica",
    nombre: "Ciática / dolor radicular compatible",
    descripcion:
      "Dolor que se irradia desde la zona lumbar o glútea hacia una pierna, a veces acompañado de hormigueo o alteraciones sensitivas.",
    sintomas: [
      { nombre: "Dolor que baja por la pierna", peso: 3 },
      { nombre: "Dolor lumbar", peso: 1 },
      { nombre: "Hormigueo en una pierna", peso: 2 },
      { nombre: "Dolor en glúteo", peso: 1 },
      { nombre: "Pérdida de fuerza en una pierna", peso: 2 },
    ],
    sintomasAlarma: [
      { nombre: "Pérdida de control de orina o heces", gravedad: "urgente" },
      { nombre: "Adormecimiento en zona genital o perineal", gravedad: "urgente" },
      { nombre: "Pérdida de fuerza en ambas piernas", gravedad: "urgente" },
      { nombre: "Debilidad progresiva de una pierna", gravedad: "alta" },
    ],
    sintomasQueContradicen: [
      { nombre: "Hinchazón de una sola pierna", peso: 2 },
      { nombre: "Pierna roja y caliente", peso: 2 },
    ],
    preguntas: [
      { texto: "¿El dolor baja desde espalda o glúteo hacia una pierna?", importancia: 3 },
      { texto: "¿Hay hormigueo, pérdida de sensibilidad o debilidad?", importancia: 3 },
      { texto: "¿Hay cambios de esfínteres o adormecimiento perineal?", importancia: 3 },
    ],
    posiblesCausas: ["Irritación o compresión de una raíz nerviosa", "Hernia o protrusión discal", "Cambios degenerativos"],
    factoresRiesgo: ["Episodios lumbares previos", "Sobrecarga", "Cambios degenerativos"],
    nutricion: ["No existe una dieta específica para la ciática", "Mantener estado nutricional y peso saludables como apoyo general"],
    fitoterapia: ["No debe usarse fitoterapia para retrasar la valoración de déficit neurológico"],
    recomendaciones: ["Mantener actividad dentro de tolerancia", "Evitar reposo prolongado", "Consultar si aparece o progresa debilidad"],
    nivelEvidencia: "alta",
    contraindicaciones: ["Síndrome de cola de caballo o debilidad progresiva requieren valoración urgente"],
    interacciones: ["Revisar analgesia y suplementos con medicación habitual"],
    pruebasMedicasHabituales: ["Historia y exploración neurológica de la extremidad", "Imagen solo cuando puede cambiar el manejo o existe sospecha de patología grave"],
    especialistaRecomendado: ["Atención Primaria", "Fisioterapia", "Traumatología/Neurocirugía según evolución", "Urgencias ante cola de caballo"],
    cuandoAcudirMedico: ["Alteración de esfínteres", "Anestesia perineal", "Debilidad progresiva", "Síntomas en ambas piernas"],
    bibliografia: ["NICE NG59 Low back pain and sciatica"],
    enfoques: {
      convencional: {
        titulo: "Medicina convencional",
        marco: "Evalúa distribución radicular, fuerza, sensibilidad y señales de compresión neurológica grave.",
        intervenciones: ["Manejo conservador en muchos casos", "Analgesia individualizada", "Derivación o imagen si hay déficit progresivo o si cambiará el tratamiento"],
        nivelEvidencia: "alta",
      },
      nutricion: {
        titulo: "Nutrición",
        marco: "Tiene papel de apoyo general y no descomprime una raíz nerviosa.",
        intervenciones: ["Alimentación equilibrada", "Peso saludable si es relevante"],
        nivelEvidencia: "limitada",
      },
      natural: {
        titulo: "Fitoterapia y medicina natural",
        marco: "Puede acompañar el control sintomático, pero no sustituye la valoración neurológica.",
        intervenciones: ["Calor local según tolerancia", "Técnicas manuales solo dentro de un plan seguro", "Evitar productos con interacciones"],
        nivelEvidencia: "limitada",
      },
      medicinaChina: {
        titulo: "Medicina tradicional china",
        marco: "Puede utilizar acupuntura como complemento, siempre después de excluir déficit neurológico grave.",
        intervenciones: ["Acupuntura por profesional cualificado", "Valoración tradicional individualizada"],
        nivelEvidencia: "tradicional",
      },
      estiloVida: {
        titulo: "Estilo de vida",
        marco: "Busca conservar función y evitar miedo al movimiento cuando no existen contraindicaciones.",
        intervenciones: ["Actividad progresiva", "Ejercicio guiado", "Adaptación temporal de cargas", "Evitar reposo prolongado"],
        nivelEvidencia: "alta",
      },
    },
  },
];