import type { EjemplosCondicion } from "./ejemplosConEvidencia";
export const ejemplosConEvidenciaComplementarios: Record<string, EjemplosCondicion> = {
"sii":{nutricion:[{nombre:"Psyllium / fibra soluble",utilidad:"Puede mejorar el hábito intestinal y algunos síntomas del síndrome de intestino irritable, especialmente cuando predomina estreñimiento.",evidencia:"moderada"},{nombre:"Dieta baja en FODMAP supervisada",utilidad:"Puede reducir dolor, distensión y gases en algunas personas; debe hacerse de forma temporal y con reintroducción.",evidencia:"moderada"}],fitoterapia:[{nombre:"Aceite de menta entérico",utilidad:"Puede reducir dolor abdominal y síntomas globales del síndrome de intestino irritable en algunas personas.",evidencia:"moderada"}]},
"hipoglucemia-compatible":{nutricion:[{nombre:"Glucosa de absorción rápida",utilidad:"En una persona consciente con hipoglucemia confirmada, una cantidad pautada de carbohidrato de absorción rápida es la medida nutricional inmediata habitual.",evidencia:"alta"}],fitoterapia:[{nombre:"Fitoterapia",utilidad:"No existe una planta indicada para corregir una hipoglucemia aguda; algunos suplementos incluso pueden bajar más la glucosa.",evidencia:"alta"}]},
"hipertiroidismo-compatible":{nutricion:[{nombre:"Aporte suficiente de energía y proteína",utilidad:"Ayuda a limitar pérdida de masa corporal cuando existe pérdida de peso asociada al hipertiroidismo, sin sustituir el tratamiento.",evidencia:"alta"},{nombre:"Evitar exceso de yodo",utilidad:"Algas y suplementos con dosis altas de yodo pueden empeorar algunos trastornos tiroideos.",evidencia:"alta"}],fitoterapia:[{nombre:"Algas ricas en yodo",utilidad:"No se recomiendan como tratamiento y pueden empeorar la situación por exceso de yodo.",evidencia:"alta"}]},
"sindrome-gripal":{nutricion:[{nombre:"Agua, caldos y solución de rehidratación cuando procede",utilidad:"Ayudan a reponer líquidos durante fiebre y menor ingesta.",evidencia:"alta"},{nombre:"Miel",utilidad:"Puede aliviar la tos asociada en adultos y mayores de un año, aunque no trata el virus.",evidencia:"moderada"}],fitoterapia:[{nombre:"Equinácea",utilidad:"Algunos preparados se han estudiado para infecciones respiratorias, pero los resultados son heterogéneos.",evidencia:"limitada"}]},
"faringitis":{nutricion:[{nombre:"Miel",utilidad:"Puede aliviar temporalmente la irritación y la tos asociada en mayores de un año.",evidencia:"moderada"},{nombre:"Líquidos fríos o templados",utilidad:"Pueden facilitar hidratación y aliviar molestias al tragar según tolerancia.",evidencia:"moderada"}],fitoterapia:[{nombre:"Salvia en gárgaras",utilidad:"Se usa tradicionalmente para molestias de boca y garganta; no sustituye el diagnóstico de una faringitis bacteriana.",evidencia:"tradicional"}]},
"deshidratacion-compatible":{nutricion:[{nombre:"Solución de rehidratación oral",utilidad:"La combinación adecuada de agua, glucosa y sales facilita la reposición de líquidos y electrolitos.",evidencia:"alta"}],fitoterapia:[{nombre:"Plantas diuréticas",utilidad:"No deben utilizarse para tratar una deshidratación porque pueden aumentar la pérdida de líquidos.",evidencia:"alta"}]},
"apnea-sueno-compatible":{nutricion:[{nombre:"Pérdida de peso mediante alimentación equilibrada",utilidad:"En personas con exceso de peso puede reducir la gravedad de la apnea obstructiva.",evidencia:"alta"}],fitoterapia:[{nombre:"Valeriana u otros sedantes vegetales",utilidad:"No tratan la obstrucción respiratoria y la sedación puede ser contraproducente en una apnea no evaluada.",evidencia:"alta"}]},
"palpitaciones":{nutricion:[{nombre:"Reducir cafeína y bebidas energéticas",utilidad:"Puede disminuir episodios cuando existe una relación clara entre estimulantes y palpitaciones.",evidencia:"moderada"},{nombre:"Hidratación adecuada",utilidad:"Puede ayudar si la deshidratación contribuye a los síntomas.",evidencia:"moderada"}],fitoterapia:[{nombre:"Guaraná y otros estimulantes vegetales",utilidad:"Pueden aumentar frecuencia cardíaca y palpitaciones.",evidencia:"moderada"}]},
"mareo-ortostatico":{nutricion:[{nombre:"Agua",utilidad:"Una hidratación adecuada puede mejorar síntomas cuando existe bajo volumen circulante, salvo restricción médica.",evidencia:"moderada"}],fitoterapia:[{nombre:"Regaliz",utilidad:"Puede elevar la presión, pero no debe recomendarse para tratar el mareo por riesgo de hipertensión, alteraciones de potasio e interacciones.",evidencia:"alta"}]},
"vaginitis-compatible":{nutricion:[{nombre:"Yogur y alimentos fermentados",utilidad:"Pueden formar parte de una dieta saludable, pero no sustituyen el tratamiento de una infección vaginal.",evidencia:"insuficiente"}],fitoterapia:[{nombre:"Ajo o árbol del té intravaginal",utilidad:"No se recomiendan: pueden irritar mucosas y no sustituyen diagnóstico y tratamiento.",evidencia:"alta"}]},
"sangrado-uterino-anormal":{nutricion:[{nombre:"Almejas, carne, lentejas y garbanzos",utilidad:"Aportan hierro y son útiles para recuperar reservas cuando el sangrado ha producido ferropenia.",evidencia:"alta"},{nombre:"Kiwi, cítricos y pimiento",utilidad:"Su vitamina C mejora la absorción del hierro vegetal.",evidencia:"alta"}],fitoterapia:[{nombre:"Fitoterapia hemostática",utilidad:"No existe una planta que deba recomendarse para frenar un sangrado uterino anormal sin estudiar primero la causa.",evidencia:"alta"}]},
"embarazo-ectopico-alerta":{nutricion:[{nombre:"Nutrición",utilidad:"No existe un alimento capaz de tratar esta situación; la prioridad es la valoración médica urgente.",evidencia:"alta"}],fitoterapia:[{nombre:"Fitoterapia",utilidad:"No tiene papel para tratar un posible embarazo ectópico y no debe retrasar la atención urgente.",evidencia:"alta"}]},
"hipertension-compatible":{nutricion:[{nombre:"Patrón DASH",utilidad:"Un patrón rico en frutas, verduras, legumbres, cereales integrales y lácteos bajos en grasa puede reducir la presión arterial.",evidencia:"alta"},{nombre:"Reducción de sodio",utilidad:"Reducir sal y alimentos muy salados puede disminuir la presión, especialmente en personas sensibles al sodio.",evidencia:"alta"}],fitoterapia:[{nombre:"Ajo",utilidad:"Algunos preparados estandarizados han mostrado reducciones modestas de presión, pero no sustituyen antihipertensivos y pueden interactuar con medicación.",evidencia:"moderada"},{nombre:"Regaliz",utilidad:"Puede elevar la presión y reducir el potasio; conviene evitarlo en hipertensión.",evidencia:"alta"}]},
"dislipemia-compatible":{nutricion:[{nombre:"Avena y cebada",utilidad:"Sus beta-glucanos solubles pueden ayudar a reducir el colesterol LDL dentro de una dieta adecuada.",evidencia:"alta"},{nombre:"Legumbres y frutos secos",utilidad:"Sustituir alimentos ricos en grasas saturadas por estas opciones puede mejorar el perfil lipídico.",evidencia:"alta"}],fitoterapia:[{nombre:"Psyllium",utilidad:"La fibra soluble de psyllium puede producir una reducción modesta del LDL.",evidencia:"alta"},{nombre:"Esteroles vegetales",utilidad:"Pueden reducir modestamente la absorción intestinal de colesterol y el LDL.",evidencia:"alta"},{nombre:"Arroz de levadura roja",utilidad:"Puede reducir LDL por monacolinas, pero presenta riesgos similares a estatinas, variabilidad de dosis y problemas de seguridad; no debe usarse a ciegas.",evidencia:"moderada"}]},
"higado-graso-metabolico":{nutricion:[{nombre:"Patrón mediterráneo",utilidad:"Ayuda a mejorar factores metabólicos y puede reducir grasa hepática, especialmente junto con pérdida de peso cuando procede.",evidencia:"alta"},{nombre:"Reducir bebidas azucaradas",utilidad:"Disminuir azúcares líquidos ayuda a reducir exceso energético y carga metabólica.",evidencia:"alta"}],fitoterapia:[{nombre:"Cardo mariano / silimarina",utilidad:"Se ha estudiado en enfermedad hepática, pero la evidencia no permite considerarlo sustituto del manejo metabólico ni tratamiento establecido del hígado graso.",evidencia:"limitada"}]},
"sindrome-metabolico-compatible":{nutricion:[{nombre:"Patrón mediterráneo",utilidad:"Puede mejorar peso, glucosa, lípidos y riesgo cardiovascular dentro de un abordaje integral.",evidencia:"alta"},{nombre:"Legumbres, avena, verduras y frutos secos",utilidad:"Aportan fibra y sustituyen alimentos refinados o ultraprocesados, ayudando al control metabólico.",evidencia:"alta"}],fitoterapia:[{nombre:"Psyllium",utilidad:"Puede apoyar modestamente el control de glucosa y colesterol como complemento de dieta y tratamiento.",evidencia:"moderada"}]}
};