import type { EjemplosCondicion } from "./ejemplosConEvidencia";
export const ejemplosAmpliacion:Record<string,EjemplosCondicion>={
"gota-compatible":{nutricion:[{nombre:"Agua",utilidad:"Una hidratación adecuada ayuda a reducir concentración urinaria y forma parte del manejo general cuando no existe restricción de líquidos.",evidencia:"moderada"},{nombre:"Cerezas",utilidad:"Estudios observacionales sugieren asociación con menos ataques, pero no sustituyen el tratamiento ni el control del urato.",evidencia:"limitada"},{nombre:"Reducir cerveza, destilados y bebidas azucaradas",utilidad:"Puede ayudar a disminuir factores dietéticos asociados con hiperuricemia y ataques de gota.",evidencia:"moderada"}],fitoterapia:[{nombre:"Fitoterapia para el ataque agudo",utilidad:"No existe una planta de primera línea que sustituya el tratamiento antiinflamatorio indicado para un ataque de gota.",evidencia:"alta"}]},
"osteoporosis-compatible":{nutricion:[{nombre:"Leche, yogur, queso, sardinas con espina y alimentos enriquecidos",utilidad:"Son fuentes dietéticas de calcio; el objetivo es alcanzar un aporte adecuado sin suplementar innecesariamente.",evidencia:"alta"},{nombre:"Proteína suficiente",utilidad:"Una ingesta adecuada contribuye al mantenimiento de músculo y hueso, especialmente en personas mayores.",evidencia:"alta"}],fitoterapia:[{nombre:"Vitamina D",utilidad:"La suplementación puede ser necesaria cuando existe déficit o riesgo, pero la dosis debe individualizarse.",evidencia:"alta"},{nombre:"Calcio suplementario",utilidad:"Puede utilizarse cuando la dieta no cubre necesidades, valorando dosis total y riesgos individuales.",evidencia:"alta"}]},
"fibromialgia-compatible":{nutricion:[{nombre:"Patrón mediterráneo",utilidad:"Es una base nutricional razonable para salud general, aunque no existe una dieta específica que cure la fibromialgia.",evidencia:"moderada"},{nombre:"Vitamina D si existe déficit",utilidad:"Corregir un déficit documentado es apropiado; suplementar sin déficit no tiene beneficio consistente demostrado para la fibromialgia.",evidencia:"moderada"}],fitoterapia:[{nombre:"Fitoterapia",utilidad:"No existe actualmente una planta con evidencia suficientemente consistente para considerarla tratamiento principal de la fibromialgia.",evidencia:"insuficiente"}]},
"piernas-inquietas-compatible":{nutricion:[{nombre:"Alimentos ricos en hierro",utilidad:"Carne, marisco, legumbres y otros alimentos con hierro ayudan a cubrir necesidades, pero un déficit relevante puede requerir tratamiento específico.",evidencia:"alta"},{nombre:"Cafeína",utilidad:"Reducirla puede ser útil si el café, té, cola o energéticas empeoran los síntomas o el sueño.",evidencia:"limitada"}],fitoterapia:[{nombre:"Hierro suplementario",utilidad:"Puede ser útil cuando ferritina y otros parámetros indican reservas bajas; no debe tomarse a ciegas.",evidencia:"alta"}]},
"dermatitis-atopica-compatible":{nutricion:[{nombre:"Dieta variada",utilidad:"No se recomienda eliminar leche, huevo, gluten u otros alimentos sin una alergia alimentaria demostrada.",evidencia:"alta"}],fitoterapia:[{nombre:"Avena coloidal tópica",utilidad:"Puede ayudar a hidratar y aliviar picor en piel seca o eccematosa como medida complementaria.",evidencia:"moderada"},{nombre:"Aceites esenciales",utilidad:"Pueden irritar o sensibilizar la piel y no deben aplicarse de forma indiscriminada sobre eccema activo.",evidencia:"moderada"}]},
"diverticulosis-compatible":{nutricion:[{nombre:"Legumbres, frutas, verduras y cereales integrales",utilidad:"Aumentan el aporte de fibra y pueden favorecer un tránsito intestinal adecuado en enfermedad diverticular no complicada.",evidencia:"moderada"},{nombre:"Frutos secos y semillas",utilidad:"No es necesario evitarlos de rutina por tener divertículos si se toleran.",evidencia:"moderada"}],fitoterapia:[{nombre:"Psyllium",utilidad:"Puede complementar la fibra dietética y mejorar el estreñimiento cuando se toma con suficiente líquido.",evidencia:"moderada"}]},
"hemorroides-compatible":{nutricion:[{nombre:"Frutas, verduras, legumbres y cereales integrales",utilidad:"La fibra ayuda a ablandar las heces y reducir el esfuerzo al defecar.",evidencia:"alta"},{nombre:"Agua",utilidad:"Una hidratación adecuada acompaña al aumento de fibra y ayuda a mantener heces más blandas.",evidencia:"moderada"}],fitoterapia:[{nombre:"Psyllium",utilidad:"La fibra soluble puede reducir sangrado y síntomas relacionados con estreñimiento y esfuerzo.",evidencia:"alta"}]},
"reflujo-laringofaringeo-compatible":{nutricion:[{nombre:"Cenas más tempranas y menos copiosas",utilidad:"Evitar grandes comidas cerca de acostarse puede reducir episodios de reflujo en personas susceptibles.",evidencia:"moderada"},{nombre:"Alimentos desencadenantes personales",utilidad:"Conviene identificar los que realmente empeoran síntomas en vez de eliminar listas completas sin necesidad.",evidencia:"moderada"}],fitoterapia:[{nombre:"Menta / aceite de menta",utilidad:"Puede relajar el esfínter esofágico y empeorar el reflujo en algunas personas.",evidencia:"moderada"}]}
};