export interface CategoriaEvaluacion {
  id: string;
  titulo: string;
  icono: string;
  opciones: string[];
}

export const categoriasEvaluacion: CategoriaEvaluacion[] = [
  {
    id: "dolor",
    titulo: "Dolor",
    icono: "⚡",
    opciones: [
      "Dolor de cabeza",
      "Dolor de cuello",
      "Dolor de garganta",
      "Dolor de pecho",
      "Dolor abdominal",
      "Dolor de espalda",
      "Dolor lumbar",
      "Dolor muscular",
      "Dolor articular",
      "Dolor pélvico",
      "Dolor al respirar",
      "Dolor al orinar",
    ],
  },
  {
    id: "estado-general",
    titulo: "Estado general",
    icono: "🌡️",
    opciones: [
      "Cansancio",
      "Debilidad",
      "Fiebre",
      "Escalofríos",
      "Sudoración nocturna",
      "Pérdida de peso",
      "Aumento de peso",
      "Poca energía",
      "Poco apetito",
      "Poca hidratación",
    ],
  },
  {
    id: "respiratorio",
    titulo: "Respiración",
    icono: "🫁",
    opciones: [
      "Tos seca",
      "Tos con mucosidad",
      "Falta de aire",
      "Congestión nasal",
      "Dolor al respirar",
      "Silbidos al respirar",
      "Mucosidad",
      "Ronquera",
    ],
  },
  {
    id: "cardiovascular",
    titulo: "Corazón y circulación",
    icono: "❤️",
    opciones: [
      "Dolor de pecho",
      "Palpitaciones",
      "Mareo",
      "Desmayo",
      "Hinchazón de piernas",
      "Sudor frío",
      "Presión en el pecho",
    ],
  },
  {
    id: "digestivo",
    titulo: "Digestión",
    icono: "🍽️",
    opciones: [
      "Náuseas",
      "Vómitos",
      "Acidez",
      "Reflujo",
      "Gases",
      "Hinchazón abdominal",
      "Estreñimiento",
      "Diarrea continua",
      "Pérdida de apetito",
      "Sensación de evacuación incompleta",
      "Esfuerzo al defecar",
    ],
  },
  {
    id: "heces",
    titulo: "Heces",
    icono: "💩",
    opciones: [
      "Heces duras",
      "Heces blandas",
      "Heces líquidas",
      "Heces claras",
      "Heces oscuras",
      "Heces negras",
      "Sangre roja en las heces",
      "Moco en las heces",
      "Heces flotantes",
      "Mal olor intenso",
      "Deposiciones muy frecuentes",
      "Menos de tres deposiciones por semana",
    ],
  },
  {
    id: "orina",
    titulo: "Orina",
    icono: "🚽",
    opciones: [
      "Orina clara",
      "Orina oscura",
      "Orina turbia",
      "Olor fuerte",
      "Espuma en la orina",
      "Dolor al orinar",
      "Sangre en la orina",
      "Orinar con mucha frecuencia",
      "Orinar muy poca cantidad",
      "Orinar mucha cantidad",
      "Levantarse por la noche a orinar",
      "Urgencia para orinar",
    ],
  },
  {
    id: "neurologico",
    titulo: "Sistema nervioso",
    icono: "🧠",
    opciones: [
      "Dolor de cabeza",
      "Migraña",
      "Mareo",
      "Vértigo",
      "Hormigueo",
      "Pérdida de fuerza",
      "Temblor",
      "Confusión",
      "Problemas de memoria",
      "Falta de concentración",
    ],
  },
  {
    id: "emocional",
    titulo: "Estado emocional",
    icono: "😊",
    opciones: [
      "Ansiedad",
      "Estrés",
      "Estado de ánimo bajo",
      "Tristeza",
      "Irritabilidad",
      "Mal sueño",
      "Insomnio",
      "Falta de motivación",
    ],
  },
  {
    id: "piel",
    titulo: "Piel",
    icono: "🧴",
    opciones: [
      "Picor",
      "Erupción",
      "Ronchas",
      "Palidez",
      "Color amarillo en la piel",
      "Moratones",
      "Sequedad de piel",
      "Enrojecimiento",
    ],
  },
  {
    id: "musculos-articulaciones",
    titulo: "Músculos y articulaciones",
    icono: "🦴",
    opciones: [
      "Dolor muscular",
      "Dolor articular",
      "Rigidez",
      "Inflamación",
      "Calambres",
      "Debilidad muscular",
      "Limitación de movimiento",
    ],
  },
];