import type { FichaVademecumFitoterapia } from "./vademecumFitoterapia";

const INTERACCIONES =
  "https://www.fitoterapia.net/publicaciones/documentacion/tabla-interacciones-entre-preparados-vegetales-2047.html";
const EMA = "https://www.ema.europa.eu/en/medicines/herbal";
const NCCIH = "https://www.nccih.nih.gov/health";

/**
 * Ampliación del Vademécum enlazada con las plantas que aparecen en las
 * recomendaciones de CuerpoClaro. Se resume el preparado concreto evaluado;
 * no se extrapola una monografía a otra parte de la planta o a otro extracto.
 */
export const vademecumFitoterapiaAmpliacion: FichaVademecumFitoterapia[] = [
  {
    id: "lino-semilla",
    nombre: "Lino",
    aliases: ["lino", "semilla de lino", "semillas de lino", "linum usitatissimum", "linaza"],
    especie: "Linum usitatissimum L.",
    drogaVegetal: "Semilla madura y desecada (Lini semen)",
    usoRespaldado: "EMA/HMPC reconoce preparados de semilla para estreñimiento habitual y, en formas concretas, molestias gastrointestinales leves.",
    precauciones: ["Debe tomarse con líquido suficiente.", "No usar ante obstrucción, estrechamiento intestinal o dificultad para tragar sin valoración profesional."],
    interaccion: { nivel: "monitorizar", resumen: "Los mucílagos pueden retrasar la absorción de medicamentos; conviene separar las tomas según el prospecto y revisar tratamientos de margen estrecho." },
    fuenteOficial: `${EMA}/lini-semen`,
    fuenteInteracciones: INTERACCIONES,
  },
  {
    id: "sen-hoja-fruto",
    nombre: "Sen",
    aliases: ["sen", "senna", "cassia senna", "senna alexandrina", "hoja de sen", "fruto de sen"],
    especie: "Senna alexandrina Mill. (sin. Cassia senna L. / C. angustifolia Vahl)",
    drogaVegetal: "Hoja o fruto, en preparados con derivados hidroxiantracénicos definidos",
    usoRespaldado: "Uso bien establecido para el tratamiento de corta duración del estreñimiento ocasional.",
    precauciones: ["No es una solución de uso diario o prolongado.", "No usar con dolor abdominal sin causa, obstrucción intestinal, deshidratación grave ni en menores de 12 años."],
    interaccion: { nivel: "monitorizar", resumen: "El abuso puede causar pérdida de potasio y aumentar el riesgo con glucósidos cardiacos, antiarrítmicos, diuréticos, corticoides o regaliz." },
    fuenteOficial: `${EMA}/sennae-folium`,
    fuenteInteracciones: INTERACCIONES,
  },
  {
    id: "frangula-corteza",
    nombre: "Frángula",
    aliases: ["frangula", "frángula", "frangula alnus", "rhamnus frangula", "corteza de frangula", "corteza de frángula"],
    especie: "Frangula alnus Mill. (sin. Rhamnus frangula L.)",
    drogaVegetal: "Corteza desecada y envejecida/procesada (Frangulae cortex)",
    usoRespaldado: "Uso bien establecido para el estreñimiento ocasional de corta duración.",
    precauciones: ["No utilizar durante más de una semana salvo indicación profesional.", "No usar ante dolor abdominal no explicado, obstrucción intestinal o deshidratación grave."],
    interaccion: { nivel: "monitorizar", resumen: "El uso excesivo puede producir hipopotasemia y aumentar riesgos con fármacos cardiacos, diuréticos, corticoides o regaliz." },
    fuenteOficial: `${EMA}/frangulae-cortex`,
    fuenteInteracciones: INTERACCIONES,
  },
  {
    id: "tomillo-parte-aerea",
    nombre: "Tomillo",
    aliases: ["tomillo", "thymus vulgaris", "thymus zygis", "thymi herba"],
    especie: "Thymus vulgaris L. / Thymus zygis L.",
    drogaVegetal: "Hojas y flores desecadas, jugo o extractos definidos (Thymi herba)",
    usoRespaldado: "Uso tradicional reconocido por EMA/HMPC para la tos productiva asociada al resfriado.",
    precauciones: ["No usar si existe alergia a plantas de la familia Lamiaceae.", "Consultar si aparece dificultad respiratoria, fiebre o esputo purulento."],
    interaccion: { nivel: "seguir", resumen: "La monografía no describe interacciones clínicas relevantes para los preparados evaluados." },
    fuenteVademecum: "https://www.fitoterapia.net/vademecum/plantas/tomillo.html",
    fuenteOficial: `${EMA}/thymi-herba`,
    fuenteInteracciones: INTERACCIONES,
  },
  {
    id: "hiedra-hoja",
    nombre: "Hiedra",
    aliases: ["hiedra", "hiedra hedera helix", "hedera helix", "hoja de hiedra"],
    especie: "Hedera helix L.",
    drogaVegetal: "Hoja y extractos definidos (Hederae helicis folium)",
    usoRespaldado: "EMA/HMPC reconoce preparados concretos como expectorantes en tos productiva.",
    precauciones: ["No administrar a menores de 2 años por riesgo de empeoramiento respiratorio.", "Consultar ante disnea, fiebre o esputo purulento."],
    interaccion: { nivel: "seguir", resumen: "No se describen interacciones relevantes en la monografía para los preparados evaluados." },
    fuenteOficial: `${EMA}/hederae-helicis-folium`,
    fuenteInteracciones: INTERACCIONES,
  },
  {
    id: "malvavisco-raiz",
    nombre: "Malvavisco",
    aliases: ["malvavisco", "althaea officinalis", "altea", "raiz de malvavisco", "raíz de malvavisco"],
    especie: "Althaea officinalis L.",
    drogaVegetal: "Raíz desecada (Althaeae radix)",
    usoRespaldado: "Uso tradicional reconocido para irritación de boca o garganta con tos seca asociada y para molestias digestivas leves.",
    precauciones: ["No sustituye la valoración de tos persistente, dificultad respiratoria o dolor importante.", "La preparación debe corresponder a la raíz descrita en la monografía."],
    interaccion: { nivel: "monitorizar", resumen: "Por su contenido en mucílagos puede retrasar la absorción de otros medicamentos; se aconseja separar las tomas según el producto." },
    fuenteOficial: `${EMA}/althaeae-radix`,
    fuenteInteracciones: INTERACCIONES,
  },
  {
    id: "malva-hoja-flor",
    nombre: "Malva",
    aliases: ["malva", "malva sylvestris", "flor de malva", "hoja de malva"],
    especie: "Malva sylvestris L. / Malva neglecta Wallr., según la droga",
    drogaVegetal: "Hoja o flor, según el preparado (Malvae folium / flos)",
    usoRespaldado: "Uso tradicional para irritación de boca y garganta con tos seca asociada y molestias gastrointestinales leves.",
    precauciones: ["No extrapolar una preparación de hoja a flor o a extractos de concentración distinta."],
    interaccion: { nivel: "monitorizar", resumen: "Los mucílagos pueden disminuir o retrasar la absorción de otros medicamentos; conviene separar las tomas." },
    fuenteOficial: `${EMA}/malvae-folium`,
    fuenteInteracciones: INTERACCIONES,
  },
  {
    id: "manzanilla-flor",
    nombre: "Manzanilla",
    aliases: ["manzanilla", "matricaria chamomilla", "matricaria recutita", "chamomilla recutita", "flor de manzanilla", "manzanilla en enjuague", "manzanilla o infusiones en el ojo"],
    especie: "Matricaria recutita L. (sin. Chamomilla recutita)",
    drogaVegetal: "Capítulos florales (Matricariae flos); el aceite esencial es otra preparación",
    usoRespaldado: "EMA/HMPC reconoce usos tradicionales para molestias digestivas leves, resfriado, irritaciones menores de boca/garganta y determinadas irritaciones cutáneas.",
    precauciones: ["Puede causar alergia, especialmente en personas sensibles a Asteraceae.", "Las infusiones caseras no son estériles y no deben aplicarse dentro del ojo."],
    interaccion: { nivel: "valorar", resumen: "No se describen interacciones clínicas relevantes en la monografía; si se usa medicación de margen estrecho o anticoagulación conviene revisión individual." },
    fuenteOficial: `${EMA}/matricariae-flos`,
    fuenteInteracciones: INTERACCIONES,
  },
  {
    id: "anis-verde-fruto",
    nombre: "Anís verde",
    aliases: ["anis verde", "anís verde", "pimpinella anisum", "fruto de anis", "fruto de anís"],
    especie: "Pimpinella anisum L.",
    drogaVegetal: "Fruto desecado (Anisi fructus)",
    usoRespaldado: "Uso tradicional reconocido para molestias digestivas leves con hinchazón y gases y como expectorante en tos asociada al resfriado.",
    precauciones: ["Evitar si existe alergia a anís o a otras Apiaceae.", "No confundir el fruto con aceite esencial concentrado."],
    interaccion: { nivel: "seguir", resumen: "La monografía no describe interacciones relevantes para el fruto en los preparados evaluados." },
    fuenteOficial: `${EMA}/anisi-fructus`,
    fuenteInteracciones: INTERACCIONES,
  },
  {
    id: "alcaravea-fruto",
    nombre: "Alcaravea",
    aliases: ["alcaravea", "carum carvi", "fruto de alcaravea", "menta alcaravea", "menta + alcaravea"],
    especie: "Carum carvi L.",
    drogaVegetal: "Fruto entero o troceado (Carvi fructus); el aceite es una preparación diferente",
    usoRespaldado: "Uso tradicional reconocido para aliviar hinchazón y flatulencia.",
    precauciones: ["Evitar en caso de alergia a alcaravea, otras Apiaceae, artemisa o abedul."],
    interaccion: { nivel: "seguir", resumen: "No se describen interacciones clínicas relevantes para el fruto en la monografía." },
    fuenteOficial: `${EMA}/carvi-fructus`,
    fuenteInteracciones: INTERACCIONES,
  },
  {
    id: "alcachofa-hoja",
    nombre: "Alcachofa — hoja",
    aliases: ["alcachofa", "alcachofa hoja", "hoja de alcachofa", "cynara scolymus", "cynara cardunculus"],
    especie: "Cynara cardunculus L. (sin. Cynara scolymus L.)",
    drogaVegetal: "Hoja (Cynarae folium)",
    usoRespaldado: "Uso tradicional reconocido para el alivio de molestias digestivas como plenitud, hinchazón y flatulencia.",
    precauciones: ["No usar en obstrucción de vías biliares, colangitis, cálculos u otros trastornos biliares/hepáticos sin valoración profesional.", "Puede causar alergia en personas sensibles a Asteraceae."],
    interaccion: { nivel: "valorar", resumen: "No se describen interacciones establecidas, pero los trastornos biliares y la medicación concomitante requieren revisión individual." },
    fuenteOficial: `${EMA}/cynarae-folium`,
    fuenteInteracciones: INTERACCIONES,
  },
  {
    id: "lavanda-aceite",
    nombre: "Lavanda — aceite esencial",
    aliases: ["lavanda", "lavanda aromatica", "lavanda aromática", "lavanda oral estandarizada", "aceite de lavanda", "lavandula angustifolia"],
    especie: "Lavandula angustifolia Mill.",
    drogaVegetal: "Aceite esencial; la vía oral estandarizada y la inhalación no son preparaciones equivalentes",
    usoRespaldado: "EMA/HMPC reconoce el uso tradicional del aceite para aliviar síntomas leves de estrés mental, agotamiento y favorecer el sueño.",
    precauciones: ["Puede afectar a la capacidad para conducir en algunas personas.", "No ingerir aceites esenciales salvo que se trate de un medicamento oral autorizado con pauta propia."],
    interaccion: { nivel: "valorar", resumen: "No se han establecido interacciones clínicas en la monografía; conviene revisar la combinación con otros sedantes por posible suma de efectos." },
    fuenteOficial: `${EMA}/lavandulae-aetheroleum`,
    fuenteInteracciones: INTERACCIONES,
  },
  {
    id: "lupulo-estróbilo",
    nombre: "Lúpulo",
    aliases: ["lupulo", "lúpulo", "humulus lupulus", "flor de lupulo", "flor de lúpulo"],
    especie: "Humulus lupulus L.",
    drogaVegetal: "Estróbilos femeninos desecados (Lupuli flos)",
    usoRespaldado: "Uso tradicional reconocido para síntomas leves de estrés mental y ayuda para conciliar el sueño.",
    precauciones: ["Puede causar somnolencia y afectar a la conducción.", "La seguridad en embarazo y lactancia no está establecida."],
    interaccion: { nivel: "valorar", resumen: "No se describen interacciones establecidas; la combinación con sedantes o alcohol debe revisarse por posible suma de efectos." },
    fuenteOficial: `${EMA}/lupuli-flos`,
    fuenteInteracciones: INTERACCIONES,
  },
  {
    id: "pelargonio-raiz",
    nombre: "Pelargonium",
    aliases: ["pelargonium", "pelargonium sidoides", "pelargonium reniforme", "pelargonio", "raiz de pelargonio", "raíz de pelargonio"],
    especie: "Pelargonium sidoides DC / Pelargonium reniforme Curt.",
    drogaVegetal: "Raíz y extractos definidos (Pelargonii radix)",
    usoRespaldado: "Uso tradicional reconocido para tratar síntomas del resfriado común.",
    precauciones: ["Consultar si los síntomas duran más de una semana o empeoran.", "Se han notificado problemas hepáticos y, raramente, sangrado nasal o gingival; suspender y consultar ante signos compatibles."],
    interaccion: { nivel: "valorar", resumen: "No hay una interacción clínica general establecida; revisar especialmente anticoagulación, trastornos hemorrágicos o enfermedad hepática." },
    fuenteOficial: `${EMA}/pelargonii-radix`,
    fuenteInteracciones: INTERACCIONES,
  },
  {
    id: "sauco-flor",
    nombre: "Saúco — flor",
    aliases: ["sauco", "saúco", "sambucus nigra", "flor de sauco", "flor de saúco"],
    especie: "Sambucus nigra L.",
    drogaVegetal: "Flor desecada (Sambuci flos); no equivale al fruto ni a jarabes de composición variable",
    usoRespaldado: "Uso tradicional reconocido para aliviar síntomas tempranos del resfriado común.",
    precauciones: ["La monografía de flor no permite extrapolar eficacia o seguridad a extractos de fruto."],
    interaccion: { nivel: "seguir", resumen: "No se describen interacciones relevantes para la flor en los preparados evaluados." },
    fuenteOficial: `${EMA}/sambuci-flos`,
    fuenteInteracciones: INTERACCIONES,
  },
  {
    id: "tila-flor",
    nombre: "Tila",
    aliases: ["tila", "tilo", "flor de tilo", "tilia cordata", "tilia platyphyllos"],
    especie: "Tilia cordata Mill. / Tilia platyphyllos Scop. y especies admitidas",
    drogaVegetal: "Inflorescencia desecada (Tiliae flos)",
    usoRespaldado: "Uso tradicional para aliviar síntomas del resfriado común y síntomas leves de estrés mental.",
    precauciones: ["No sustituye la valoración de fiebre persistente, dificultad respiratoria o empeoramiento."],
    interaccion: { nivel: "seguir", resumen: "No se describen interacciones clínicas relevantes en la monografía para los preparados evaluados." },
    fuenteOficial: `${EMA}/tiliae-flos`,
    fuenteInteracciones: INTERACCIONES,
  },
  {
    id: "gayuba-hoja",
    nombre: "Gayuba",
    aliases: ["gayuba", "arctostaphylos uva ursi", "uva ursi", "uva-ursi", "hoja de gayuba"],
    especie: "Arctostaphylos uva-ursi (L.) Spreng.",
    drogaVegetal: "Hoja (Uvae ursi folium)",
    usoRespaldado: "Uso tradicional para síntomas leves y recurrentes del tracto urinario inferior en mujeres adultas, después de excluir causas graves.",
    precauciones: ["No sirve para tratar pielonefritis ni una infección complicada.", "EMA limita su uso a mujeres adultas y a periodos cortos; evitar en enfermedad renal."],
    interaccion: { nivel: "valorar", resumen: "No se describen interacciones establecidas, pero por su uso urinario y límites de seguridad debe revisarse si hay enfermedad renal o medicación habitual." },
    fuenteOficial: `${EMA}/uvae-ursi-folium`,
    fuenteInteracciones: INTERACCIONES,
  },
  {
    id: "diente-leon-raiz-parte-aerea",
    nombre: "Diente de león",
    aliases: ["diente de leon", "diente de león", "taraxacum officinale", "taraxaco"],
    especie: "Taraxacum officinale F.H. Wigg.",
    drogaVegetal: "Raíz con parte aérea o partes concretas, según la monografía",
    usoRespaldado: "Uso tradicional para aumentar la cantidad de orina en molestias urinarias menores y, según la droga, molestias digestivas leves.",
    precauciones: ["No usar para forzar diuresis en obstrucción urinaria, cólico renal agudo, deshidratación o cuando se haya indicado restricción de líquidos.", "Revisar trastornos biliares antes de usar la raíz."],
    interaccion: { nivel: "valorar", resumen: "No hay interacciones clínicas establecidas; revisar si se toman diuréticos, litio o existe enfermedad renal/cardiaca por el posible efecto sobre líquidos." },
    fuenteOficial: `${EMA}/taraxaci-radix-cum-herba`,
    fuenteInteracciones: INTERACCIONES,
  },
  {
    id: "cola-caballo-parte-aerea",
    nombre: "Cola de caballo",
    aliases: ["cola de caballo", "equisetum arvense", "equiseti herba"],
    especie: "Equisetum arvense L.",
    drogaVegetal: "Parte aérea estéril desecada (Equiseti herba)",
    usoRespaldado: "Uso tradicional para aumentar la diuresis y favorecer el lavado urinario en molestias menores.",
    precauciones: ["No usar cuando se recomienda reducir líquidos por enfermedad cardiaca o renal.", "No utilizar para intentar expulsar un cálculo durante un cólico u obstrucción."],
    interaccion: { nivel: "valorar", resumen: "No se describen interacciones clínicas establecidas; revisar con diuréticos, litio o trastornos de electrolitos." },
    fuenteOficial: `${EMA}/equiseti-herba`,
    fuenteInteracciones: INTERACCIONES,
  },
  {
    id: "ortiga-hoja-parte-aerea",
    nombre: "Ortiga — hoja/parte aérea",
    aliases: ["ortiga", "ortiga hoja", "hoja de ortiga", "urtica dioica", "urtica urens", "urticae herba"],
    especie: "Urtica dioica L. / Urtica urens L.",
    drogaVegetal: "Hoja o parte aérea (Urticae folium / herba)",
    usoRespaldado: "Uso tradicional para molestias articulares menores y para aumentar la diuresis en molestias urinarias leves, según el preparado.",
    precauciones: ["No usar como tratamiento de anemia, gota o infección urinaria.", "Evitar cuando exista restricción de líquidos por enfermedad cardiaca o renal."],
    interaccion: { nivel: "valorar", resumen: "No se describen interacciones clínicas establecidas; revisar si se usan diuréticos, antihipertensivos o medicación para diabetes." },
    fuenteOficial: `${EMA}/urticae-herba`,
    fuenteInteracciones: INTERACCIONES,
  },
  {
    id: "ortiga-raiz",
    nombre: "Ortiga — raíz",
    aliases: ["ortiga raiz", "ortiga raíz", "raiz de ortiga", "raíz de ortiga", "urticae radix"],
    especie: "Urtica dioica L. / Urtica urens L.",
    drogaVegetal: "Raíz (Urticae radix)",
    usoRespaldado: "Uso tradicional para aliviar síntomas urinarios bajos relacionados con hiperplasia benigna de próstata, después de descartar causas importantes.",
    precauciones: ["No usar antes de una evaluación de los síntomas prostáticos.", "Sangre en orina, fiebre, dolor o retención requieren valoración médica."],
    interaccion: { nivel: "valorar", resumen: "No se describen interacciones clínicas establecidas; debe revisarse junto con medicación urológica, diuréticos y antihipertensivos." },
    fuenteOficial: `${EMA}/urticae-radix`,
    fuenteInteracciones: INTERACCIONES,
  },
  {
    id: "castano-indias-semilla",
    nombre: "Castaño de Indias",
    aliases: ["castano de indias", "castaño de indias", "aesculus hippocastanum", "semilla de castano de indias", "semilla de castaño de indias"],
    especie: "Aesculus hippocastanum L.",
    drogaVegetal: "Semilla; el uso oral se refiere a extractos secos estandarizados concretos",
    usoRespaldado: "Determinados extractos estandarizados tienen uso bien establecido para síntomas de insuficiencia venosa crónica; otras preparaciones solo tienen uso tradicional.",
    precauciones: ["Las semillas crudas y preparados no estandarizados no son seguros para ingestión.", "Una pierna súbitamente hinchada, roja o dolorosa requiere valoración urgente."],
    interaccion: { nivel: "valorar", resumen: "No se describen interacciones establecidas en la monografía; revisar anticoagulación/antiagregación y enfermedad renal o hepática antes del uso oral." },
    fuenteOficial: `${EMA}/hippocastani-semen`,
    fuenteInteracciones: INTERACCIONES,
  },
  {
    id: "cimicifuga-rizoma",
    nombre: "Cimicífuga",
    aliases: ["cimicifuga", "cimicífuga", "actaea racemosa", "cimicifuga racemosa", "black cohosh"],
    especie: "Actaea racemosa L. (sin. Cimicifuga racemosa)",
    drogaVegetal: "Rizoma y extractos definidos (Cimicifugae rhizoma)",
    usoRespaldado: "Preparados concretos se utilizan para aliviar síntomas menopáusicos como sofocos y sudoración; el efecto no se extrapola a cualquier producto.",
    precauciones: ["Se han notificado casos de lesión hepática; suspender y consultar ante ictericia, orina oscura, cansancio inusual o dolor abdominal alto.", "Revisar antecedentes hormonodependientes."],
    interaccion: { nivel: "monitorizar", resumen: "La información de interacciones es limitada; debe revisarse si hay tratamiento hormonal, tamoxifeno, enfermedad hepática o medicación hepatotóxica." },
    fuenteOficial: `${EMA}/cimicifugae-rhizoma`,
    fuenteInteracciones: INTERACCIONES,
  },
  {
    id: "arbol-te-aceite",
    nombre: "Árbol del té — aceite esencial",
    aliases: ["aceite de arbol del te", "aceite de árbol del té", "arbol del te", "árbol del té", "melaleuca alternifolia", "tea tree oil"],
    especie: "Melaleuca alternifolia (Maiden & Betche) Cheel y especies admitidas",
    drogaVegetal: "Aceite esencial obtenido de hojas y ramas terminales",
    usoRespaldado: "Uso tradicional tópico para pequeñas heridas superficiales, picaduras, forúnculos/acné leves, pie de atleta leve e inflamación menor de la boca, según formulación.",
    precauciones: ["No debe tragarse: la ingestión puede ser tóxica.", "Puede irritar o sensibilizar la piel y nunca debe aplicarse sin una formulación adecuada en mucosas sensibles."],
    interaccion: { nivel: "evitar", resumen: "Evitar la vía oral y el uso intravaginal. No sustituye antifúngicos en candidiasis oral o vaginal." },
    fuenteOficial: `${EMA}/melaleucae-aetheroleum`,
    fuenteInteracciones: INTERACCIONES,
  },
  {
    id: "calendula-flor",
    nombre: "Caléndula — flor",
    aliases: ["calendula", "caléndula", "calendula officinalis", "calendula topica", "caléndula tópica"],
    especie: "Calendula officinalis L.",
    drogaVegetal: "Flor y preparaciones tópicas definidas (Calendulae flos)",
    usoRespaldado: "Uso tradicional para inflamaciones menores de la piel, ayuda en heridas pequeñas y determinadas irritaciones leves de boca o garganta.",
    precauciones: ["No aplicar sobre heridas profundas o infectadas sin valoración.", "Puede causar alergia en personas sensibles a Asteraceae."],
    interaccion: { nivel: "seguir", resumen: "No se describen interacciones relevantes para el uso tópico evaluado." },
    fuenteOficial: `${EMA}/calendulae-flos`,
    fuenteInteracciones: INTERACCIONES,
  },
  {
    id: "clavo-aceite",
    nombre: "Clavo — aceite esencial",
    aliases: ["clavo", "aceite de clavo", "clavo aceite", "clavo aceite de clavo", "syzygium aromaticum", "eugenol"],
    especie: "Syzygium aromaticum (L.) Merr. & L.M. Perry",
    drogaVegetal: "Aceite esencial del botón floral (Caryophylli floris aetheroleum)",
    usoRespaldado: "Uso tradicional para alivio temporal del dolor dental y determinadas inflamaciones menores de boca o garganta, mediante preparados adecuados.",
    precauciones: ["No cura un absceso dental ni sustituye atención odontológica.", "El aceite concentrado puede lesionar mucosas y su ingestión puede ser tóxica, especialmente en niños."],
    interaccion: { nivel: "monitorizar", resumen: "Evitar dosis altas o ingestión; revisar anticoagulantes/antiagregantes y trastornos hemorrágicos antes de usar productos concentrados." },
    fuenteOficial: `${EMA}/caryophylli-floris-aetheroleum`,
    fuenteInteracciones: INTERACCIONES,
  },
  {
    id: "harpagofito-raiz",
    nombre: "Harpagofito",
    aliases: ["harpagofito", "harpagófito", "harpagophytum procumbens", "harpagophytum zeyheri", "garra del diablo"],
    especie: "Harpagophytum procumbens DC. / Harpagophytum zeyheri Decne.",
    drogaVegetal: "Raíz secundaria (Harpagophyti radix)",
    usoRespaldado: "Uso tradicional para aliviar dolor articular menor y molestias digestivas leves; no modifica la artrosis.",
    precauciones: ["Precaución en úlcera gastroduodenal y cálculos biliares.", "El dolor articular con inflamación importante, fiebre o pérdida de función requiere valoración."],
    interaccion: { nivel: "valorar", resumen: "No se describen interacciones clínicas firmes; revisar anticoagulantes, antidiabéticos y medicación cardiovascular antes de usar extractos." },
    fuenteOficial: `${EMA}/harpagophyti-radix`,
    fuenteInteracciones: INTERACCIONES,
  },
  {
    id: "salvia-hoja",
    nombre: "Salvia — hoja",
    aliases: ["salvia", "salvia officinalis", "salvia en enjuague", "salvia en gargaras", "salvia en gárgaras"],
    especie: "Salvia officinalis L.",
    drogaVegetal: "Hoja (Salviae officinalis folium); el aceite esencial es una preparación diferente",
    usoRespaldado: "Uso tradicional para molestias digestivas leves, sudoración excesiva y uso local en inflamaciones de boca o garganta.",
    precauciones: ["No ingerir aceite esencial concentrado: la tuyona puede ser neurotóxica.", "Evitar dosis medicinales durante embarazo/lactancia sin indicación profesional."],
    interaccion: { nivel: "monitorizar", resumen: "No se describen interacciones establecidas para la hoja; los extractos concentrados o aceites deben revisarse con anticonvulsivantes y medicación para diabetes." },
    fuenteOficial: `${EMA}/salviae-officinalis-folium`,
    fuenteInteracciones: INTERACCIONES,
  },
  {
    id: "matricaria-parte-aerea",
    nombre: "Matricaria / Feverfew",
    aliases: ["matricaria", "feverfew", "tanacetum parthenium", "matricaria feverfew"],
    especie: "Tanacetum parthenium (L.) Sch.Bip.",
    drogaVegetal: "Parte aérea; los estudios usan preparaciones y concentraciones variables",
    usoRespaldado: "Se ha estudiado para prevención de migraña, pero los resultados son inconsistentes y no sirve para tratar una crisis aguda.",
    precauciones: ["Evitar durante el embarazo.", "Puede causar molestias digestivas, erupción o inflamación de la boca; no suspender bruscamente tras uso prolongado sin consejo profesional."],
    interaccion: { nivel: "monitorizar", resumen: "Puede interactuar con medicamentos, especialmente anticoagulantes o antiagregantes; requiere revisión individual." },
    fuenteOficial: `${NCCIH}/feverfew`,
    fuenteInteracciones: `${NCCIH}/feverfew`,
  },
  {
    id: "guarana-semilla",
    nombre: "Guaraná",
    aliases: ["guarana", "guaraná", "paullinia cupana", "guarana y otros estimulantes vegetales", "guaraná y otros estimulantes vegetales"],
    especie: "Paullinia cupana Kunth",
    drogaVegetal: "Semilla y preparados con cafeína (Paulliniae semen)",
    usoRespaldado: "Uso tradicional como estimulante frente a fatiga o debilidad; el efecto se relaciona principalmente con su cafeína.",
    precauciones: ["Puede empeorar palpitaciones, ansiedad, insomnio e hipertensión.", "La cantidad total de cafeína puede no quedar clara si se combina con café, té o energéticas."],
    interaccion: { nivel: "monitorizar", resumen: "Evitar combinar con otros estimulantes; revisar medicación cardiovascular, descongestionantes, algunos antidepresivos y fármacos que alteran el metabolismo de cafeína." },
    fuenteOficial: `${EMA}/paulliniae-semen`,
    fuenteInteracciones: INTERACCIONES,
  },
  {
    id: "cardo-mariano-fruto",
    nombre: "Cardo mariano / Silimarina",
    aliases: ["cardo mariano", "silimarina", "silybum marianum", "milk thistle"],
    especie: "Silybum marianum (L.) Gaertn.",
    drogaVegetal: "Fruto; silimarina y extractos no son equivalentes a cualquier polvo de fruto",
    usoRespaldado: "Se ha estudiado en distintas enfermedades hepáticas, pero no hay evidencia suficiente para sustituir el manejo de hígado graso, hepatitis u otra enfermedad hepática.",
    precauciones: ["Los suplementos pueden variar mucho en contenido y calidad.", "Puede causar molestias digestivas y alergia, especialmente en personas sensibles a Asteraceae."],
    interaccion: { nivel: "valorar", resumen: "Las interacciones clínicas no están bien definidas; revisar medicación hepática, antidiabéticos y fármacos de margen estrecho." },
    fuenteOficial: `${NCCIH}/milk-thistle`,
    fuenteInteracciones: `${NCCIH}/milk-thistle`,
  },
  {
    id: "calabaza-semilla",
    nombre: "Semilla de calabaza",
    aliases: ["semilla de calabaza", "semillas de calabaza", "cucurbita pepo", "cucurbitae semen"],
    especie: "Cucurbita pepo L. y especies/preparaciones admitidas",
    drogaVegetal: "Semilla madura desecada y preparados definidos",
    usoRespaldado: "Uso tradicional para aliviar síntomas urinarios bajos relacionados con hiperplasia benigna de próstata o vejiga hiperactiva, después de descartar causas graves.",
    precauciones: ["No sustituye la evaluación de sangre en orina, dolor, fiebre, retención o empeoramiento progresivo."],
    interaccion: { nivel: "seguir", resumen: "No se describen interacciones clínicas relevantes para los preparados evaluados." },
    fuenteOficial: `${EMA}/cucurbitae-semen`,
    fuenteInteracciones: INTERACCIONES,
  },
  {
    id: "hamamelis-topico",
    nombre: "Hamamelis — uso tópico",
    aliases: ["hamamelis", "hamamelis topico", "hamamelis tópico", "hamamelis virginiana", "agua de hamamelis"],
    especie: "Hamamelis virginiana L.",
    drogaVegetal: "Hoja, corteza o destilado, según la preparación tópica",
    usoRespaldado: "Uso tradicional tópico para irritación e inflamación cutánea menor y alivio sintomático de molestias hemorroidales externas.",
    precauciones: ["No ingerir preparados tópicos.", "El sangrado rectal nuevo, abundante o persistente requiere valoración médica."],
    interaccion: { nivel: "seguir", resumen: "No se describen interacciones relevantes para el uso tópico indicado." },
    fuenteOficial: `${EMA}/hamamelidis-cortex`,
    fuenteInteracciones: INTERACCIONES,
  },
  {
    id: "agrimonia-parte-aerea",
    nombre: "Agrimonia",
    aliases: ["agrimonia", "agrimonia eupatoria", "agrimoniae herba"],
    especie: "Agrimonia eupatoria L.",
    drogaVegetal: "Parte aérea desecada (Agrimoniae herba)",
    usoRespaldado: "Uso tradicional para diarrea leve, gargarismos en inflamación menor de boca/garganta y lavado cutáneo de pequeñas inflamaciones o heridas superficiales.",
    precauciones: ["No sustituye rehidratación ni valoración ante sangre, fiebre alta, deshidratación o diarrea persistente."],
    interaccion: { nivel: "seguir", resumen: "No se describen interacciones clínicas relevantes para los preparados evaluados." },
    fuenteOficial: `${EMA}/agrimoniae-herba`,
    fuenteInteracciones: INTERACCIONES,
  },
  {
    id: "aloe-vera-gel-topico",
    nombre: "Aloe vera — gel tópico",
    aliases: ["aloe vera", "aloe vera topico", "aloe vera tópico", "aloe vera topico oral", "aloe vera tópico oral", "aloe barbadensis"],
    especie: "Aloe vera (L.) Burm.f. (sin. Aloe barbadensis Mill.)",
    drogaVegetal: "Gel interno de la hoja para uso tópico; no equivale al látex amarillo ni a extractos de hoja entera",
    usoRespaldado: "El gel tópico se ha estudiado en algunas afecciones cutáneas, pero el beneficio depende de la formulación y la evidencia es limitada para muchas indicaciones.",
    precauciones: ["Puede causar quemazón, picor, erupción o eccema.", "No aplicar un producto cutáneo dentro de la boca; el látex oral puede causar cólicos, diarrea y problemas graves."],
    interaccion: { nivel: "evitar", resumen: "Evitar la ingestión de látex o extractos de hoja entera como si fueran gel tópico; pueden alterar electrolitos e interactuar con varios medicamentos." },
    fuenteOficial: `${NCCIH}/aloe-vera`,
    fuenteInteracciones: `${NCCIH}/aloe-vera`,
  },
  {
    id: "boswellia-resina",
    nombre: "Boswellia",
    aliases: ["boswellia", "boswellia serrata", "incienso indio"],
    especie: "Boswellia serrata Roxb. ex Colebr.",
    drogaVegetal: "Gomorresina y extractos de composición variable",
    usoRespaldado: "Algunos estudios sugieren pequeñas mejoras de dolor y función en artrosis, pero la evidencia global es débil y no permite equiparar todos los extractos.",
    precauciones: ["No sustituye ejercicio, control de peso ni tratamientos indicados.", "La seguridad depende del extracto; faltan datos suficientes en embarazo y lactancia."],
    interaccion: { nivel: "valorar", resumen: "Los datos de interacción son limitados; revisar anticoagulantes/antiagregantes y medicación antiinflamatoria o inmunológica." },
    fuenteOficial: `${NCCIH}/boswellia`,
    fuenteInteracciones: `${NCCIH}/boswellia`,
  },
  {
    id: "arandano-rojo-fruto",
    nombre: "Arándano rojo",
    aliases: ["arandano rojo", "arándano rojo", "cranberry", "vaccinium macrocarpon"],
    especie: "Vaccinium macrocarpon Aiton",
    drogaVegetal: "Fruto, jugo o extractos; las concentraciones de proantocianidinas varían entre productos",
    usoRespaldado: "Puede disminuir el riesgo de infección urinaria sintomática recurrente en algunas mujeres, pero no trata una infección activa.",
    precauciones: ["No retrasar consulta ante fiebre, dolor lumbar, sangre en orina, embarazo o síntomas persistentes.", "Cantidades altas pueden causar molestias digestivas y aumentar el riesgo de cálculos en personas susceptibles."],
    interaccion: { nivel: "monitorizar", resumen: "Se han comunicado cambios con warfarina; si existe anticoagulación debe revisarse el producto y vigilarse el tratamiento." },
    fuenteOficial: `${NCCIH}/cranberry`,
    fuenteInteracciones: `${NCCIH}/cranberry`,
  },
  {
    id: "canela-corteza",
    nombre: "Canela",
    aliases: ["canela", "cinnamomum verum", "cinnamomum cassia", "cinnamomum aromaticum", "cinnamon"],
    especie: "Cinnamomum verum J.Presl / Cinnamomum cassia y especies comerciales",
    drogaVegetal: "Corteza o extractos; la composición y el contenido en cumarina dependen de la especie",
    usoRespaldado: "Los estudios para control de glucosa ofrecen resultados contradictorios; no sustituye dieta, ejercicio ni medicación antidiabética.",
    precauciones: ["La canela cassia puede aportar cantidades relevantes de cumarina y aumentar el riesgo hepático en uso prolongado o dosis altas.", "Los suplementos no equivalen al uso culinario."],
    interaccion: { nivel: "monitorizar", resumen: "Puede sumar efectos con antidiabéticos; revisar también anticoagulantes y medicación hepatotóxica, especialmente con extractos concentrados." },
    fuenteOficial: `${NCCIH}/cinnamon`,
    fuenteInteracciones: `${NCCIH}/cinnamon`,
  },
  {
    id: "levadura-roja-arroz",
    nombre: "Arroz de levadura roja",
    aliases: ["arroz de levadura roja", "red yeast rice", "monascus purpureus", "monacolina k", "monacolina"],
    especie: "Monascus purpureus cultivado sobre Oryza sativa (producto fermentado)",
    drogaVegetal: "Arroz fermentado; el contenido de monacolina K y contaminantes varía ampliamente",
    usoRespaldado: "Los productos con suficiente monacolina K pueden reducir el colesterol, pero actúan de forma similar a lovastatina y no son un complemento inocuo.",
    precauciones: ["Puede causar los mismos efectos adversos musculares, hepáticos y renales que una estatina.", "Algunos productos pueden contener citrinina, potencialmente nefrotóxica."],
    interaccion: { nivel: "evitar", resumen: "No combinar a ciegas con estatinas, fibratos, ciertos antibióticos/antifúngicos, ciclosporina, pomelo o fármacos que elevan el riesgo muscular/hepático." },
    fuenteOficial: `${NCCIH}/red-yeast-rice`,
    fuenteInteracciones: `${NCCIH}/red-yeast-rice`,
  },
  {
    id: "te-verde-hoja-extracto",
    nombre: "Té verde",
    aliases: ["te verde", "té verde", "camellia sinensis", "extracto de te verde", "extracto de té verde"],
    especie: "Camellia sinensis (L.) Kuntze",
    drogaVegetal: "Hoja/bebida o extractos concentrados; no tienen el mismo perfil de seguridad",
    usoRespaldado: "La bebida forma parte de la alimentación; algunos extractos se han estudiado para distintas condiciones, pero los beneficios son modestos o inciertos según la indicación.",
    precauciones: ["Los extractos concentrados se han relacionado raramente con lesión hepática.", "Contiene cafeína y puede empeorar insomnio, ansiedad o palpitaciones."],
    interaccion: { nivel: "monitorizar", resumen: "Los extractos pueden interactuar con medicamentos, incluidos algunos cardiovasculares; revisar anticoagulación y fármacos de margen estrecho." },
    fuenteOficial: `${NCCIH}/green-tea`,
    fuenteInteracciones: `${NCCIH}/green-tea`,
  },
  {
    id: "soja-isoflavonas",
    nombre: "Isoflavonas de soja",
    aliases: ["isoflavonas de soja", "soja isoflavonas", "glycine max", "extracto de soja"],
    especie: "Glycine max (L.) Merr.",
    drogaVegetal: "Alimento de soja, proteína o mezclas de isoflavonas; no son equivalentes",
    usoRespaldado: "La soja o sus isoflavonas pueden reducir de forma pequeña la frecuencia/intensidad de sofocos en algunas mujeres.",
    precauciones: ["El efecto es modesto y variable.", "Revisar antecedentes de enfermedad hormonodependiente y no sustituir el cuidado de salud ósea o cardiovascular."],
    interaccion: { nivel: "monitorizar", resumen: "Puede alterar la absorción de levotiroxina si se toma cerca; separar según indicación profesional y revisar otros tratamientos hormonales." },
    fuenteOficial: `${NCCIH}/soy`,
    fuenteInteracciones: `${NCCIH}/soy`,
  },
  {
    id: "berberina-compuesto",
    nombre: "Berberina",
    aliases: ["berberina", "berberine"],
    especie: "Alcaloide presente en Berberis spp., Hydrastis canadensis y otras plantas",
    drogaVegetal: "Compuesto aislado/suplemento; no es una única droga vegetal ni equivale a cualquier planta que lo contenga",
    usoRespaldado: "Se investiga para glucosa y factores cardiometabólicos, pero no sustituye tratamiento y la calidad/dosis de suplementos es variable.",
    precauciones: ["Puede causar molestias gastrointestinales.", "No usar durante embarazo, lactancia ni en recién nacidos; requiere especial cautela en niños."],
    interaccion: { nivel: "monitorizar", resumen: "Puede modificar glucosa y múltiples vías de metabolización/transporte de fármacos; revisar antidiabéticos, anticoagulantes, inmunosupresores y medicación de margen estrecho." },
    fuenteOficial: `${NCCIH}/berberine-and-weight-loss-what-you-need-to-know`,
    fuenteInteracciones: `${NCCIH}/berberine-and-weight-loss-what-you-need-to-know`,
  },
  {
    id: "algas-yodo-grupo",
    nombre: "Algas ricas en yodo",
    aliases: ["algas ricas en yodo", "alga rica en yodo", "kelp", "kombu", "fucus", "laminaria"],
    especie: "Grupo de especies marinas; el contenido de yodo varía ampliamente",
    drogaVegetal: "Alga alimentaria o suplemento; no existe equivalencia de dosis entre especies, lotes y extractos",
    usoRespaldado: "Son fuentes de yodo, pero no se recomiendan como tratamiento rutinario del hipotiroidismo o hipertiroidismo y un exceso puede alterar la función tiroidea.",
    precauciones: ["El contenido de yodo puede ser muy alto e impredecible.", "Evitar suplementos sin cuantificación fiable si existe enfermedad tiroidea, embarazo o tratamiento con yodo."],
    interaccion: { nivel: "monitorizar", resumen: "El exceso de yodo puede interferir con antitiroideos y afectar al control de tratamientos tiroideos; requiere revisión individual." },
    fuenteOficial: "https://ods.od.nih.gov/factsheets/Iodine-DatosEnEspanol/",
    fuenteOficialEtiqueta: "NIH ODS — yodo",
    fuenteInteracciones: "https://ods.od.nih.gov/factsheets/Iodine-DatosEnEspanol/",
  },
  {
    id: "avena-coloidal-topica",
    nombre: "Avena coloidal — uso tópico",
    aliases: ["avena coloidal", "avena coloidal topica", "avena coloidal tópica", "colloidal oatmeal", "avena sativa topica", "avena sativa tópica"],
    especie: "Avena sativa L.",
    drogaVegetal: "Harina de avena coloidal formulada como protector cutáneo; no equivale a avena alimentaria",
    usoRespaldado: "Ingrediente activo reconocido por la FDA en protectores cutáneos de venta sin receta; puede aliviar temporalmente picor e irritación menores cuando la formulación cumple la monografía.",
    precauciones: ["Suspender si aumenta la irritación o aparece reacción alérgica.", "No aplicar sobre infección profunda o heridas importantes sin valoración."],
    interaccion: { nivel: "seguir", resumen: "No se describen interacciones sistémicas relevantes para el uso tópico correcto." },
    fuenteOficial: "https://www.accessdata.fda.gov/scripts/cder/omuf/index.cfm?event=monographsearch&val=Colloidal+Oatmeal",
    fuenteOficialEtiqueta: "Monografía OTC de la FDA",
    fuenteInteracciones: "https://www.accessdata.fda.gov/scripts/cder/omuf/index.cfm?event=monographsearch&val=Colloidal+Oatmeal",
  },
  {
    id: "brezo-parte-aerea",
    nombre: "Brezo / Brecina",
    aliases: ["brezo", "brecina", "calluna vulgaris", "erica cinerea"],
    especie: "Calluna vulgaris (L.) Hull / Erica cinerea L.",
    drogaVegetal: "Sumidad florida u hoja, según la especie y preparación",
    usoRespaldado: "El Vademécum recoge un uso tradicional diurético y urinario; no existe evidencia suficiente para presentarlo como tratamiento de una infección activa.",
    precauciones: ["No se ha establecido la seguridad en embarazo, lactancia o infancia.", "No forzar la diuresis si existe insuficiencia renal/cardiaca, obstrucción, deshidratación o hipertensión descompensada."],
    interaccion: { nivel: "valorar", resumen: "No se describen interacciones clínicas en la ficha, pero debe revisarse con diuréticos, antihipertensivos, litio o enfermedad renal/cardiaca." },
    fuenteVademecum: "https://www.fitoterapia.net/vademecum/plantas/brezo.html",
    fuenteInteracciones: INTERACCIONES,
  },
  {
    id: "olmo-resbaladizo-corteza",
    nombre: "Olmo resbaladizo",
    aliases: ["olmo resbaladizo", "slippery elm", "ulmus rubra", "olmo americano"],
    especie: "Ulmus rubra Muhl.",
    drogaVegetal: "Corteza interna; la ficha del Vademécum también agrupa otras especies de Ulmus",
    usoRespaldado: "Uso popular como demulcente; la evidencia clínica para reflujo gastroesofágico o laringofaríngeo es insuficiente.",
    precauciones: ["No debe presentarse como tratamiento demostrado del reflujo.", "Los síntomas persistentes, dificultad para tragar, pérdida de peso o sangrado requieren valoración médica."],
    interaccion: { nivel: "monitorizar", resumen: "Los mucílagos pueden retrasar la absorción de otros medicamentos; separar las tomas y revisar fármacos de margen estrecho." },
    fuenteVademecum: "https://www.fitoterapia.net/vademecum/plantas/olmo.html",
    fuenteInteracciones: INTERACCIONES,
  },
  {
    id: "phyllanthus-niruri-parte-aerea",
    nombre: "Phyllanthus niruri / Rompepiedra",
    aliases: ["phyllanthus niruri", "rompepiedra", "chancapiedra", "chanca piedra"],
    especie: "Phyllanthus niruri L. y especies próximas comercializadas con nombres semejantes",
    drogaVegetal: "Parte aérea o planta entera, según el preparado",
    usoRespaldado: "Los estudios disponibles sugieren un posible papel coadyuvante urinario, pero la evidencia todavía es insuficiente para sustituir prevención individualizada o tratamiento de la litiasis.",
    precauciones: ["No usar durante embarazo, lactancia, en menores de 18 años ni de forma prolongada sin supervisión.", "No intentar expulsar un cálculo ante dolor intenso, fiebre, vómitos, anuria o posible obstrucción."],
    interaccion: { nivel: "valorar", resumen: "No se describen interacciones clínicas confirmadas; por posibles efectos sobre glucosa y presión debe revisarse con antidiabéticos y antihipertensivos." },
    fuenteVademecum: "https://www.fitoterapia.net/vademecum/plantas/rompepiedra.html",
    fuenteOficial: "https://pubmed.ncbi.nlm.nih.gov/29617079/",
    fuenteOficialEtiqueta: "Estudio clínico indexado en PubMed",
    fuenteInteracciones: INTERACCIONES,
  },
];
