import { useState } from "react";

type Nivel = "sin-datos" | "favorable" | "vigilar" | "alta" | "muy-alta";
type Resultado = { nivel:Nivel; titulo:string; accion:string; detalle:string; icono:string };

function interpretar(sis:number,dia:number):Resultado {
 if(!sis||!dia)return{nivel:"sin-datos",titulo:"Introduce las dos cifras",accion:"",detalle:"Necesitamos sistólica y diastólica.",icono:"🩺"};
 if(sis>=180||dia>=120)return{nivel:"muy-alta",titulo:"Cifra muy elevada",accion:"Repite la medición tras unos minutos de reposo.",detalle:"Si se mantiene muy elevada, necesita valoración médica. Si además hay dolor de pecho, falta de aire, confusión, dificultad para hablar, pérdida de fuerza o alteración visual importante, busca atención urgente.",icono:"🚨"};
 if(sis>=140||dia>=90)return{nivel:"alta",titulo:"Presión elevada",accion:"Repite y registra nuevas mediciones.",detalle:"Una sola lectura no diagnostica hipertensión. Si estas cifras se repiten, conviene valoración profesional.",icono:"⚠️"};
 if(sis>=130||dia>=85)return{nivel:"vigilar",titulo:"Conviene vigilar",accion:"Comprueba la tendencia en nuevas mediciones.",detalle:"Está por encima del rango orientativamente favorable. La valoración depende de varias mediciones y del riesgo cardiovascular individual.",icono:"👀"};
 return{nivel:"favorable",titulo:"Lectura orientativamente favorable",accion:"Mantén el seguimiento habitual.",detalle:"Una lectura favorable no permite suspender tratamiento ni descarta hipertensión si ya ha sido diagnosticada.",icono:"✓"};
}

export default function ModuloTensionArterial(){
 const[sistolica,setSistolica]=useState("");const[diastolica,setDiastolica]=useState("");const[mostrar,setMostrar]=useState(false);
 const r=interpretar(Number(sistolica),Number(diastolica));
 const tema=r.nivel==="muy-alta"?{f:"#fff0f0",b:"#c83d3d",c:"#8d1717"}:r.nivel==="alta"?{f:"#fff4e5",b:"#d17a12",c:"#8a4a00"}:r.nivel==="vigilar"?{f:"#fffbe8",b:"#b89c16",c:"#6f5c00"}:{f:"#edf8f1",b:"#57926e",c:"#245c3a"};
 const limpiar=()=>{setSistolica("");setDiastolica("");setMostrar(false)};
 return <section style={s.card} aria-label="Control visual de tensión arterial">
  <div style={s.encabezado}><span style={s.icono}>🩺</span><div><h2 style={s.h2}>Tensión arterial</h2><p style={s.sub}>Escribe las dos cifras de tu tensiómetro y obtén una orientación sencilla.</p></div></div>
  <div style={s.preparacion}><b>Para medir bien</b><div style={s.pasos}><span>🪑 Reposa 5 min</span><span>🦶 Pies apoyados</span><span>💪 Brazo a la altura del corazón</span><span>🤫 No hables</span></div></div>
  <div style={s.medidores}>
   <label style={s.label}><b style={s.labelTitulo}>SISTÓLICA</b><span style={s.labelAyuda}>número de arriba</span><input aria-label="Presión sistólica" inputMode="numeric" value={sistolica} onChange={e=>{setSistolica(e.target.value.replace(/\D/g,"").slice(0,3));setMostrar(false)}} placeholder="120" style={s.input}/><small>mmHg</small></label>
   <div style={s.barra}>/</div>
   <label style={s.label}><b style={s.labelTitulo}>DIASTÓLICA</b><span style={s.labelAyuda}>número de abajo</span><input aria-label="Presión diastólica" inputMode="numeric" value={diastolica} onChange={e=>{setDiastolica(e.target.value.replace(/\D/g,"").slice(0,3));setMostrar(false)}} placeholder="80" style={s.input}/><small>mmHg</small></label>
  </div>
  <button style={{...s.boton,opacity:!sistolica||!diastolica?.55:1}} disabled={!sistolica||!diastolica} onClick={()=>setMostrar(true)}>Ver resultado</button>
  {mostrar&&<div style={{...s.resultado,background:tema.f,borderColor:tema.b,color:tema.c}}>
    <div style={s.estadoIcono}>{r.icono}</div><div style={s.cifra}>{sistolica} / {diastolica}<small style={s.unidad}> mmHg</small></div><h3 style={s.resultadoTitulo}>{r.titulo}</h3><div style={s.accion}>{r.accion}</div><p style={s.detalle}>{r.detalle}</p>
    <div style={s.recordatorio}><b>Importante:</b> una medición aislada no diagnostica hipertensión. No cambies ni suspendas medicación por este resultado.</div>
    <button onClick={limpiar} style={s.nueva}>Hacer otra medición</button>
  </div>}
  <div style={s.leyenda} aria-label="Guía orientativa"><div><span style={{...s.punto,background:"#57926e"}}/>Favorable</div><div><span style={{...s.punto,background:"#b89c16"}}/>Vigilar</div><div><span style={{...s.punto,background:"#d17a12"}}/>Elevada</div><div><span style={{...s.punto,background:"#c83d3d"}}/>Muy elevada</div></div>
  <details style={s.details}><summary style={s.summary}>Cómo medirla correctamente</summary><ol style={s.lista}><li>Evita ejercicio, tabaco y cafeína durante los 30 minutos previos cuando sea posible.</li><li>Vacía la vejiga y descansa sentado al menos 5 minutos.</li><li>Espalda apoyada, piernas sin cruzar y pies planos en el suelo.</li><li>Manguito adecuado sobre el brazo desnudo y brazo apoyado a la altura del corazón.</li><li>No hables durante la medición. Para seguimiento, usa varias lecturas según la pauta indicada por tu profesional.</li></ol></details>
 </section>;
}
const s:Record<string,React.CSSProperties>={card:{maxWidth:1100,margin:"18px auto 0",padding:"clamp(16px,4vw,24px)",background:"#fff",border:"2px solid #cfe0d7",borderRadius:18,fontFamily:"Arial,sans-serif",boxShadow:"0 4px 18px rgba(20,70,50,.07)"},encabezado:{display:"flex",gap:12,alignItems:"center"},icono:{fontSize:38},h2:{margin:"0 0 4px",fontSize:"clamp(23px,6vw,29px)",color:"#214c3b"},sub:{margin:0,color:"#52665d",lineHeight:1.4},preparacion:{marginTop:16,padding:13,borderRadius:12,background:"#f4f8f7",color:"#334b41"},pasos:{display:"flex",flexWrap:"wrap",gap:"8px 14px",marginTop:9,fontSize:14},medidores:{display:"flex",alignItems:"center",justifyContent:"center",gap:"clamp(6px,3vw,14px)",margin:"22px 0 16px",flexWrap:"nowrap"},label:{display:"flex",flexDirection:"column",alignItems:"center",width:"min(39vw,150px)"},labelTitulo:{fontSize:13,color:"#214c3b"},labelAyuda:{fontSize:11,color:"#66776f",marginBottom:5},input:{boxSizing:"border-box",width:"100%",fontSize:"clamp(34px,10vw,44px)",fontWeight:900,textAlign:"center",padding:"9px 3px",border:"2px solid #8fb3a3",borderRadius:14,color:"#173c2e",background:"#fbfdfc"},barra:{fontSize:34,fontWeight:800,color:"#78958a",paddingTop:15},boton:{display:"block",width:"min(100%,420px)",margin:"0 auto",padding:"16px 18px",border:0,borderRadius:13,background:"#216b4d",color:"#fff",fontSize:18,fontWeight:900,cursor:"pointer"},resultado:{marginTop:20,padding:"20px 15px",border:"3px solid",borderRadius:16,textAlign:"center"},estadoIcono:{fontSize:34},cifra:{fontSize:"clamp(32px,10vw,46px)",fontWeight:900},unidad:{fontSize:14},resultadoTitulo:{fontSize:23,margin:"5px 0"},accion:{fontWeight:900,fontSize:17,marginTop:7},detalle:{maxWidth:720,margin:"8px auto",lineHeight:1.5},recordatorio:{margin:"14px auto 0",maxWidth:760,padding:11,borderRadius:9,background:"rgba(255,255,255,.72)",fontSize:14,lineHeight:1.45},nueva:{marginTop:14,padding:"11px 16px",border:"1px solid currentColor",borderRadius:10,background:"#fff",fontWeight:800,cursor:"pointer"},leyenda:{display:"flex",justifyContent:"center",flexWrap:"wrap",gap:"8px 15px",marginTop:18,fontSize:12,color:"#53665d"},punto:{display:"inline-block",width:10,height:10,borderRadius:"50%",marginRight:5},details:{marginTop:17,borderTop:"1px solid #dbe5e0",paddingTop:14},summary:{cursor:"pointer",fontWeight:800,color:"#214c3b"},lista:{lineHeight:1.65,paddingLeft:22}};